# Autogenerated R wrappers

#' @rdname graphene
#' @title grapheneBoxAlloc
#'
#' @return Box
#' @export
grapheneBoxAlloc <- function() {
  .Call("R_graphene_box_alloc")$result
}


#' @rdname graphene
#' @title grapheneBoxContainsBox
#'
#' @param a Box
#' @param b Box
#' @return gboolean
#' @export
grapheneBoxContainsBox <- function(a, b) {
  .Call("R_graphene_box_contains_box", a, b)$result
}


#' @rdname graphene
#' @title grapheneBoxContainsPoint
#'
#' @param box Box
#' @param point Point3D
#' @return gboolean
#' @export
grapheneBoxContainsPoint <- function(box, point) {
  .Call("R_graphene_box_contains_point", box, point)$result
}


#' @rdname graphene
#' @title grapheneBoxEqual
#'
#' @param a Box
#' @param b Box
#' @return gboolean
#' @export
grapheneBoxEqual <- function(a, b) {
  .Call("R_graphene_box_equal", a, b)$result
}


#' @rdname graphene
#' @title grapheneBoxExpand
#'
#' @param box Box
#' @param point Point3D
#' @return Return value from C function
#' @export
grapheneBoxExpand <- function(box, point) {
  .Call("R_graphene_box_expand", box, point)$res
}


#' @rdname graphene
#' @title grapheneBoxExpandScalar
#'
#' @param box Box
#' @param scalar gfloat
#' @return Return value from C function
#' @export
grapheneBoxExpandScalar <- function(box, scalar) {
  .Call("R_graphene_box_expand_scalar", box, scalar)$res
}


#' @rdname graphene
#' @title grapheneBoxExpandVec3
#'
#' @param box Box
#' @param vec Vec3
#' @return Return value from C function
#' @export
grapheneBoxExpandVec3 <- function(box, vec) {
  .Call("R_graphene_box_expand_vec3", box, vec)$res
}


#' @rdname graphene
#' @title grapheneBoxFree
#'
#' @param box Box
#' @return Return value from C function
#' @export
grapheneBoxFree <- function(box) {
  invisible(.Call("R_graphene_box_free", box))
}


#' @rdname graphene
#' @title grapheneBoxGetBoundingSphere
#'
#' @param box Box
#' @return Return value from C function
#' @export
grapheneBoxGetBoundingSphere <- function(box) {
  .Call("R_graphene_box_get_bounding_sphere", box)$sphere
}


#' @rdname graphene
#' @title grapheneBoxGetCenter
#'
#' @param box Box
#' @return Return value from C function
#' @export
grapheneBoxGetCenter <- function(box) {
  .Call("R_graphene_box_get_center", box)$center
}


#' @rdname graphene
#' @title grapheneBoxGetDepth
#'
#' @param box Box
#' @return gfloat
#' @export
grapheneBoxGetDepth <- function(box) {
  .Call("R_graphene_box_get_depth", box)$result
}


#' @rdname graphene
#' @title grapheneBoxGetHeight
#'
#' @param box Box
#' @return gfloat
#' @export
grapheneBoxGetHeight <- function(box) {
  .Call("R_graphene_box_get_height", box)$result
}


#' @rdname graphene
#' @title grapheneBoxGetMax
#'
#' @param box Box
#' @return Return value from C function
#' @export
grapheneBoxGetMax <- function(box) {
  .Call("R_graphene_box_get_max", box)$max
}


#' @rdname graphene
#' @title grapheneBoxGetMin
#'
#' @param box Box
#' @return Return value from C function
#' @export
grapheneBoxGetMin <- function(box) {
  .Call("R_graphene_box_get_min", box)$min
}


#' @rdname graphene
#' @title grapheneBoxGetSize
#'
#' @param box Box
#' @return Return value from C function
#' @export
grapheneBoxGetSize <- function(box) {
  .Call("R_graphene_box_get_size", box)$size
}


#' @rdname graphene
#' @title grapheneBoxGetVertices
#'
#' @param box Box
#' @return Return value from C function
#' @export
grapheneBoxGetVertices <- function(box) {
  .Call("R_graphene_box_get_vertices", box)$vertices
}


#' @rdname graphene
#' @title grapheneBoxGetWidth
#'
#' @param box Box
#' @return gfloat
#' @export
grapheneBoxGetWidth <- function(box) {
  .Call("R_graphene_box_get_width", box)$result
}


#' @rdname graphene
#' @title grapheneBoxInit
#'
#' @param box Box
#' @param min Point3D
#' @param max Point3D
#' @return Box
#' @export
grapheneBoxInit <- function(box, min, max) {
  .Call("R_graphene_box_init", box, min, max)$result
}


#' @rdname graphene
#' @title grapheneBoxInitFromBox
#'
#' @param box Box
#' @param src Box
#' @return Box
#' @export
grapheneBoxInitFromBox <- function(box, src) {
  .Call("R_graphene_box_init_from_box", box, src)$result
}


#' @rdname graphene
#' @title grapheneBoxInitFromPoints
#'
#' @param box Box
#' @param n_points guint
#' @param points Point3D
#' @return Box
#' @export
grapheneBoxInitFromPoints <- function(box, n_points, points) {
  .Call("R_graphene_box_init_from_points", box, as.integer(n_points), points)$result
}


#' @rdname graphene
#' @title grapheneBoxInitFromVec3
#'
#' @param box Box
#' @param min Vec3
#' @param max Vec3
#' @return Box
#' @export
grapheneBoxInitFromVec3 <- function(box, min, max) {
  .Call("R_graphene_box_init_from_vec3", box, min, max)$result
}


#' @rdname graphene
#' @title grapheneBoxInitFromVectors
#'
#' @param box Box
#' @param n_vectors guint
#' @param vectors Vec3
#' @return Box
#' @export
grapheneBoxInitFromVectors <- function(box, n_vectors, vectors) {
  .Call("R_graphene_box_init_from_vectors", box, as.integer(n_vectors), vectors)$result
}


#' @rdname graphene
#' @title grapheneBoxIntersection
#'
#' @param a Box
#' @param b Box
#' @return gboolean
#' @export
grapheneBoxIntersection <- function(a, b) {
  .Call("R_graphene_box_intersection", a, b)
}


#' @rdname graphene
#' @title grapheneBoxUnion
#'
#' @param a Box
#' @param b Box
#' @return Return value from C function
#' @export
grapheneBoxUnion <- function(a, b) {
  .Call("R_graphene_box_union", a, b)$res
}


#' @rdname graphene
#' @title grapheneBoxEmpty
#'
#' @return Box
#' @export
grapheneBoxEmpty <- function() {
  .Call("R_graphene_box_empty")$result
}


#' @rdname graphene
#' @title grapheneBoxInfinite
#'
#' @return Box
#' @export
grapheneBoxInfinite <- function() {
  .Call("R_graphene_box_infinite")$result
}


#' @rdname graphene
#' @title grapheneBoxMinusOne
#'
#' @return Box
#' @export
grapheneBoxMinusOne <- function() {
  .Call("R_graphene_box_minus_one")$result
}


#' @rdname graphene
#' @title grapheneBoxOne
#'
#' @return Box
#' @export
grapheneBoxOne <- function() {
  .Call("R_graphene_box_one")$result
}


#' @rdname graphene
#' @title grapheneBoxOneMinusOne
#'
#' @return Box
#' @export
grapheneBoxOneMinusOne <- function() {
  .Call("R_graphene_box_one_minus_one")$result
}


#' @rdname graphene
#' @title grapheneBoxZero
#'
#' @return Box
#' @export
grapheneBoxZero <- function() {
  .Call("R_graphene_box_zero")$result
}


#' @rdname graphene
#' @title grapheneEulerAlloc
#'
#' @return Euler
#' @export
grapheneEulerAlloc <- function() {
  .Call("R_graphene_euler_alloc")$result
}


#' @rdname graphene
#' @title grapheneEulerEqual
#'
#' @param a Euler
#' @param b Euler
#' @return gboolean
#' @export
grapheneEulerEqual <- function(a, b) {
  .Call("R_graphene_euler_equal", a, b)$result
}


#' @rdname graphene
#' @title grapheneEulerFree
#'
#' @param e Euler
#' @return Return value from C function
#' @export
grapheneEulerFree <- function(e) {
  invisible(.Call("R_graphene_euler_free", e))
}


#' @rdname graphene
#' @title grapheneEulerGetAlpha
#'
#' @param e Euler
#' @return gfloat
#' @export
grapheneEulerGetAlpha <- function(e) {
  .Call("R_graphene_euler_get_alpha", e)$result
}


#' @rdname graphene
#' @title grapheneEulerGetBeta
#'
#' @param e Euler
#' @return gfloat
#' @export
grapheneEulerGetBeta <- function(e) {
  .Call("R_graphene_euler_get_beta", e)$result
}


#' @rdname graphene
#' @title grapheneEulerGetGamma
#'
#' @param e Euler
#' @return gfloat
#' @export
grapheneEulerGetGamma <- function(e) {
  .Call("R_graphene_euler_get_gamma", e)$result
}


#' @rdname graphene
#' @title grapheneEulerGetOrder
#'
#' @param e Euler
#' @return EulerOrder
#' @export
grapheneEulerGetOrder <- function(e) {
  .Call("R_graphene_euler_get_order", e)$result
}


#' @rdname graphene
#' @title grapheneEulerGetX
#'
#' @param e Euler
#' @return gfloat
#' @export
grapheneEulerGetX <- function(e) {
  .Call("R_graphene_euler_get_x", e)$result
}


#' @rdname graphene
#' @title grapheneEulerGetY
#'
#' @param e Euler
#' @return gfloat
#' @export
grapheneEulerGetY <- function(e) {
  .Call("R_graphene_euler_get_y", e)$result
}


#' @rdname graphene
#' @title grapheneEulerGetZ
#'
#' @param e Euler
#' @return gfloat
#' @export
grapheneEulerGetZ <- function(e) {
  .Call("R_graphene_euler_get_z", e)$result
}


#' @rdname graphene
#' @title grapheneEulerInit
#'
#' @param e Euler
#' @param x gfloat
#' @param y gfloat
#' @param z gfloat
#' @return Euler
#' @export
grapheneEulerInit <- function(e, x, y, z) {
  .Call("R_graphene_euler_init", e, x, y, z)$result
}


#' @rdname graphene
#' @title grapheneEulerInitFromEuler
#'
#' @param e Euler
#' @param src Euler
#' @return Euler
#' @export
grapheneEulerInitFromEuler <- function(e, src) {
  .Call("R_graphene_euler_init_from_euler", e, src)$result
}


#' @rdname graphene
#' @title grapheneEulerInitFromMatrix
#'
#' @param e Euler
#' @param m Matrix
#' @param order EulerOrder
#' @return Euler
#' @export
grapheneEulerInitFromMatrix <- function(e, m, order) {
  .Call("R_graphene_euler_init_from_matrix", e, m, order)$result
}


#' @rdname graphene
#' @title grapheneEulerInitFromQuaternion
#'
#' @param e Euler
#' @param q Quaternion
#' @param order EulerOrder
#' @return Euler
#' @export
grapheneEulerInitFromQuaternion <- function(e, q, order) {
  .Call("R_graphene_euler_init_from_quaternion", e, q, order)$result
}


#' @rdname graphene
#' @title grapheneEulerInitFromRadians
#'
#' @param e Euler
#' @param x gfloat
#' @param y gfloat
#' @param z gfloat
#' @param order EulerOrder
#' @return Euler
#' @export
grapheneEulerInitFromRadians <- function(e, x, y, z, order) {
  .Call("R_graphene_euler_init_from_radians", e, x, y, z, order)$result
}


#' @rdname graphene
#' @title grapheneEulerInitFromVec3
#'
#' @param e Euler
#' @param v Vec3
#' @param order EulerOrder
#' @return Euler
#' @export
grapheneEulerInitFromVec3 <- function(e, v, order) {
  .Call("R_graphene_euler_init_from_vec3", e, v, order)$result
}


#' @rdname graphene
#' @title grapheneEulerInitWithOrder
#'
#' @param e Euler
#' @param x gfloat
#' @param y gfloat
#' @param z gfloat
#' @param order EulerOrder
#' @return Euler
#' @export
grapheneEulerInitWithOrder <- function(e, x, y, z, order) {
  .Call("R_graphene_euler_init_with_order", e, x, y, z, order)$result
}


#' @rdname graphene
#' @title grapheneEulerReorder
#'
#' @param e Euler
#' @param order EulerOrder
#' @return Return value from C function
#' @export
grapheneEulerReorder <- function(e, order) {
  .Call("R_graphene_euler_reorder", e, order)$res
}


#' @rdname graphene
#' @title grapheneEulerToMatrix
#'
#' @param e Euler
#' @return Return value from C function
#' @export
grapheneEulerToMatrix <- function(e) {
  .Call("R_graphene_euler_to_matrix", e)$res
}


#' @rdname graphene
#' @title grapheneEulerToQuaternion
#'
#' @param e Euler
#' @return Return value from C function
#' @export
grapheneEulerToQuaternion <- function(e) {
  .Call("R_graphene_euler_to_quaternion", e)$res
}


#' @rdname graphene
#' @title grapheneEulerToVec3
#'
#' @param e Euler
#' @return Return value from C function
#' @export
grapheneEulerToVec3 <- function(e) {
  .Call("R_graphene_euler_to_vec3", e)$res
}


#' @rdname graphene
#' @title grapheneFrustumAlloc
#'
#' @return Frustum
#' @export
grapheneFrustumAlloc <- function() {
  .Call("R_graphene_frustum_alloc")$result
}


#' @rdname graphene
#' @title grapheneFrustumContainsPoint
#'
#' @param f Frustum
#' @param point Point3D
#' @return gboolean
#' @export
grapheneFrustumContainsPoint <- function(f, point) {
  .Call("R_graphene_frustum_contains_point", f, point)$result
}


#' @rdname graphene
#' @title grapheneFrustumEqual
#'
#' @param a Frustum
#' @param b Frustum
#' @return gboolean
#' @export
grapheneFrustumEqual <- function(a, b) {
  .Call("R_graphene_frustum_equal", a, b)$result
}


#' @rdname graphene
#' @title grapheneFrustumFree
#'
#' @param f Frustum
#' @return Return value from C function
#' @export
grapheneFrustumFree <- function(f) {
  invisible(.Call("R_graphene_frustum_free", f))
}


#' @rdname graphene
#' @title grapheneFrustumGetPlanes
#'
#' @param f Frustum
#' @return Return value from C function
#' @export
grapheneFrustumGetPlanes <- function(f) {
  .Call("R_graphene_frustum_get_planes", f)$planes
}


#' @rdname graphene
#' @title grapheneFrustumInit
#'
#' @param f Frustum
#' @param p0 Plane
#' @param p1 Plane
#' @param p2 Plane
#' @param p3 Plane
#' @param p4 Plane
#' @param p5 Plane
#' @return Frustum
#' @export
grapheneFrustumInit <- function(f, p0, p1, p2, p3, p4, p5) {
  .Call("R_graphene_frustum_init", f, p0, p1, p2, p3, p4, p5)$result
}


#' @rdname graphene
#' @title grapheneFrustumInitFromFrustum
#'
#' @param f Frustum
#' @param src Frustum
#' @return Frustum
#' @export
grapheneFrustumInitFromFrustum <- function(f, src) {
  .Call("R_graphene_frustum_init_from_frustum", f, src)$result
}


#' @rdname graphene
#' @title grapheneFrustumInitFromMatrix
#'
#' @param f Frustum
#' @param matrix Matrix
#' @return Frustum
#' @export
grapheneFrustumInitFromMatrix <- function(f, matrix) {
  .Call("R_graphene_frustum_init_from_matrix", f, matrix)$result
}


#' @rdname graphene
#' @title grapheneFrustumIntersectsBox
#'
#' @param f Frustum
#' @param box Box
#' @return gboolean
#' @export
grapheneFrustumIntersectsBox <- function(f, box) {
  .Call("R_graphene_frustum_intersects_box", f, box)$result
}


#' @rdname graphene
#' @title grapheneFrustumIntersectsSphere
#'
#' @param f Frustum
#' @param sphere Sphere
#' @return gboolean
#' @export
grapheneFrustumIntersectsSphere <- function(f, sphere) {
  .Call("R_graphene_frustum_intersects_sphere", f, sphere)$result
}


#' @rdname graphene
#' @title grapheneMatrixAlloc
#'
#' @return Matrix
#' @export
grapheneMatrixAlloc <- function() {
  .Call("R_graphene_matrix_alloc")$result
}


#' @rdname graphene
#' @title grapheneMatrixDecompose
#'
#' @param m Matrix
#' @return gboolean
#' @export
grapheneMatrixDecompose <- function(m) {
  .Call("R_graphene_matrix_decompose", m)
}


#' @rdname graphene
#' @title grapheneMatrixDeterminant
#'
#' @param m Matrix
#' @return gfloat
#' @export
grapheneMatrixDeterminant <- function(m) {
  .Call("R_graphene_matrix_determinant", m)$result
}


#' @rdname graphene
#' @title grapheneMatrixEqual
#'
#' @param a Matrix
#' @param b Matrix
#' @return gboolean
#' @export
grapheneMatrixEqual <- function(a, b) {
  .Call("R_graphene_matrix_equal", a, b)$result
}


#' @rdname graphene
#' @title grapheneMatrixEqualFast
#'
#' @param a Matrix
#' @param b Matrix
#' @return gboolean
#' @export
grapheneMatrixEqualFast <- function(a, b) {
  .Call("R_graphene_matrix_equal_fast", a, b)$result
}


#' @rdname graphene
#' @title grapheneMatrixFree
#'
#' @param m Matrix
#' @return Return value from C function
#' @export
grapheneMatrixFree <- function(m) {
  invisible(.Call("R_graphene_matrix_free", m))
}


#' @rdname graphene
#' @title grapheneMatrixGetRow
#'
#' @param m Matrix
#' @param index_ guint
#' @return Return value from C function
#' @export
grapheneMatrixGetRow <- function(m, index_) {
  .Call("R_graphene_matrix_get_row", m, as.integer(index_))$res
}


#' @rdname graphene
#' @title grapheneMatrixGetValue
#'
#' @param m Matrix
#' @param row guint
#' @param col guint
#' @return gfloat
#' @export
grapheneMatrixGetValue <- function(m, row, col) {
  .Call("R_graphene_matrix_get_value", m, as.integer(row), as.integer(col))$result
}


#' @rdname graphene
#' @title grapheneMatrixGetXScale
#'
#' @param m Matrix
#' @return gfloat
#' @export
grapheneMatrixGetXScale <- function(m) {
  .Call("R_graphene_matrix_get_x_scale", m)$result
}


#' @rdname graphene
#' @title grapheneMatrixGetXTranslation
#'
#' @param m Matrix
#' @return gfloat
#' @export
grapheneMatrixGetXTranslation <- function(m) {
  .Call("R_graphene_matrix_get_x_translation", m)$result
}


#' @rdname graphene
#' @title grapheneMatrixGetYScale
#'
#' @param m Matrix
#' @return gfloat
#' @export
grapheneMatrixGetYScale <- function(m) {
  .Call("R_graphene_matrix_get_y_scale", m)$result
}


#' @rdname graphene
#' @title grapheneMatrixGetYTranslation
#'
#' @param m Matrix
#' @return gfloat
#' @export
grapheneMatrixGetYTranslation <- function(m) {
  .Call("R_graphene_matrix_get_y_translation", m)$result
}


#' @rdname graphene
#' @title grapheneMatrixGetZScale
#'
#' @param m Matrix
#' @return gfloat
#' @export
grapheneMatrixGetZScale <- function(m) {
  .Call("R_graphene_matrix_get_z_scale", m)$result
}


#' @rdname graphene
#' @title grapheneMatrixGetZTranslation
#'
#' @param m Matrix
#' @return gfloat
#' @export
grapheneMatrixGetZTranslation <- function(m) {
  .Call("R_graphene_matrix_get_z_translation", m)$result
}


#' @rdname graphene
#' @title grapheneMatrixInitFrom2d
#'
#' @param m Matrix
#' @param xx gdouble
#' @param yx gdouble
#' @param xy gdouble
#' @param yy gdouble
#' @param x_0 gdouble
#' @param y_0 gdouble
#' @return Matrix
#' @export
grapheneMatrixInitFrom2d <- function(m, xx, yx, xy, yy, x_0, y_0) {
  .Call("R_graphene_matrix_init_from_2d", m, xx, yx, xy, yy, x_0, y_0)$result
}


#' @rdname graphene
#' @title grapheneMatrixInitFromFloat
#'
#' @param m Matrix
#' @param v gfloat
#' @return Matrix
#' @export
grapheneMatrixInitFromFloat <- function(m, v) {
  .Call("R_graphene_matrix_init_from_float", m, v)$result
}


#' @rdname graphene
#' @title grapheneMatrixInitFromMatrix
#'
#' @param m Matrix
#' @param src Matrix
#' @return Matrix
#' @export
grapheneMatrixInitFromMatrix <- function(m, src) {
  .Call("R_graphene_matrix_init_from_matrix", m, src)$result
}


#' @rdname graphene
#' @title grapheneMatrixInitFromVec4
#'
#' @param m Matrix
#' @param v0 Vec4
#' @param v1 Vec4
#' @param v2 Vec4
#' @param v3 Vec4
#' @return Matrix
#' @export
grapheneMatrixInitFromVec4 <- function(m, v0, v1, v2, v3) {
  .Call("R_graphene_matrix_init_from_vec4", m, v0, v1, v2, v3)$result
}


#' @rdname graphene
#' @title grapheneMatrixInitFrustum
#'
#' @param m Matrix
#' @param left gfloat
#' @param right gfloat
#' @param bottom gfloat
#' @param top gfloat
#' @param z_near gfloat
#' @param z_far gfloat
#' @return Matrix
#' @export
grapheneMatrixInitFrustum <- function(m, left, right, bottom, top, z_near, z_far) {
  .Call("R_graphene_matrix_init_frustum", m, left, right, bottom, top, z_near, z_far)$result
}


#' @rdname graphene
#' @title grapheneMatrixInitIdentity
#'
#' @param m Matrix
#' @return Matrix
#' @export
grapheneMatrixInitIdentity <- function(m) {
  .Call("R_graphene_matrix_init_identity", m)$result
}


#' @rdname graphene
#' @title grapheneMatrixInitLookAt
#'
#' @param m Matrix
#' @param eye Vec3
#' @param center Vec3
#' @param up Vec3
#' @return Matrix
#' @export
grapheneMatrixInitLookAt <- function(m, eye, center, up) {
  .Call("R_graphene_matrix_init_look_at", m, eye, center, up)$result
}


#' @rdname graphene
#' @title grapheneMatrixInitOrtho
#'
#' @param m Matrix
#' @param left gfloat
#' @param right gfloat
#' @param top gfloat
#' @param bottom gfloat
#' @param z_near gfloat
#' @param z_far gfloat
#' @return Matrix
#' @export
grapheneMatrixInitOrtho <- function(m, left, right, top, bottom, z_near, z_far) {
  .Call("R_graphene_matrix_init_ortho", m, left, right, top, bottom, z_near, z_far)$result
}


#' @rdname graphene
#' @title grapheneMatrixInitPerspective
#'
#' @param m Matrix
#' @param fovy gfloat
#' @param aspect gfloat
#' @param z_near gfloat
#' @param z_far gfloat
#' @return Matrix
#' @export
grapheneMatrixInitPerspective <- function(m, fovy, aspect, z_near, z_far) {
  .Call("R_graphene_matrix_init_perspective", m, fovy, aspect, z_near, z_far)$result
}


#' @rdname graphene
#' @title grapheneMatrixInitRotate
#'
#' @param m Matrix
#' @param angle gfloat
#' @param axis Vec3
#' @return Matrix
#' @export
grapheneMatrixInitRotate <- function(m, angle, axis) {
  .Call("R_graphene_matrix_init_rotate", m, angle, axis)$result
}


#' @rdname graphene
#' @title grapheneMatrixInitScale
#'
#' @param m Matrix
#' @param x gfloat
#' @param y gfloat
#' @param z gfloat
#' @return Matrix
#' @export
grapheneMatrixInitScale <- function(m, x, y, z) {
  .Call("R_graphene_matrix_init_scale", m, x, y, z)$result
}


#' @rdname graphene
#' @title grapheneMatrixInitSkew
#'
#' @param m Matrix
#' @param x_skew gfloat
#' @param y_skew gfloat
#' @return Matrix
#' @export
grapheneMatrixInitSkew <- function(m, x_skew, y_skew) {
  .Call("R_graphene_matrix_init_skew", m, x_skew, y_skew)$result
}


#' @rdname graphene
#' @title grapheneMatrixInitTranslate
#'
#' @param m Matrix
#' @param p Point3D
#' @return Matrix
#' @export
grapheneMatrixInitTranslate <- function(m, p) {
  .Call("R_graphene_matrix_init_translate", m, p)$result
}


#' @rdname graphene
#' @title grapheneMatrixInterpolate
#'
#' @param a Matrix
#' @param b Matrix
#' @param factor gdouble
#' @return Return value from C function
#' @export
grapheneMatrixInterpolate <- function(a, b, factor) {
  .Call("R_graphene_matrix_interpolate", a, b, factor)$res
}


#' @rdname graphene
#' @title grapheneMatrixInverse
#'
#' @param m Matrix
#' @return gboolean
#' @export
grapheneMatrixInverse <- function(m) {
  .Call("R_graphene_matrix_inverse", m)
}


#' @rdname graphene
#' @title grapheneMatrixIs2d
#'
#' @param m Matrix
#' @return gboolean
#' @export
grapheneMatrixIs2d <- function(m) {
  .Call("R_graphene_matrix_is_2d", m)$result
}


#' @rdname graphene
#' @title grapheneMatrixIsBackfaceVisible
#'
#' @param m Matrix
#' @return gboolean
#' @export
grapheneMatrixIsBackfaceVisible <- function(m) {
  .Call("R_graphene_matrix_is_backface_visible", m)$result
}


#' @rdname graphene
#' @title grapheneMatrixIsIdentity
#'
#' @param m Matrix
#' @return gboolean
#' @export
grapheneMatrixIsIdentity <- function(m) {
  .Call("R_graphene_matrix_is_identity", m)$result
}


#' @rdname graphene
#' @title grapheneMatrixIsSingular
#'
#' @param m Matrix
#' @return gboolean
#' @export
grapheneMatrixIsSingular <- function(m) {
  .Call("R_graphene_matrix_is_singular", m)$result
}


#' @rdname graphene
#' @title grapheneMatrixMultiply
#'
#' @param a Matrix
#' @param b Matrix
#' @return Return value from C function
#' @export
grapheneMatrixMultiply <- function(a, b) {
  .Call("R_graphene_matrix_multiply", a, b)$res
}


#' @rdname graphene
#' @title grapheneMatrixNear
#'
#' @param a Matrix
#' @param b Matrix
#' @param epsilon gfloat
#' @return gboolean
#' @export
grapheneMatrixNear <- function(a, b, epsilon) {
  .Call("R_graphene_matrix_near", a, b, epsilon)$result
}


#' @rdname graphene
#' @title grapheneMatrixNormalize
#'
#' @param m Matrix
#' @return Return value from C function
#' @export
grapheneMatrixNormalize <- function(m) {
  .Call("R_graphene_matrix_normalize", m)$res
}


#' @rdname graphene
#' @title grapheneMatrixPerspective
#'
#' @param m Matrix
#' @param depth gfloat
#' @return Return value from C function
#' @export
grapheneMatrixPerspective <- function(m, depth) {
  .Call("R_graphene_matrix_perspective", m, depth)$res
}


#' @rdname graphene
#' @title grapheneMatrixPrint
#'
#' @param m Matrix
#' @return Return value from C function
#' @export
grapheneMatrixPrint <- function(m) {
  invisible(.Call("R_graphene_matrix_print", m))
}


#' @rdname graphene
#' @title grapheneMatrixProjectPoint
#'
#' @param m Matrix
#' @param p Point
#' @return Return value from C function
#' @export
grapheneMatrixProjectPoint <- function(m, p) {
  .Call("R_graphene_matrix_project_point", m, p)$res
}


#' @rdname graphene
#' @title grapheneMatrixProjectRect
#'
#' @param m Matrix
#' @param r Rect
#' @return Return value from C function
#' @export
grapheneMatrixProjectRect <- function(m, r) {
  .Call("R_graphene_matrix_project_rect", m, r)$res
}


#' @rdname graphene
#' @title grapheneMatrixProjectRectBounds
#'
#' @param m Matrix
#' @param r Rect
#' @return Return value from C function
#' @export
grapheneMatrixProjectRectBounds <- function(m, r) {
  .Call("R_graphene_matrix_project_rect_bounds", m, r)$res
}


#' @rdname graphene
#' @title grapheneMatrixRotate
#'
#' @param m Matrix
#' @param angle gfloat
#' @param axis Vec3
#' @return Return value from C function
#' @export
grapheneMatrixRotate <- function(m, angle, axis) {
  invisible(.Call("R_graphene_matrix_rotate", m, angle, axis))
}


#' @rdname graphene
#' @title grapheneMatrixRotateEuler
#'
#' @param m Matrix
#' @param e Euler
#' @return Return value from C function
#' @export
grapheneMatrixRotateEuler <- function(m, e) {
  invisible(.Call("R_graphene_matrix_rotate_euler", m, e))
}


#' @rdname graphene
#' @title grapheneMatrixRotateQuaternion
#'
#' @param m Matrix
#' @param q Quaternion
#' @return Return value from C function
#' @export
grapheneMatrixRotateQuaternion <- function(m, q) {
  invisible(.Call("R_graphene_matrix_rotate_quaternion", m, q))
}


#' @rdname graphene
#' @title grapheneMatrixRotateX
#'
#' @param m Matrix
#' @param angle gfloat
#' @return Return value from C function
#' @export
grapheneMatrixRotateX <- function(m, angle) {
  invisible(.Call("R_graphene_matrix_rotate_x", m, angle))
}


#' @rdname graphene
#' @title grapheneMatrixRotateY
#'
#' @param m Matrix
#' @param angle gfloat
#' @return Return value from C function
#' @export
grapheneMatrixRotateY <- function(m, angle) {
  invisible(.Call("R_graphene_matrix_rotate_y", m, angle))
}


#' @rdname graphene
#' @title grapheneMatrixRotateZ
#'
#' @param m Matrix
#' @param angle gfloat
#' @return Return value from C function
#' @export
grapheneMatrixRotateZ <- function(m, angle) {
  invisible(.Call("R_graphene_matrix_rotate_z", m, angle))
}


#' @rdname graphene
#' @title grapheneMatrixScale
#'
#' @param m Matrix
#' @param factor_x gfloat
#' @param factor_y gfloat
#' @param factor_z gfloat
#' @return Return value from C function
#' @export
grapheneMatrixScale <- function(m, factor_x, factor_y, factor_z) {
  invisible(.Call("R_graphene_matrix_scale", m, factor_x, factor_y, factor_z))
}


#' @rdname graphene
#' @title grapheneMatrixSkewXy
#'
#' @param m Matrix
#' @param factor gfloat
#' @return Return value from C function
#' @export
grapheneMatrixSkewXy <- function(m, factor) {
  invisible(.Call("R_graphene_matrix_skew_xy", m, factor))
}


#' @rdname graphene
#' @title grapheneMatrixSkewXz
#'
#' @param m Matrix
#' @param factor gfloat
#' @return Return value from C function
#' @export
grapheneMatrixSkewXz <- function(m, factor) {
  invisible(.Call("R_graphene_matrix_skew_xz", m, factor))
}


#' @rdname graphene
#' @title grapheneMatrixSkewYz
#'
#' @param m Matrix
#' @param factor gfloat
#' @return Return value from C function
#' @export
grapheneMatrixSkewYz <- function(m, factor) {
  invisible(.Call("R_graphene_matrix_skew_yz", m, factor))
}


#' @rdname graphene
#' @title grapheneMatrixTo2d
#'
#' @param m Matrix
#' @return gboolean
#' @export
grapheneMatrixTo2d <- function(m) {
  .Call("R_graphene_matrix_to_2d", m)
}


#' @rdname graphene
#' @title grapheneMatrixToFloat
#'
#' @param m Matrix
#' @return Return value from C function
#' @export
grapheneMatrixToFloat <- function(m) {
  .Call("R_graphene_matrix_to_float", m)$v
}


#' @rdname graphene
#' @title grapheneMatrixTransformBounds
#'
#' @param m Matrix
#' @param r Rect
#' @return Return value from C function
#' @export
grapheneMatrixTransformBounds <- function(m, r) {
  .Call("R_graphene_matrix_transform_bounds", m, r)$res
}


#' @rdname graphene
#' @title grapheneMatrixTransformBox
#'
#' @param m Matrix
#' @param b Box
#' @return Return value from C function
#' @export
grapheneMatrixTransformBox <- function(m, b) {
  .Call("R_graphene_matrix_transform_box", m, b)$res
}


#' @rdname graphene
#' @title grapheneMatrixTransformPoint
#'
#' @param m Matrix
#' @param p Point
#' @return Return value from C function
#' @export
grapheneMatrixTransformPoint <- function(m, p) {
  .Call("R_graphene_matrix_transform_point", m, p)$res
}


#' @rdname graphene
#' @title grapheneMatrixTransformPoint3d
#'
#' @param m Matrix
#' @param p Point3D
#' @return Return value from C function
#' @export
grapheneMatrixTransformPoint3d <- function(m, p) {
  .Call("R_graphene_matrix_transform_point3d", m, p)$res
}


#' @rdname graphene
#' @title grapheneMatrixTransformRay
#'
#' @param m Matrix
#' @param r Ray
#' @return Return value from C function
#' @export
grapheneMatrixTransformRay <- function(m, r) {
  .Call("R_graphene_matrix_transform_ray", m, r)$res
}


#' @rdname graphene
#' @title grapheneMatrixTransformRect
#'
#' @param m Matrix
#' @param r Rect
#' @return Return value from C function
#' @export
grapheneMatrixTransformRect <- function(m, r) {
  .Call("R_graphene_matrix_transform_rect", m, r)$res
}


#' @rdname graphene
#' @title grapheneMatrixTransformSphere
#'
#' @param m Matrix
#' @param s Sphere
#' @return Return value from C function
#' @export
grapheneMatrixTransformSphere <- function(m, s) {
  .Call("R_graphene_matrix_transform_sphere", m, s)$res
}


#' @rdname graphene
#' @title grapheneMatrixTransformVec3
#'
#' @param m Matrix
#' @param v Vec3
#' @return Return value from C function
#' @export
grapheneMatrixTransformVec3 <- function(m, v) {
  .Call("R_graphene_matrix_transform_vec3", m, v)$res
}


#' @rdname graphene
#' @title grapheneMatrixTransformVec4
#'
#' @param m Matrix
#' @param v Vec4
#' @return Return value from C function
#' @export
grapheneMatrixTransformVec4 <- function(m, v) {
  .Call("R_graphene_matrix_transform_vec4", m, v)$res
}


#' @rdname graphene
#' @title grapheneMatrixTranslate
#'
#' @param m Matrix
#' @param pos Point3D
#' @return Return value from C function
#' @export
grapheneMatrixTranslate <- function(m, pos) {
  invisible(.Call("R_graphene_matrix_translate", m, pos))
}


#' @rdname graphene
#' @title grapheneMatrixTranspose
#'
#' @param m Matrix
#' @return Return value from C function
#' @export
grapheneMatrixTranspose <- function(m) {
  .Call("R_graphene_matrix_transpose", m)$res
}


#' @rdname graphene
#' @title grapheneMatrixUnprojectPoint3d
#'
#' @param projection Matrix
#' @param modelview Matrix
#' @param point Point3D
#' @return Return value from C function
#' @export
grapheneMatrixUnprojectPoint3d <- function(projection, modelview, point) {
  .Call("R_graphene_matrix_unproject_point3d", projection, modelview, point)$res
}


#' @rdname graphene
#' @title grapheneMatrixUntransformBounds
#'
#' @param m Matrix
#' @param r Rect
#' @param bounds Rect
#' @return Return value from C function
#' @export
grapheneMatrixUntransformBounds <- function(m, r, bounds) {
  .Call("R_graphene_matrix_untransform_bounds", m, r, bounds)$res
}


#' @rdname graphene
#' @title grapheneMatrixUntransformPoint
#'
#' @param m Matrix
#' @param p Point
#' @param bounds Rect
#' @return gboolean
#' @export
grapheneMatrixUntransformPoint <- function(m, p, bounds) {
  .Call("R_graphene_matrix_untransform_point", m, p, bounds)
}


#' @rdname graphene
#' @title graphenePlaneAlloc
#'
#' @return Plane
#' @export
graphenePlaneAlloc <- function() {
  .Call("R_graphene_plane_alloc")$result
}


#' @rdname graphene
#' @title graphenePlaneDistance
#'
#' @param p Plane
#' @param point Point3D
#' @return gfloat
#' @export
graphenePlaneDistance <- function(p, point) {
  .Call("R_graphene_plane_distance", p, point)$result
}


#' @rdname graphene
#' @title graphenePlaneEqual
#'
#' @param a Plane
#' @param b Plane
#' @return gboolean
#' @export
graphenePlaneEqual <- function(a, b) {
  .Call("R_graphene_plane_equal", a, b)$result
}


#' @rdname graphene
#' @title graphenePlaneFree
#'
#' @param p Plane
#' @return Return value from C function
#' @export
graphenePlaneFree <- function(p) {
  invisible(.Call("R_graphene_plane_free", p))
}


#' @rdname graphene
#' @title graphenePlaneGetConstant
#'
#' @param p Plane
#' @return gfloat
#' @export
graphenePlaneGetConstant <- function(p) {
  .Call("R_graphene_plane_get_constant", p)$result
}


#' @rdname graphene
#' @title graphenePlaneGetNormal
#'
#' @param p Plane
#' @return Return value from C function
#' @export
graphenePlaneGetNormal <- function(p) {
  .Call("R_graphene_plane_get_normal", p)$normal
}


#' @rdname graphene
#' @title graphenePlaneInit
#'
#' @param p Plane
#' @param normal Vec3
#' @param constant gfloat
#' @return Plane
#' @export
graphenePlaneInit <- function(p, normal, constant) {
  .Call("R_graphene_plane_init", p, normal, constant)$result
}


#' @rdname graphene
#' @title graphenePlaneInitFromPlane
#'
#' @param p Plane
#' @param src Plane
#' @return Plane
#' @export
graphenePlaneInitFromPlane <- function(p, src) {
  .Call("R_graphene_plane_init_from_plane", p, src)$result
}


#' @rdname graphene
#' @title graphenePlaneInitFromPoint
#'
#' @param p Plane
#' @param normal Vec3
#' @param point Point3D
#' @return Plane
#' @export
graphenePlaneInitFromPoint <- function(p, normal, point) {
  .Call("R_graphene_plane_init_from_point", p, normal, point)$result
}


#' @rdname graphene
#' @title graphenePlaneInitFromPoints
#'
#' @param p Plane
#' @param a Point3D
#' @param b Point3D
#' @param c Point3D
#' @return Plane
#' @export
graphenePlaneInitFromPoints <- function(p, a, b, c) {
  .Call("R_graphene_plane_init_from_points", p, a, b, c)$result
}


#' @rdname graphene
#' @title graphenePlaneInitFromVec4
#'
#' @param p Plane
#' @param src Vec4
#' @return Plane
#' @export
graphenePlaneInitFromVec4 <- function(p, src) {
  .Call("R_graphene_plane_init_from_vec4", p, src)$result
}


#' @rdname graphene
#' @title graphenePlaneNegate
#'
#' @param p Plane
#' @return Return value from C function
#' @export
graphenePlaneNegate <- function(p) {
  .Call("R_graphene_plane_negate", p)$res
}


#' @rdname graphene
#' @title graphenePlaneNormalize
#'
#' @param p Plane
#' @return Return value from C function
#' @export
graphenePlaneNormalize <- function(p) {
  .Call("R_graphene_plane_normalize", p)$res
}


#' @rdname graphene
#' @title graphenePlaneTransform
#'
#' @param p Plane
#' @param matrix Matrix
#' @param normal_matrix Matrix
#' @return Return value from C function
#' @export
graphenePlaneTransform <- function(p, matrix, normal_matrix) {
  .Call("R_graphene_plane_transform", p, matrix, normal_matrix)$res
}


#' @rdname graphene
#' @title graphenePointAlloc
#'
#' @return Point
#' @export
graphenePointAlloc <- function() {
  .Call("R_graphene_point_alloc")$result
}


#' @rdname graphene
#' @title graphenePointDistance
#'
#' @param a Point
#' @param b Point
#' @return gfloat
#' @export
graphenePointDistance <- function(a, b) {
  .Call("R_graphene_point_distance", a, b)
}


#' @rdname graphene
#' @title graphenePointEqual
#'
#' @param a Point
#' @param b Point
#' @return gboolean
#' @export
graphenePointEqual <- function(a, b) {
  .Call("R_graphene_point_equal", a, b)$result
}


#' @rdname graphene
#' @title graphenePointFree
#'
#' @param p Point
#' @return Return value from C function
#' @export
graphenePointFree <- function(p) {
  invisible(.Call("R_graphene_point_free", p))
}


#' @rdname graphene
#' @title graphenePointInit
#'
#' @param p Point
#' @param x gfloat
#' @param y gfloat
#' @return Point
#' @export
graphenePointInit <- function(p, x, y) {
  .Call("R_graphene_point_init", p, x, y)$result
}


#' @rdname graphene
#' @title graphenePointInitFromPoint
#'
#' @param p Point
#' @param src Point
#' @return Point
#' @export
graphenePointInitFromPoint <- function(p, src) {
  .Call("R_graphene_point_init_from_point", p, src)$result
}


#' @rdname graphene
#' @title graphenePointInitFromVec2
#'
#' @param p Point
#' @param src Vec2
#' @return Point
#' @export
graphenePointInitFromVec2 <- function(p, src) {
  .Call("R_graphene_point_init_from_vec2", p, src)$result
}


#' @rdname graphene
#' @title graphenePointInterpolate
#'
#' @param a Point
#' @param b Point
#' @param factor gdouble
#' @return Return value from C function
#' @export
graphenePointInterpolate <- function(a, b, factor) {
  .Call("R_graphene_point_interpolate", a, b, factor)$res
}


#' @rdname graphene
#' @title graphenePointNear
#'
#' @param a Point
#' @param b Point
#' @param epsilon gfloat
#' @return gboolean
#' @export
graphenePointNear <- function(a, b, epsilon) {
  .Call("R_graphene_point_near", a, b, epsilon)$result
}


#' @rdname graphene
#' @title graphenePointToVec2
#'
#' @param p Point
#' @return Return value from C function
#' @export
graphenePointToVec2 <- function(p) {
  .Call("R_graphene_point_to_vec2", p)$v
}


#' @rdname graphene
#' @title graphenePointZero
#'
#' @return Point
#' @export
graphenePointZero <- function() {
  .Call("R_graphene_point_zero")$result
}


#' @rdname graphene
#' @title graphenePoint3dAlloc
#'
#' @return Point3D
#' @export
graphenePoint3dAlloc <- function() {
  .Call("R_graphene_point3d_alloc")$result
}


#' @rdname graphene
#' @title graphenePoint3dCross
#'
#' @param a Point3D
#' @param b Point3D
#' @return Return value from C function
#' @export
graphenePoint3dCross <- function(a, b) {
  .Call("R_graphene_point3d_cross", a, b)$res
}


#' @rdname graphene
#' @title graphenePoint3dDistance
#'
#' @param a Point3D
#' @param b Point3D
#' @return gfloat
#' @export
graphenePoint3dDistance <- function(a, b) {
  .Call("R_graphene_point3d_distance", a, b)
}


#' @rdname graphene
#' @title graphenePoint3dDot
#'
#' @param a Point3D
#' @param b Point3D
#' @return gfloat
#' @export
graphenePoint3dDot <- function(a, b) {
  .Call("R_graphene_point3d_dot", a, b)$result
}


#' @rdname graphene
#' @title graphenePoint3dEqual
#'
#' @param a Point3D
#' @param b Point3D
#' @return gboolean
#' @export
graphenePoint3dEqual <- function(a, b) {
  .Call("R_graphene_point3d_equal", a, b)$result
}


#' @rdname graphene
#' @title graphenePoint3dFree
#'
#' @param p Point3D
#' @return Return value from C function
#' @export
graphenePoint3dFree <- function(p) {
  invisible(.Call("R_graphene_point3d_free", p))
}


#' @rdname graphene
#' @title graphenePoint3dInit
#'
#' @param p Point3D
#' @param x gfloat
#' @param y gfloat
#' @param z gfloat
#' @return Point3D
#' @export
graphenePoint3dInit <- function(p, x, y, z) {
  .Call("R_graphene_point3d_init", p, x, y, z)$result
}


#' @rdname graphene
#' @title graphenePoint3dInitFromPoint
#'
#' @param p Point3D
#' @param src Point3D
#' @return Point3D
#' @export
graphenePoint3dInitFromPoint <- function(p, src) {
  .Call("R_graphene_point3d_init_from_point", p, src)$result
}


#' @rdname graphene
#' @title graphenePoint3dInitFromVec3
#'
#' @param p Point3D
#' @param v Vec3
#' @return Point3D
#' @export
graphenePoint3dInitFromVec3 <- function(p, v) {
  .Call("R_graphene_point3d_init_from_vec3", p, v)$result
}


#' @rdname graphene
#' @title graphenePoint3dInterpolate
#'
#' @param a Point3D
#' @param b Point3D
#' @param factor gdouble
#' @return Return value from C function
#' @export
graphenePoint3dInterpolate <- function(a, b, factor) {
  .Call("R_graphene_point3d_interpolate", a, b, factor)$res
}


#' @rdname graphene
#' @title graphenePoint3dLength
#'
#' @param p Point3D
#' @return gfloat
#' @export
graphenePoint3dLength <- function(p) {
  .Call("R_graphene_point3d_length", p)$result
}


#' @rdname graphene
#' @title graphenePoint3dNear
#'
#' @param a Point3D
#' @param b Point3D
#' @param epsilon gfloat
#' @return gboolean
#' @export
graphenePoint3dNear <- function(a, b, epsilon) {
  .Call("R_graphene_point3d_near", a, b, epsilon)$result
}


#' @rdname graphene
#' @title graphenePoint3dNormalize
#'
#' @param p Point3D
#' @return Return value from C function
#' @export
graphenePoint3dNormalize <- function(p) {
  .Call("R_graphene_point3d_normalize", p)$res
}


#' @rdname graphene
#' @title graphenePoint3dNormalizeViewport
#'
#' @param p Point3D
#' @param viewport Rect
#' @param z_near gfloat
#' @param z_far gfloat
#' @return Return value from C function
#' @export
graphenePoint3dNormalizeViewport <- function(p, viewport, z_near, z_far) {
  .Call("R_graphene_point3d_normalize_viewport", p, viewport, z_near, z_far)$res
}


#' @rdname graphene
#' @title graphenePoint3dScale
#'
#' @param p Point3D
#' @param factor gfloat
#' @return Return value from C function
#' @export
graphenePoint3dScale <- function(p, factor) {
  .Call("R_graphene_point3d_scale", p, factor)$res
}


#' @rdname graphene
#' @title graphenePoint3dToVec3
#'
#' @param p Point3D
#' @return Return value from C function
#' @export
graphenePoint3dToVec3 <- function(p) {
  .Call("R_graphene_point3d_to_vec3", p)$v
}


#' @rdname graphene
#' @title graphenePoint3dZero
#'
#' @return Point3D
#' @export
graphenePoint3dZero <- function() {
  .Call("R_graphene_point3d_zero")$result
}


#' @rdname graphene
#' @title grapheneQuadAlloc
#'
#' @return Quad
#' @export
grapheneQuadAlloc <- function() {
  .Call("R_graphene_quad_alloc")$result
}


#' @rdname graphene
#' @title grapheneQuadBounds
#'
#' @param q Quad
#' @return Return value from C function
#' @export
grapheneQuadBounds <- function(q) {
  .Call("R_graphene_quad_bounds", q)$r
}


#' @rdname graphene
#' @title grapheneQuadContains
#'
#' @param q Quad
#' @param p Point
#' @return gboolean
#' @export
grapheneQuadContains <- function(q, p) {
  .Call("R_graphene_quad_contains", q, p)$result
}


#' @rdname graphene
#' @title grapheneQuadFree
#'
#' @param q Quad
#' @return Return value from C function
#' @export
grapheneQuadFree <- function(q) {
  invisible(.Call("R_graphene_quad_free", q))
}


#' @rdname graphene
#' @title grapheneQuadGetPoint
#'
#' @param q Quad
#' @param index_ guint
#' @return Point
#' @export
grapheneQuadGetPoint <- function(q, index_) {
  .Call("R_graphene_quad_get_point", q, as.integer(index_))$result
}


#' @rdname graphene
#' @title grapheneQuadInit
#'
#' @param q Quad
#' @param p1 Point
#' @param p2 Point
#' @param p3 Point
#' @param p4 Point
#' @return Quad
#' @export
grapheneQuadInit <- function(q, p1, p2, p3, p4) {
  .Call("R_graphene_quad_init", q, p1, p2, p3, p4)$result
}


#' @rdname graphene
#' @title grapheneQuadInitFromPoints
#'
#' @param q Quad
#' @param points Point
#' @return Quad
#' @export
grapheneQuadInitFromPoints <- function(q, points) {
  .Call("R_graphene_quad_init_from_points", q, points)$result
}


#' @rdname graphene
#' @title grapheneQuadInitFromRect
#'
#' @param q Quad
#' @param r Rect
#' @return Quad
#' @export
grapheneQuadInitFromRect <- function(q, r) {
  .Call("R_graphene_quad_init_from_rect", q, r)$result
}


#' @rdname graphene
#' @title grapheneQuaternionAlloc
#'
#' @return Quaternion
#' @export
grapheneQuaternionAlloc <- function() {
  .Call("R_graphene_quaternion_alloc")$result
}


#' @rdname graphene
#' @title grapheneQuaternionAdd
#'
#' @param a Quaternion
#' @param b Quaternion
#' @return Return value from C function
#' @export
grapheneQuaternionAdd <- function(a, b) {
  .Call("R_graphene_quaternion_add", a, b)$res
}


#' @rdname graphene
#' @title grapheneQuaternionDot
#'
#' @param a Quaternion
#' @param b Quaternion
#' @return gfloat
#' @export
grapheneQuaternionDot <- function(a, b) {
  .Call("R_graphene_quaternion_dot", a, b)$result
}


#' @rdname graphene
#' @title grapheneQuaternionEqual
#'
#' @param a Quaternion
#' @param b Quaternion
#' @return gboolean
#' @export
grapheneQuaternionEqual <- function(a, b) {
  .Call("R_graphene_quaternion_equal", a, b)$result
}


#' @rdname graphene
#' @title grapheneQuaternionFree
#'
#' @param q Quaternion
#' @return Return value from C function
#' @export
grapheneQuaternionFree <- function(q) {
  invisible(.Call("R_graphene_quaternion_free", q))
}


#' @rdname graphene
#' @title grapheneQuaternionInit
#'
#' @param q Quaternion
#' @param x gfloat
#' @param y gfloat
#' @param z gfloat
#' @param w gfloat
#' @return Quaternion
#' @export
grapheneQuaternionInit <- function(q, x, y, z, w) {
  .Call("R_graphene_quaternion_init", q, x, y, z, w)$result
}


#' @rdname graphene
#' @title grapheneQuaternionInitFromAngleVec3
#'
#' @param q Quaternion
#' @param angle gfloat
#' @param axis Vec3
#' @return Quaternion
#' @export
grapheneQuaternionInitFromAngleVec3 <- function(q, angle, axis) {
  .Call("R_graphene_quaternion_init_from_angle_vec3", q, angle, axis)$result
}


#' @rdname graphene
#' @title grapheneQuaternionInitFromAngles
#'
#' @param q Quaternion
#' @param deg_x gfloat
#' @param deg_y gfloat
#' @param deg_z gfloat
#' @return Quaternion
#' @export
grapheneQuaternionInitFromAngles <- function(q, deg_x, deg_y, deg_z) {
  .Call("R_graphene_quaternion_init_from_angles", q, deg_x, deg_y, deg_z)$result
}


#' @rdname graphene
#' @title grapheneQuaternionInitFromEuler
#'
#' @param q Quaternion
#' @param e Euler
#' @return Quaternion
#' @export
grapheneQuaternionInitFromEuler <- function(q, e) {
  .Call("R_graphene_quaternion_init_from_euler", q, e)$result
}


#' @rdname graphene
#' @title grapheneQuaternionInitFromMatrix
#'
#' @param q Quaternion
#' @param m Matrix
#' @return Quaternion
#' @export
grapheneQuaternionInitFromMatrix <- function(q, m) {
  .Call("R_graphene_quaternion_init_from_matrix", q, m)$result
}


#' @rdname graphene
#' @title grapheneQuaternionInitFromQuaternion
#'
#' @param q Quaternion
#' @param src Quaternion
#' @return Quaternion
#' @export
grapheneQuaternionInitFromQuaternion <- function(q, src) {
  .Call("R_graphene_quaternion_init_from_quaternion", q, src)$result
}


#' @rdname graphene
#' @title grapheneQuaternionInitFromRadians
#'
#' @param q Quaternion
#' @param rad_x gfloat
#' @param rad_y gfloat
#' @param rad_z gfloat
#' @return Quaternion
#' @export
grapheneQuaternionInitFromRadians <- function(q, rad_x, rad_y, rad_z) {
  .Call("R_graphene_quaternion_init_from_radians", q, rad_x, rad_y, rad_z)$result
}


#' @rdname graphene
#' @title grapheneQuaternionInitFromVec4
#'
#' @param q Quaternion
#' @param src Vec4
#' @return Quaternion
#' @export
grapheneQuaternionInitFromVec4 <- function(q, src) {
  .Call("R_graphene_quaternion_init_from_vec4", q, src)$result
}


#' @rdname graphene
#' @title grapheneQuaternionInitIdentity
#'
#' @param q Quaternion
#' @return Quaternion
#' @export
grapheneQuaternionInitIdentity <- function(q) {
  .Call("R_graphene_quaternion_init_identity", q)$result
}


#' @rdname graphene
#' @title grapheneQuaternionInvert
#'
#' @param q Quaternion
#' @return Return value from C function
#' @export
grapheneQuaternionInvert <- function(q) {
  .Call("R_graphene_quaternion_invert", q)$res
}


#' @rdname graphene
#' @title grapheneQuaternionMultiply
#'
#' @param a Quaternion
#' @param b Quaternion
#' @return Return value from C function
#' @export
grapheneQuaternionMultiply <- function(a, b) {
  .Call("R_graphene_quaternion_multiply", a, b)$res
}


#' @rdname graphene
#' @title grapheneQuaternionNormalize
#'
#' @param q Quaternion
#' @return Return value from C function
#' @export
grapheneQuaternionNormalize <- function(q) {
  .Call("R_graphene_quaternion_normalize", q)$res
}


#' @rdname graphene
#' @title grapheneQuaternionScale
#'
#' @param q Quaternion
#' @param factor gfloat
#' @return Return value from C function
#' @export
grapheneQuaternionScale <- function(q, factor) {
  .Call("R_graphene_quaternion_scale", q, factor)$res
}


#' @rdname graphene
#' @title grapheneQuaternionSlerp
#'
#' @param a Quaternion
#' @param b Quaternion
#' @param factor gfloat
#' @return Return value from C function
#' @export
grapheneQuaternionSlerp <- function(a, b, factor) {
  .Call("R_graphene_quaternion_slerp", a, b, factor)$res
}


#' @rdname graphene
#' @title grapheneQuaternionToAngleVec3
#'
#' @param q Quaternion
#' @return Return value from C function
#' @export
grapheneQuaternionToAngleVec3 <- function(q) {
  .Call("R_graphene_quaternion_to_angle_vec3", q)
}


#' @rdname graphene
#' @title grapheneQuaternionToAngles
#'
#' @param q Quaternion
#' @return Return value from C function
#' @export
grapheneQuaternionToAngles <- function(q) {
  .Call("R_graphene_quaternion_to_angles", q)
}


#' @rdname graphene
#' @title grapheneQuaternionToMatrix
#'
#' @param q Quaternion
#' @return Return value from C function
#' @export
grapheneQuaternionToMatrix <- function(q) {
  .Call("R_graphene_quaternion_to_matrix", q)$m
}


#' @rdname graphene
#' @title grapheneQuaternionToRadians
#'
#' @param q Quaternion
#' @return Return value from C function
#' @export
grapheneQuaternionToRadians <- function(q) {
  .Call("R_graphene_quaternion_to_radians", q)
}


#' @rdname graphene
#' @title grapheneQuaternionToVec4
#'
#' @param q Quaternion
#' @return Return value from C function
#' @export
grapheneQuaternionToVec4 <- function(q) {
  .Call("R_graphene_quaternion_to_vec4", q)$res
}


#' @rdname graphene
#' @title grapheneRayAlloc
#'
#' @return Ray
#' @export
grapheneRayAlloc <- function() {
  .Call("R_graphene_ray_alloc")$result
}


#' @rdname graphene
#' @title grapheneRayEqual
#'
#' @param a Ray
#' @param b Ray
#' @return gboolean
#' @export
grapheneRayEqual <- function(a, b) {
  .Call("R_graphene_ray_equal", a, b)$result
}


#' @rdname graphene
#' @title grapheneRayFree
#'
#' @param r Ray
#' @return Return value from C function
#' @export
grapheneRayFree <- function(r) {
  invisible(.Call("R_graphene_ray_free", r))
}


#' @rdname graphene
#' @title grapheneRayGetClosestPointToPoint
#'
#' @param r Ray
#' @param p Point3D
#' @return Return value from C function
#' @export
grapheneRayGetClosestPointToPoint <- function(r, p) {
  .Call("R_graphene_ray_get_closest_point_to_point", r, p)$res
}


#' @rdname graphene
#' @title grapheneRayGetDirection
#'
#' @param r Ray
#' @return Return value from C function
#' @export
grapheneRayGetDirection <- function(r) {
  .Call("R_graphene_ray_get_direction", r)$direction
}


#' @rdname graphene
#' @title grapheneRayGetDistanceToPlane
#'
#' @param r Ray
#' @param p Plane
#' @return gfloat
#' @export
grapheneRayGetDistanceToPlane <- function(r, p) {
  .Call("R_graphene_ray_get_distance_to_plane", r, p)$result
}


#' @rdname graphene
#' @title grapheneRayGetDistanceToPoint
#'
#' @param r Ray
#' @param p Point3D
#' @return gfloat
#' @export
grapheneRayGetDistanceToPoint <- function(r, p) {
  .Call("R_graphene_ray_get_distance_to_point", r, p)$result
}


#' @rdname graphene
#' @title grapheneRayGetOrigin
#'
#' @param r Ray
#' @return Return value from C function
#' @export
grapheneRayGetOrigin <- function(r) {
  .Call("R_graphene_ray_get_origin", r)$origin
}


#' @rdname graphene
#' @title grapheneRayGetPositionAt
#'
#' @param r Ray
#' @param t gfloat
#' @return Return value from C function
#' @export
grapheneRayGetPositionAt <- function(r, t) {
  .Call("R_graphene_ray_get_position_at", r, t)$position
}


#' @rdname graphene
#' @title grapheneRayInit
#'
#' @param r Ray
#' @param origin Point3D
#' @param direction Vec3
#' @return Ray
#' @export
grapheneRayInit <- function(r, origin, direction) {
  .Call("R_graphene_ray_init", r, origin, direction)$result
}


#' @rdname graphene
#' @title grapheneRayInitFromRay
#'
#' @param r Ray
#' @param src Ray
#' @return Ray
#' @export
grapheneRayInitFromRay <- function(r, src) {
  .Call("R_graphene_ray_init_from_ray", r, src)$result
}


#' @rdname graphene
#' @title grapheneRayInitFromVec3
#'
#' @param r Ray
#' @param origin Vec3
#' @param direction Vec3
#' @return Ray
#' @export
grapheneRayInitFromVec3 <- function(r, origin, direction) {
  .Call("R_graphene_ray_init_from_vec3", r, origin, direction)$result
}


#' @rdname graphene
#' @title grapheneRayIntersectBox
#'
#' @param r Ray
#' @param b Box
#' @return RayIntersectionKind
#' @export
grapheneRayIntersectBox <- function(r, b) {
  .Call("R_graphene_ray_intersect_box", r, b)
}


#' @rdname graphene
#' @title grapheneRayIntersectSphere
#'
#' @param r Ray
#' @param s Sphere
#' @return RayIntersectionKind
#' @export
grapheneRayIntersectSphere <- function(r, s) {
  .Call("R_graphene_ray_intersect_sphere", r, s)
}


#' @rdname graphene
#' @title grapheneRayIntersectTriangle
#'
#' @param r Ray
#' @param t Triangle
#' @return RayIntersectionKind
#' @export
grapheneRayIntersectTriangle <- function(r, t) {
  .Call("R_graphene_ray_intersect_triangle", r, t)
}


#' @rdname graphene
#' @title grapheneRayIntersectsBox
#'
#' @param r Ray
#' @param b Box
#' @return gboolean
#' @export
grapheneRayIntersectsBox <- function(r, b) {
  .Call("R_graphene_ray_intersects_box", r, b)$result
}


#' @rdname graphene
#' @title grapheneRayIntersectsSphere
#'
#' @param r Ray
#' @param s Sphere
#' @return gboolean
#' @export
grapheneRayIntersectsSphere <- function(r, s) {
  .Call("R_graphene_ray_intersects_sphere", r, s)$result
}


#' @rdname graphene
#' @title grapheneRayIntersectsTriangle
#'
#' @param r Ray
#' @param t Triangle
#' @return gboolean
#' @export
grapheneRayIntersectsTriangle <- function(r, t) {
  .Call("R_graphene_ray_intersects_triangle", r, t)$result
}


#' @rdname graphene
#' @title grapheneRectContainsPoint
#'
#' @param r Rect
#' @param p Point
#' @return gboolean
#' @export
grapheneRectContainsPoint <- function(r, p) {
  .Call("R_graphene_rect_contains_point", r, p)$result
}


#' @rdname graphene
#' @title grapheneRectContainsRect
#'
#' @param a Rect
#' @param b Rect
#' @return gboolean
#' @export
grapheneRectContainsRect <- function(a, b) {
  .Call("R_graphene_rect_contains_rect", a, b)$result
}


#' @rdname graphene
#' @title grapheneRectEqual
#'
#' @param a Rect
#' @param b Rect
#' @return gboolean
#' @export
grapheneRectEqual <- function(a, b) {
  .Call("R_graphene_rect_equal", a, b)$result
}


#' @rdname graphene
#' @title grapheneRectExpand
#'
#' @param r Rect
#' @param p Point
#' @return Return value from C function
#' @export
grapheneRectExpand <- function(r, p) {
  .Call("R_graphene_rect_expand", r, p)$res
}


#' @rdname graphene
#' @title grapheneRectFree
#'
#' @param r Rect
#' @return Return value from C function
#' @export
grapheneRectFree <- function(r) {
  invisible(.Call("R_graphene_rect_free", r))
}


#' @rdname graphene
#' @title grapheneRectGetArea
#'
#' @param r Rect
#' @return gfloat
#' @export
grapheneRectGetArea <- function(r) {
  .Call("R_graphene_rect_get_area", r)$result
}


#' @rdname graphene
#' @title grapheneRectGetBottomLeft
#'
#' @param r Rect
#' @return Return value from C function
#' @export
grapheneRectGetBottomLeft <- function(r) {
  .Call("R_graphene_rect_get_bottom_left", r)$p
}


#' @rdname graphene
#' @title grapheneRectGetBottomRight
#'
#' @param r Rect
#' @return Return value from C function
#' @export
grapheneRectGetBottomRight <- function(r) {
  .Call("R_graphene_rect_get_bottom_right", r)$p
}


#' @rdname graphene
#' @title grapheneRectGetCenter
#'
#' @param r Rect
#' @return Return value from C function
#' @export
grapheneRectGetCenter <- function(r) {
  .Call("R_graphene_rect_get_center", r)$p
}


#' @rdname graphene
#' @title grapheneRectGetHeight
#'
#' @param r Rect
#' @return gfloat
#' @export
grapheneRectGetHeight <- function(r) {
  .Call("R_graphene_rect_get_height", r)$result
}


#' @rdname graphene
#' @title grapheneRectGetTopLeft
#'
#' @param r Rect
#' @return Return value from C function
#' @export
grapheneRectGetTopLeft <- function(r) {
  .Call("R_graphene_rect_get_top_left", r)$p
}


#' @rdname graphene
#' @title grapheneRectGetTopRight
#'
#' @param r Rect
#' @return Return value from C function
#' @export
grapheneRectGetTopRight <- function(r) {
  .Call("R_graphene_rect_get_top_right", r)$p
}


#' @rdname graphene
#' @title grapheneRectGetVertices
#'
#' @param r Rect
#' @return Return value from C function
#' @export
grapheneRectGetVertices <- function(r) {
  .Call("R_graphene_rect_get_vertices", r)$vertices
}


#' @rdname graphene
#' @title grapheneRectGetWidth
#'
#' @param r Rect
#' @return gfloat
#' @export
grapheneRectGetWidth <- function(r) {
  .Call("R_graphene_rect_get_width", r)$result
}


#' @rdname graphene
#' @title grapheneRectGetX
#'
#' @param r Rect
#' @return gfloat
#' @export
grapheneRectGetX <- function(r) {
  .Call("R_graphene_rect_get_x", r)$result
}


#' @rdname graphene
#' @title grapheneRectGetY
#'
#' @param r Rect
#' @return gfloat
#' @export
grapheneRectGetY <- function(r) {
  .Call("R_graphene_rect_get_y", r)$result
}


#' @rdname graphene
#' @title grapheneRectInit
#'
#' @param r Rect
#' @param x gfloat
#' @param y gfloat
#' @param width gfloat
#' @param height gfloat
#' @return Rect
#' @export
grapheneRectInit <- function(r, x, y, width, height) {
  .Call("R_graphene_rect_init", r, x, y, width, height)$result
}


#' @rdname graphene
#' @title grapheneRectInitFromRect
#'
#' @param r Rect
#' @param src Rect
#' @return Rect
#' @export
grapheneRectInitFromRect <- function(r, src) {
  .Call("R_graphene_rect_init_from_rect", r, src)$result
}


#' @rdname graphene
#' @title grapheneRectInset
#'
#' @param r Rect
#' @param d_x gfloat
#' @param d_y gfloat
#' @return Rect
#' @export
grapheneRectInset <- function(r, d_x, d_y) {
  .Call("R_graphene_rect_inset", r, d_x, d_y)$result
}


#' @rdname graphene
#' @title grapheneRectInsetR
#'
#' @param r Rect
#' @param d_x gfloat
#' @param d_y gfloat
#' @return Return value from C function
#' @export
grapheneRectInsetR <- function(r, d_x, d_y) {
  .Call("R_graphene_rect_inset_r", r, d_x, d_y)$res
}


#' @rdname graphene
#' @title grapheneRectInterpolate
#'
#' @param a Rect
#' @param b Rect
#' @param factor gdouble
#' @return Return value from C function
#' @export
grapheneRectInterpolate <- function(a, b, factor) {
  .Call("R_graphene_rect_interpolate", a, b, factor)$res
}


#' @rdname graphene
#' @title grapheneRectIntersection
#'
#' @param a Rect
#' @param b Rect
#' @return gboolean
#' @export
grapheneRectIntersection <- function(a, b) {
  .Call("R_graphene_rect_intersection", a, b)
}


#' @rdname graphene
#' @title grapheneRectNormalize
#'
#' @param r Rect
#' @return Rect
#' @export
grapheneRectNormalize <- function(r) {
  .Call("R_graphene_rect_normalize", r)$result
}


#' @rdname graphene
#' @title grapheneRectNormalizeR
#'
#' @param r Rect
#' @return Return value from C function
#' @export
grapheneRectNormalizeR <- function(r) {
  .Call("R_graphene_rect_normalize_r", r)$res
}


#' @rdname graphene
#' @title grapheneRectOffset
#'
#' @param r Rect
#' @param d_x gfloat
#' @param d_y gfloat
#' @return Rect
#' @export
grapheneRectOffset <- function(r, d_x, d_y) {
  .Call("R_graphene_rect_offset", r, d_x, d_y)$result
}


#' @rdname graphene
#' @title grapheneRectOffsetR
#'
#' @param r Rect
#' @param d_x gfloat
#' @param d_y gfloat
#' @return Return value from C function
#' @export
grapheneRectOffsetR <- function(r, d_x, d_y) {
  .Call("R_graphene_rect_offset_r", r, d_x, d_y)$res
}


#' @rdname graphene
#' @title grapheneRectRound
#'
#' @param r Rect
#' @return Return value from C function
#' @export
grapheneRectRound <- function(r) {
  .Call("R_graphene_rect_round", r)$res
}


#' @rdname graphene
#' @title grapheneRectRoundExtents
#'
#' @param r Rect
#' @return Return value from C function
#' @export
grapheneRectRoundExtents <- function(r) {
  .Call("R_graphene_rect_round_extents", r)$res
}


#' @rdname graphene
#' @title grapheneRectRoundToPixel
#'
#' @param r Rect
#' @return Rect
#' @export
grapheneRectRoundToPixel <- function(r) {
  .Call("R_graphene_rect_round_to_pixel", r)$result
}


#' @rdname graphene
#' @title grapheneRectScale
#'
#' @param r Rect
#' @param s_h gfloat
#' @param s_v gfloat
#' @return Return value from C function
#' @export
grapheneRectScale <- function(r, s_h, s_v) {
  .Call("R_graphene_rect_scale", r, s_h, s_v)$res
}


#' @rdname graphene
#' @title grapheneRectUnion
#'
#' @param a Rect
#' @param b Rect
#' @return Return value from C function
#' @export
grapheneRectUnion <- function(a, b) {
  .Call("R_graphene_rect_union", a, b)$res
}


#' @rdname graphene
#' @title grapheneRectAlloc
#'
#' @return Rect
#' @export
grapheneRectAlloc <- function() {
  .Call("R_graphene_rect_alloc")$result
}


#' @rdname graphene
#' @title grapheneRectZero
#'
#' @return Rect
#' @export
grapheneRectZero <- function() {
  .Call("R_graphene_rect_zero")$result
}


#' @rdname graphene
#' @title grapheneSizeAlloc
#'
#' @return Size
#' @export
grapheneSizeAlloc <- function() {
  .Call("R_graphene_size_alloc")$result
}


#' @rdname graphene
#' @title grapheneSizeEqual
#'
#' @param a Size
#' @param b Size
#' @return gboolean
#' @export
grapheneSizeEqual <- function(a, b) {
  .Call("R_graphene_size_equal", a, b)$result
}


#' @rdname graphene
#' @title grapheneSizeFree
#'
#' @param s Size
#' @return Return value from C function
#' @export
grapheneSizeFree <- function(s) {
  invisible(.Call("R_graphene_size_free", s))
}


#' @rdname graphene
#' @title grapheneSizeInit
#'
#' @param s Size
#' @param width gfloat
#' @param height gfloat
#' @return Size
#' @export
grapheneSizeInit <- function(s, width, height) {
  .Call("R_graphene_size_init", s, width, height)$result
}


#' @rdname graphene
#' @title grapheneSizeInitFromSize
#'
#' @param s Size
#' @param src Size
#' @return Size
#' @export
grapheneSizeInitFromSize <- function(s, src) {
  .Call("R_graphene_size_init_from_size", s, src)$result
}


#' @rdname graphene
#' @title grapheneSizeInterpolate
#'
#' @param a Size
#' @param b Size
#' @param factor gdouble
#' @return Return value from C function
#' @export
grapheneSizeInterpolate <- function(a, b, factor) {
  .Call("R_graphene_size_interpolate", a, b, factor)$res
}


#' @rdname graphene
#' @title grapheneSizeScale
#'
#' @param s Size
#' @param factor gfloat
#' @return Return value from C function
#' @export
grapheneSizeScale <- function(s, factor) {
  .Call("R_graphene_size_scale", s, factor)$res
}


#' @rdname graphene
#' @title grapheneSizeZero
#'
#' @return Size
#' @export
grapheneSizeZero <- function() {
  .Call("R_graphene_size_zero")$result
}


#' @rdname graphene
#' @title grapheneSphereAlloc
#'
#' @return Sphere
#' @export
grapheneSphereAlloc <- function() {
  .Call("R_graphene_sphere_alloc")$result
}


#' @rdname graphene
#' @title grapheneSphereContainsPoint
#'
#' @param s Sphere
#' @param point Point3D
#' @return gboolean
#' @export
grapheneSphereContainsPoint <- function(s, point) {
  .Call("R_graphene_sphere_contains_point", s, point)$result
}


#' @rdname graphene
#' @title grapheneSphereDistance
#'
#' @param s Sphere
#' @param point Point3D
#' @return gfloat
#' @export
grapheneSphereDistance <- function(s, point) {
  .Call("R_graphene_sphere_distance", s, point)$result
}


#' @rdname graphene
#' @title grapheneSphereEqual
#'
#' @param a Sphere
#' @param b Sphere
#' @return gboolean
#' @export
grapheneSphereEqual <- function(a, b) {
  .Call("R_graphene_sphere_equal", a, b)$result
}


#' @rdname graphene
#' @title grapheneSphereFree
#'
#' @param s Sphere
#' @return Return value from C function
#' @export
grapheneSphereFree <- function(s) {
  invisible(.Call("R_graphene_sphere_free", s))
}


#' @rdname graphene
#' @title grapheneSphereGetBoundingBox
#'
#' @param s Sphere
#' @return Return value from C function
#' @export
grapheneSphereGetBoundingBox <- function(s) {
  .Call("R_graphene_sphere_get_bounding_box", s)$box
}


#' @rdname graphene
#' @title grapheneSphereGetCenter
#'
#' @param s Sphere
#' @return Return value from C function
#' @export
grapheneSphereGetCenter <- function(s) {
  .Call("R_graphene_sphere_get_center", s)$center
}


#' @rdname graphene
#' @title grapheneSphereGetRadius
#'
#' @param s Sphere
#' @return gfloat
#' @export
grapheneSphereGetRadius <- function(s) {
  .Call("R_graphene_sphere_get_radius", s)$result
}


#' @rdname graphene
#' @title grapheneSphereInit
#'
#' @param s Sphere
#' @param center Point3D
#' @param radius gfloat
#' @return Sphere
#' @export
grapheneSphereInit <- function(s, center, radius) {
  .Call("R_graphene_sphere_init", s, center, radius)$result
}


#' @rdname graphene
#' @title grapheneSphereInitFromPoints
#'
#' @param s Sphere
#' @param n_points guint
#' @param points Point3D
#' @param center Point3D
#' @return Sphere
#' @export
grapheneSphereInitFromPoints <- function(s, n_points, points, center) {
  .Call("R_graphene_sphere_init_from_points", s, as.integer(n_points), points, center)$result
}


#' @rdname graphene
#' @title grapheneSphereInitFromVectors
#'
#' @param s Sphere
#' @param n_vectors guint
#' @param vectors Vec3
#' @param center Point3D
#' @return Sphere
#' @export
grapheneSphereInitFromVectors <- function(s, n_vectors, vectors, center) {
  .Call("R_graphene_sphere_init_from_vectors", s, as.integer(n_vectors), vectors, center)$result
}


#' @rdname graphene
#' @title grapheneSphereIsEmpty
#'
#' @param s Sphere
#' @return gboolean
#' @export
grapheneSphereIsEmpty <- function(s) {
  .Call("R_graphene_sphere_is_empty", s)$result
}


#' @rdname graphene
#' @title grapheneSphereTranslate
#'
#' @param s Sphere
#' @param point Point3D
#' @return Return value from C function
#' @export
grapheneSphereTranslate <- function(s, point) {
  .Call("R_graphene_sphere_translate", s, point)$res
}


#' @rdname graphene
#' @title grapheneTriangleAlloc
#'
#' @return Triangle
#' @export
grapheneTriangleAlloc <- function() {
  .Call("R_graphene_triangle_alloc")$result
}


#' @rdname graphene
#' @title grapheneTriangleContainsPoint
#'
#' @param t Triangle
#' @param p Point3D
#' @return gboolean
#' @export
grapheneTriangleContainsPoint <- function(t, p) {
  .Call("R_graphene_triangle_contains_point", t, p)$result
}


#' @rdname graphene
#' @title grapheneTriangleEqual
#'
#' @param a Triangle
#' @param b Triangle
#' @return gboolean
#' @export
grapheneTriangleEqual <- function(a, b) {
  .Call("R_graphene_triangle_equal", a, b)$result
}


#' @rdname graphene
#' @title grapheneTriangleFree
#'
#' @param t Triangle
#' @return Return value from C function
#' @export
grapheneTriangleFree <- function(t) {
  invisible(.Call("R_graphene_triangle_free", t))
}


#' @rdname graphene
#' @title grapheneTriangleGetArea
#'
#' @param t Triangle
#' @return gfloat
#' @export
grapheneTriangleGetArea <- function(t) {
  .Call("R_graphene_triangle_get_area", t)$result
}


#' @rdname graphene
#' @title grapheneTriangleGetBarycoords
#'
#' @param t Triangle
#' @param p Point3D
#' @return gboolean
#' @export
grapheneTriangleGetBarycoords <- function(t, p) {
  .Call("R_graphene_triangle_get_barycoords", t, p)
}


#' @rdname graphene
#' @title grapheneTriangleGetBoundingBox
#'
#' @param t Triangle
#' @return Return value from C function
#' @export
grapheneTriangleGetBoundingBox <- function(t) {
  .Call("R_graphene_triangle_get_bounding_box", t)$res
}


#' @rdname graphene
#' @title grapheneTriangleGetMidpoint
#'
#' @param t Triangle
#' @return Return value from C function
#' @export
grapheneTriangleGetMidpoint <- function(t) {
  .Call("R_graphene_triangle_get_midpoint", t)$res
}


#' @rdname graphene
#' @title grapheneTriangleGetNormal
#'
#' @param t Triangle
#' @return Return value from C function
#' @export
grapheneTriangleGetNormal <- function(t) {
  .Call("R_graphene_triangle_get_normal", t)$res
}


#' @rdname graphene
#' @title grapheneTriangleGetPlane
#'
#' @param t Triangle
#' @return Return value from C function
#' @export
grapheneTriangleGetPlane <- function(t) {
  .Call("R_graphene_triangle_get_plane", t)$res
}


#' @rdname graphene
#' @title grapheneTriangleGetPoints
#'
#' @param t Triangle
#' @return Return value from C function
#' @export
grapheneTriangleGetPoints <- function(t) {
  .Call("R_graphene_triangle_get_points", t)
}


#' @rdname graphene
#' @title grapheneTriangleGetUv
#'
#' @param t Triangle
#' @param p Point3D
#' @param uv_a Vec2
#' @param uv_b Vec2
#' @param uv_c Vec2
#' @return gboolean
#' @export
grapheneTriangleGetUv <- function(t, p, uv_a, uv_b, uv_c) {
  .Call("R_graphene_triangle_get_uv", t, p, uv_a, uv_b, uv_c)
}


#' @rdname graphene
#' @title grapheneTriangleGetVertices
#'
#' @param t Triangle
#' @return Return value from C function
#' @export
grapheneTriangleGetVertices <- function(t) {
  .Call("R_graphene_triangle_get_vertices", t)
}


#' @rdname graphene
#' @title grapheneTriangleInitFromFloat
#'
#' @param t Triangle
#' @param a gfloat
#' @param b gfloat
#' @param c gfloat
#' @return Triangle
#' @export
grapheneTriangleInitFromFloat <- function(t, a, b, c) {
  .Call("R_graphene_triangle_init_from_float", t, a, b, c)$result
}


#' @rdname graphene
#' @title grapheneTriangleInitFromPoint3d
#'
#' @param t Triangle
#' @param a Point3D
#' @param b Point3D
#' @param c Point3D
#' @return Triangle
#' @export
grapheneTriangleInitFromPoint3d <- function(t, a, b, c) {
  .Call("R_graphene_triangle_init_from_point3d", t, a, b, c)$result
}


#' @rdname graphene
#' @title grapheneTriangleInitFromVec3
#'
#' @param t Triangle
#' @param a Vec3
#' @param b Vec3
#' @param c Vec3
#' @return Triangle
#' @export
grapheneTriangleInitFromVec3 <- function(t, a, b, c) {
  .Call("R_graphene_triangle_init_from_vec3", t, a, b, c)$result
}


#' @rdname graphene
#' @title grapheneVec2Alloc
#'
#' @return Vec2
#' @export
grapheneVec2Alloc <- function() {
  .Call("R_graphene_vec2_alloc")$result
}


#' @rdname graphene
#' @title grapheneVec2Add
#'
#' @param a Vec2
#' @param b Vec2
#' @return Return value from C function
#' @export
grapheneVec2Add <- function(a, b) {
  .Call("R_graphene_vec2_add", a, b)$res
}


#' @rdname graphene
#' @title grapheneVec2Divide
#'
#' @param a Vec2
#' @param b Vec2
#' @return Return value from C function
#' @export
grapheneVec2Divide <- function(a, b) {
  .Call("R_graphene_vec2_divide", a, b)$res
}


#' @rdname graphene
#' @title grapheneVec2Dot
#'
#' @param a Vec2
#' @param b Vec2
#' @return gfloat
#' @export
grapheneVec2Dot <- function(a, b) {
  .Call("R_graphene_vec2_dot", a, b)$result
}


#' @rdname graphene
#' @title grapheneVec2Equal
#'
#' @param v1 Vec2
#' @param v2 Vec2
#' @return gboolean
#' @export
grapheneVec2Equal <- function(v1, v2) {
  .Call("R_graphene_vec2_equal", v1, v2)$result
}


#' @rdname graphene
#' @title grapheneVec2Free
#'
#' @param v Vec2
#' @return Return value from C function
#' @export
grapheneVec2Free <- function(v) {
  invisible(.Call("R_graphene_vec2_free", v))
}


#' @rdname graphene
#' @title grapheneVec2GetX
#'
#' @param v Vec2
#' @return gfloat
#' @export
grapheneVec2GetX <- function(v) {
  .Call("R_graphene_vec2_get_x", v)$result
}


#' @rdname graphene
#' @title grapheneVec2GetY
#'
#' @param v Vec2
#' @return gfloat
#' @export
grapheneVec2GetY <- function(v) {
  .Call("R_graphene_vec2_get_y", v)$result
}


#' @rdname graphene
#' @title grapheneVec2Init
#'
#' @param v Vec2
#' @param x gfloat
#' @param y gfloat
#' @return Vec2
#' @export
grapheneVec2Init <- function(v, x, y) {
  .Call("R_graphene_vec2_init", v, x, y)$result
}


#' @rdname graphene
#' @title grapheneVec2InitFromFloat
#'
#' @param v Vec2
#' @param src gfloat
#' @return Vec2
#' @export
grapheneVec2InitFromFloat <- function(v, src) {
  .Call("R_graphene_vec2_init_from_float", v, src)$result
}


#' @rdname graphene
#' @title grapheneVec2InitFromVec2
#'
#' @param v Vec2
#' @param src Vec2
#' @return Vec2
#' @export
grapheneVec2InitFromVec2 <- function(v, src) {
  .Call("R_graphene_vec2_init_from_vec2", v, src)$result
}


#' @rdname graphene
#' @title grapheneVec2Interpolate
#'
#' @param v1 Vec2
#' @param v2 Vec2
#' @param factor gdouble
#' @return Return value from C function
#' @export
grapheneVec2Interpolate <- function(v1, v2, factor) {
  .Call("R_graphene_vec2_interpolate", v1, v2, factor)$res
}


#' @rdname graphene
#' @title grapheneVec2Length
#'
#' @param v Vec2
#' @return gfloat
#' @export
grapheneVec2Length <- function(v) {
  .Call("R_graphene_vec2_length", v)$result
}


#' @rdname graphene
#' @title grapheneVec2Max
#'
#' @param a Vec2
#' @param b Vec2
#' @return Return value from C function
#' @export
grapheneVec2Max <- function(a, b) {
  .Call("R_graphene_vec2_max", a, b)$res
}


#' @rdname graphene
#' @title grapheneVec2Min
#'
#' @param a Vec2
#' @param b Vec2
#' @return Return value from C function
#' @export
grapheneVec2Min <- function(a, b) {
  .Call("R_graphene_vec2_min", a, b)$res
}


#' @rdname graphene
#' @title grapheneVec2Multiply
#'
#' @param a Vec2
#' @param b Vec2
#' @return Return value from C function
#' @export
grapheneVec2Multiply <- function(a, b) {
  .Call("R_graphene_vec2_multiply", a, b)$res
}


#' @rdname graphene
#' @title grapheneVec2Near
#'
#' @param v1 Vec2
#' @param v2 Vec2
#' @param epsilon gfloat
#' @return gboolean
#' @export
grapheneVec2Near <- function(v1, v2, epsilon) {
  .Call("R_graphene_vec2_near", v1, v2, epsilon)$result
}


#' @rdname graphene
#' @title grapheneVec2Negate
#'
#' @param v Vec2
#' @return Return value from C function
#' @export
grapheneVec2Negate <- function(v) {
  .Call("R_graphene_vec2_negate", v)$res
}


#' @rdname graphene
#' @title grapheneVec2Normalize
#'
#' @param v Vec2
#' @return Return value from C function
#' @export
grapheneVec2Normalize <- function(v) {
  .Call("R_graphene_vec2_normalize", v)$res
}


#' @rdname graphene
#' @title grapheneVec2Scale
#'
#' @param v Vec2
#' @param factor gfloat
#' @return Return value from C function
#' @export
grapheneVec2Scale <- function(v, factor) {
  .Call("R_graphene_vec2_scale", v, factor)$res
}


#' @rdname graphene
#' @title grapheneVec2Subtract
#'
#' @param a Vec2
#' @param b Vec2
#' @return Return value from C function
#' @export
grapheneVec2Subtract <- function(a, b) {
  .Call("R_graphene_vec2_subtract", a, b)$res
}


#' @rdname graphene
#' @title grapheneVec2ToFloat
#'
#' @param v Vec2
#' @return Return value from C function
#' @export
grapheneVec2ToFloat <- function(v) {
  .Call("R_graphene_vec2_to_float", v)$dest
}


#' @rdname graphene
#' @title grapheneVec2One
#'
#' @return Vec2
#' @export
grapheneVec2One <- function() {
  .Call("R_graphene_vec2_one")$result
}


#' @rdname graphene
#' @title grapheneVec2XAxis
#'
#' @return Vec2
#' @export
grapheneVec2XAxis <- function() {
  .Call("R_graphene_vec2_x_axis")$result
}


#' @rdname graphene
#' @title grapheneVec2YAxis
#'
#' @return Vec2
#' @export
grapheneVec2YAxis <- function() {
  .Call("R_graphene_vec2_y_axis")$result
}


#' @rdname graphene
#' @title grapheneVec2Zero
#'
#' @return Vec2
#' @export
grapheneVec2Zero <- function() {
  .Call("R_graphene_vec2_zero")$result
}


#' @rdname graphene
#' @title grapheneVec3Alloc
#'
#' @return Vec3
#' @export
grapheneVec3Alloc <- function() {
  .Call("R_graphene_vec3_alloc")$result
}


#' @rdname graphene
#' @title grapheneVec3Add
#'
#' @param a Vec3
#' @param b Vec3
#' @return Return value from C function
#' @export
grapheneVec3Add <- function(a, b) {
  .Call("R_graphene_vec3_add", a, b)$res
}


#' @rdname graphene
#' @title grapheneVec3Cross
#'
#' @param a Vec3
#' @param b Vec3
#' @return Return value from C function
#' @export
grapheneVec3Cross <- function(a, b) {
  .Call("R_graphene_vec3_cross", a, b)$res
}


#' @rdname graphene
#' @title grapheneVec3Divide
#'
#' @param a Vec3
#' @param b Vec3
#' @return Return value from C function
#' @export
grapheneVec3Divide <- function(a, b) {
  .Call("R_graphene_vec3_divide", a, b)$res
}


#' @rdname graphene
#' @title grapheneVec3Dot
#'
#' @param a Vec3
#' @param b Vec3
#' @return gfloat
#' @export
grapheneVec3Dot <- function(a, b) {
  .Call("R_graphene_vec3_dot", a, b)$result
}


#' @rdname graphene
#' @title grapheneVec3Equal
#'
#' @param v1 Vec3
#' @param v2 Vec3
#' @return gboolean
#' @export
grapheneVec3Equal <- function(v1, v2) {
  .Call("R_graphene_vec3_equal", v1, v2)$result
}


#' @rdname graphene
#' @title grapheneVec3Free
#'
#' @param v Vec3
#' @return Return value from C function
#' @export
grapheneVec3Free <- function(v) {
  invisible(.Call("R_graphene_vec3_free", v))
}


#' @rdname graphene
#' @title grapheneVec3GetX
#'
#' @param v Vec3
#' @return gfloat
#' @export
grapheneVec3GetX <- function(v) {
  .Call("R_graphene_vec3_get_x", v)$result
}


#' @rdname graphene
#' @title grapheneVec3GetXy
#'
#' @param v Vec3
#' @return Return value from C function
#' @export
grapheneVec3GetXy <- function(v) {
  .Call("R_graphene_vec3_get_xy", v)$res
}


#' @rdname graphene
#' @title grapheneVec3GetXy0
#'
#' @param v Vec3
#' @return Return value from C function
#' @export
grapheneVec3GetXy0 <- function(v) {
  .Call("R_graphene_vec3_get_xy0", v)$res
}


#' @rdname graphene
#' @title grapheneVec3GetXyz0
#'
#' @param v Vec3
#' @return Return value from C function
#' @export
grapheneVec3GetXyz0 <- function(v) {
  .Call("R_graphene_vec3_get_xyz0", v)$res
}


#' @rdname graphene
#' @title grapheneVec3GetXyz1
#'
#' @param v Vec3
#' @return Return value from C function
#' @export
grapheneVec3GetXyz1 <- function(v) {
  .Call("R_graphene_vec3_get_xyz1", v)$res
}


#' @rdname graphene
#' @title grapheneVec3GetXyzw
#'
#' @param v Vec3
#' @param w gfloat
#' @return Return value from C function
#' @export
grapheneVec3GetXyzw <- function(v, w) {
  .Call("R_graphene_vec3_get_xyzw", v, w)$res
}


#' @rdname graphene
#' @title grapheneVec3GetY
#'
#' @param v Vec3
#' @return gfloat
#' @export
grapheneVec3GetY <- function(v) {
  .Call("R_graphene_vec3_get_y", v)$result
}


#' @rdname graphene
#' @title grapheneVec3GetZ
#'
#' @param v Vec3
#' @return gfloat
#' @export
grapheneVec3GetZ <- function(v) {
  .Call("R_graphene_vec3_get_z", v)$result
}


#' @rdname graphene
#' @title grapheneVec3Init
#'
#' @param v Vec3
#' @param x gfloat
#' @param y gfloat
#' @param z gfloat
#' @return Vec3
#' @export
grapheneVec3Init <- function(v, x, y, z) {
  .Call("R_graphene_vec3_init", v, x, y, z)$result
}


#' @rdname graphene
#' @title grapheneVec3InitFromFloat
#'
#' @param v Vec3
#' @param src gfloat
#' @return Vec3
#' @export
grapheneVec3InitFromFloat <- function(v, src) {
  .Call("R_graphene_vec3_init_from_float", v, src)$result
}


#' @rdname graphene
#' @title grapheneVec3InitFromVec3
#'
#' @param v Vec3
#' @param src Vec3
#' @return Vec3
#' @export
grapheneVec3InitFromVec3 <- function(v, src) {
  .Call("R_graphene_vec3_init_from_vec3", v, src)$result
}


#' @rdname graphene
#' @title grapheneVec3Interpolate
#'
#' @param v1 Vec3
#' @param v2 Vec3
#' @param factor gdouble
#' @return Return value from C function
#' @export
grapheneVec3Interpolate <- function(v1, v2, factor) {
  .Call("R_graphene_vec3_interpolate", v1, v2, factor)$res
}


#' @rdname graphene
#' @title grapheneVec3Length
#'
#' @param v Vec3
#' @return gfloat
#' @export
grapheneVec3Length <- function(v) {
  .Call("R_graphene_vec3_length", v)$result
}


#' @rdname graphene
#' @title grapheneVec3Max
#'
#' @param a Vec3
#' @param b Vec3
#' @return Return value from C function
#' @export
grapheneVec3Max <- function(a, b) {
  .Call("R_graphene_vec3_max", a, b)$res
}


#' @rdname graphene
#' @title grapheneVec3Min
#'
#' @param a Vec3
#' @param b Vec3
#' @return Return value from C function
#' @export
grapheneVec3Min <- function(a, b) {
  .Call("R_graphene_vec3_min", a, b)$res
}


#' @rdname graphene
#' @title grapheneVec3Multiply
#'
#' @param a Vec3
#' @param b Vec3
#' @return Return value from C function
#' @export
grapheneVec3Multiply <- function(a, b) {
  .Call("R_graphene_vec3_multiply", a, b)$res
}


#' @rdname graphene
#' @title grapheneVec3Near
#'
#' @param v1 Vec3
#' @param v2 Vec3
#' @param epsilon gfloat
#' @return gboolean
#' @export
grapheneVec3Near <- function(v1, v2, epsilon) {
  .Call("R_graphene_vec3_near", v1, v2, epsilon)$result
}


#' @rdname graphene
#' @title grapheneVec3Negate
#'
#' @param v Vec3
#' @return Return value from C function
#' @export
grapheneVec3Negate <- function(v) {
  .Call("R_graphene_vec3_negate", v)$res
}


#' @rdname graphene
#' @title grapheneVec3Normalize
#'
#' @param v Vec3
#' @return Return value from C function
#' @export
grapheneVec3Normalize <- function(v) {
  .Call("R_graphene_vec3_normalize", v)$res
}


#' @rdname graphene
#' @title grapheneVec3Scale
#'
#' @param v Vec3
#' @param factor gfloat
#' @return Return value from C function
#' @export
grapheneVec3Scale <- function(v, factor) {
  .Call("R_graphene_vec3_scale", v, factor)$res
}


#' @rdname graphene
#' @title grapheneVec3Subtract
#'
#' @param a Vec3
#' @param b Vec3
#' @return Return value from C function
#' @export
grapheneVec3Subtract <- function(a, b) {
  .Call("R_graphene_vec3_subtract", a, b)$res
}


#' @rdname graphene
#' @title grapheneVec3ToFloat
#'
#' @param v Vec3
#' @return Return value from C function
#' @export
grapheneVec3ToFloat <- function(v) {
  .Call("R_graphene_vec3_to_float", v)$dest
}


#' @rdname graphene
#' @title grapheneVec3One
#'
#' @return Vec3
#' @export
grapheneVec3One <- function() {
  .Call("R_graphene_vec3_one")$result
}


#' @rdname graphene
#' @title grapheneVec3XAxis
#'
#' @return Vec3
#' @export
grapheneVec3XAxis <- function() {
  .Call("R_graphene_vec3_x_axis")$result
}


#' @rdname graphene
#' @title grapheneVec3YAxis
#'
#' @return Vec3
#' @export
grapheneVec3YAxis <- function() {
  .Call("R_graphene_vec3_y_axis")$result
}


#' @rdname graphene
#' @title grapheneVec3ZAxis
#'
#' @return Vec3
#' @export
grapheneVec3ZAxis <- function() {
  .Call("R_graphene_vec3_z_axis")$result
}


#' @rdname graphene
#' @title grapheneVec3Zero
#'
#' @return Vec3
#' @export
grapheneVec3Zero <- function() {
  .Call("R_graphene_vec3_zero")$result
}


#' @rdname graphene
#' @title grapheneVec4Alloc
#'
#' @return Vec4
#' @export
grapheneVec4Alloc <- function() {
  .Call("R_graphene_vec4_alloc")$result
}


#' @rdname graphene
#' @title grapheneVec4Add
#'
#' @param a Vec4
#' @param b Vec4
#' @return Return value from C function
#' @export
grapheneVec4Add <- function(a, b) {
  .Call("R_graphene_vec4_add", a, b)$res
}


#' @rdname graphene
#' @title grapheneVec4Divide
#'
#' @param a Vec4
#' @param b Vec4
#' @return Return value from C function
#' @export
grapheneVec4Divide <- function(a, b) {
  .Call("R_graphene_vec4_divide", a, b)$res
}


#' @rdname graphene
#' @title grapheneVec4Dot
#'
#' @param a Vec4
#' @param b Vec4
#' @return gfloat
#' @export
grapheneVec4Dot <- function(a, b) {
  .Call("R_graphene_vec4_dot", a, b)$result
}


#' @rdname graphene
#' @title grapheneVec4Equal
#'
#' @param v1 Vec4
#' @param v2 Vec4
#' @return gboolean
#' @export
grapheneVec4Equal <- function(v1, v2) {
  .Call("R_graphene_vec4_equal", v1, v2)$result
}


#' @rdname graphene
#' @title grapheneVec4Free
#'
#' @param v Vec4
#' @return Return value from C function
#' @export
grapheneVec4Free <- function(v) {
  invisible(.Call("R_graphene_vec4_free", v))
}


#' @rdname graphene
#' @title grapheneVec4GetW
#'
#' @param v Vec4
#' @return gfloat
#' @export
grapheneVec4GetW <- function(v) {
  .Call("R_graphene_vec4_get_w", v)$result
}


#' @rdname graphene
#' @title grapheneVec4GetX
#'
#' @param v Vec4
#' @return gfloat
#' @export
grapheneVec4GetX <- function(v) {
  .Call("R_graphene_vec4_get_x", v)$result
}


#' @rdname graphene
#' @title grapheneVec4GetXy
#'
#' @param v Vec4
#' @return Return value from C function
#' @export
grapheneVec4GetXy <- function(v) {
  .Call("R_graphene_vec4_get_xy", v)$res
}


#' @rdname graphene
#' @title grapheneVec4GetXyz
#'
#' @param v Vec4
#' @return Return value from C function
#' @export
grapheneVec4GetXyz <- function(v) {
  .Call("R_graphene_vec4_get_xyz", v)$res
}


#' @rdname graphene
#' @title grapheneVec4GetY
#'
#' @param v Vec4
#' @return gfloat
#' @export
grapheneVec4GetY <- function(v) {
  .Call("R_graphene_vec4_get_y", v)$result
}


#' @rdname graphene
#' @title grapheneVec4GetZ
#'
#' @param v Vec4
#' @return gfloat
#' @export
grapheneVec4GetZ <- function(v) {
  .Call("R_graphene_vec4_get_z", v)$result
}


#' @rdname graphene
#' @title grapheneVec4Init
#'
#' @param v Vec4
#' @param x gfloat
#' @param y gfloat
#' @param z gfloat
#' @param w gfloat
#' @return Vec4
#' @export
grapheneVec4Init <- function(v, x, y, z, w) {
  .Call("R_graphene_vec4_init", v, x, y, z, w)$result
}


#' @rdname graphene
#' @title grapheneVec4InitFromFloat
#'
#' @param v Vec4
#' @param src gfloat
#' @return Vec4
#' @export
grapheneVec4InitFromFloat <- function(v, src) {
  .Call("R_graphene_vec4_init_from_float", v, src)$result
}


#' @rdname graphene
#' @title grapheneVec4InitFromVec2
#'
#' @param v Vec4
#' @param src Vec2
#' @param z gfloat
#' @param w gfloat
#' @return Vec4
#' @export
grapheneVec4InitFromVec2 <- function(v, src, z, w) {
  .Call("R_graphene_vec4_init_from_vec2", v, src, z, w)$result
}


#' @rdname graphene
#' @title grapheneVec4InitFromVec3
#'
#' @param v Vec4
#' @param src Vec3
#' @param w gfloat
#' @return Vec4
#' @export
grapheneVec4InitFromVec3 <- function(v, src, w) {
  .Call("R_graphene_vec4_init_from_vec3", v, src, w)$result
}


#' @rdname graphene
#' @title grapheneVec4InitFromVec4
#'
#' @param v Vec4
#' @param src Vec4
#' @return Vec4
#' @export
grapheneVec4InitFromVec4 <- function(v, src) {
  .Call("R_graphene_vec4_init_from_vec4", v, src)$result
}


#' @rdname graphene
#' @title grapheneVec4Interpolate
#'
#' @param v1 Vec4
#' @param v2 Vec4
#' @param factor gdouble
#' @return Return value from C function
#' @export
grapheneVec4Interpolate <- function(v1, v2, factor) {
  .Call("R_graphene_vec4_interpolate", v1, v2, factor)$res
}


#' @rdname graphene
#' @title grapheneVec4Length
#'
#' @param v Vec4
#' @return gfloat
#' @export
grapheneVec4Length <- function(v) {
  .Call("R_graphene_vec4_length", v)$result
}


#' @rdname graphene
#' @title grapheneVec4Max
#'
#' @param a Vec4
#' @param b Vec4
#' @return Return value from C function
#' @export
grapheneVec4Max <- function(a, b) {
  .Call("R_graphene_vec4_max", a, b)$res
}


#' @rdname graphene
#' @title grapheneVec4Min
#'
#' @param a Vec4
#' @param b Vec4
#' @return Return value from C function
#' @export
grapheneVec4Min <- function(a, b) {
  .Call("R_graphene_vec4_min", a, b)$res
}


#' @rdname graphene
#' @title grapheneVec4Multiply
#'
#' @param a Vec4
#' @param b Vec4
#' @return Return value from C function
#' @export
grapheneVec4Multiply <- function(a, b) {
  .Call("R_graphene_vec4_multiply", a, b)$res
}


#' @rdname graphene
#' @title grapheneVec4Near
#'
#' @param v1 Vec4
#' @param v2 Vec4
#' @param epsilon gfloat
#' @return gboolean
#' @export
grapheneVec4Near <- function(v1, v2, epsilon) {
  .Call("R_graphene_vec4_near", v1, v2, epsilon)$result
}


#' @rdname graphene
#' @title grapheneVec4Negate
#'
#' @param v Vec4
#' @return Return value from C function
#' @export
grapheneVec4Negate <- function(v) {
  .Call("R_graphene_vec4_negate", v)$res
}


#' @rdname graphene
#' @title grapheneVec4Normalize
#'
#' @param v Vec4
#' @return Return value from C function
#' @export
grapheneVec4Normalize <- function(v) {
  .Call("R_graphene_vec4_normalize", v)$res
}


#' @rdname graphene
#' @title grapheneVec4Scale
#'
#' @param v Vec4
#' @param factor gfloat
#' @return Return value from C function
#' @export
grapheneVec4Scale <- function(v, factor) {
  .Call("R_graphene_vec4_scale", v, factor)$res
}


#' @rdname graphene
#' @title grapheneVec4Subtract
#'
#' @param a Vec4
#' @param b Vec4
#' @return Return value from C function
#' @export
grapheneVec4Subtract <- function(a, b) {
  .Call("R_graphene_vec4_subtract", a, b)$res
}


#' @rdname graphene
#' @title grapheneVec4ToFloat
#'
#' @param v Vec4
#' @return Return value from C function
#' @export
grapheneVec4ToFloat <- function(v) {
  .Call("R_graphene_vec4_to_float", v)$dest
}


#' @rdname graphene
#' @title grapheneVec4One
#'
#' @return Vec4
#' @export
grapheneVec4One <- function() {
  .Call("R_graphene_vec4_one")$result
}


#' @rdname graphene
#' @title grapheneVec4WAxis
#'
#' @return Vec4
#' @export
grapheneVec4WAxis <- function() {
  .Call("R_graphene_vec4_w_axis")$result
}


#' @rdname graphene
#' @title grapheneVec4XAxis
#'
#' @return Vec4
#' @export
grapheneVec4XAxis <- function() {
  .Call("R_graphene_vec4_x_axis")$result
}


#' @rdname graphene
#' @title grapheneVec4YAxis
#'
#' @return Vec4
#' @export
grapheneVec4YAxis <- function() {
  .Call("R_graphene_vec4_y_axis")$result
}


#' @rdname graphene
#' @title grapheneVec4ZAxis
#'
#' @return Vec4
#' @export
grapheneVec4ZAxis <- function() {
  .Call("R_graphene_vec4_z_axis")$result
}


#' @rdname graphene
#' @title grapheneVec4Zero
#'
#' @return Vec4
#' @export
grapheneVec4Zero <- function() {
  .Call("R_graphene_vec4_zero")$result
}


# Enumerations

# EulerOrder
DEFAULT <- -1
XYZ <- 0
YZX <- 1
ZXY <- 2
XZY <- 3
YXZ <- 4
ZYX <- 5
SXYZ <- 6
SXYX <- 7
SXZY <- 8
SXZX <- 9
SYZX <- 10
SYZY <- 11
SYXZ <- 12
SYXY <- 13
SZXY <- 14
SZXZ <- 15
SZYX <- 16
SZYZ <- 17
RZYX <- 18
RXYX <- 19
RYZX <- 20
RXZX <- 21
RXZY <- 22
RYZY <- 23
RZXY <- 24
RYXY <- 25
RYXZ <- 26
RZXZ <- 27
RXYZ <- 28
RZYZ <- 29

# RayIntersectionKind
NONE <- 0
ENTER <- 1
LEAVE <- 2
