# Autogenerated R wrappers

#' @rdname gsk
#' @title gskBlendNodeNew
#'
#' @param bottom RenderNode
#' @param top RenderNode
#' @param blend_mode BlendMode
#' @return BlendNode
#' @export
gskBlendNodeNew <- function(bottom, top, blend_mode) {
  .Call("R_gsk_blend_node_new", bottom, top, blend_mode)$result
}


#' @rdname gsk
#' @title gskBlendNodeGetBlendMode
#'
#' @param node BlendNode
#' @return BlendMode
#' @export
gskBlendNodeGetBlendMode <- function(node) {
  .Call("R_gsk_blend_node_get_blend_mode", node)$result
}


#' @rdname gsk
#' @title gskBlendNodeGetBottomChild
#'
#' @param node BlendNode
#' @return RenderNode
#' @export
gskBlendNodeGetBottomChild <- function(node) {
  .Call("R_gsk_blend_node_get_bottom_child", node)$result
}


#' @rdname gsk
#' @title gskBlendNodeGetTopChild
#'
#' @param node BlendNode
#' @return RenderNode
#' @export
gskBlendNodeGetTopChild <- function(node) {
  .Call("R_gsk_blend_node_get_top_child", node)$result
}


#' @rdname gsk
#' @title gskBlurNodeNew
#'
#' @param child RenderNode
#' @param radius gfloat
#' @return BlurNode
#' @export
gskBlurNodeNew <- function(child, radius) {
  .Call("R_gsk_blur_node_new", child, radius)$result
}


#' @rdname gsk
#' @title gskBlurNodeGetChild
#'
#' @param node BlurNode
#' @return RenderNode
#' @export
gskBlurNodeGetChild <- function(node) {
  .Call("R_gsk_blur_node_get_child", node)$result
}


#' @rdname gsk
#' @title gskBlurNodeGetRadius
#'
#' @param node BlurNode
#' @return gfloat
#' @export
gskBlurNodeGetRadius <- function(node) {
  .Call("R_gsk_blur_node_get_radius", node)$result
}


#' @rdname gsk
#' @title gskBorderNodeNew
#'
#' @param outline RoundedRect
#' @param border_width gfloat
#' @param border_color Gdk.RGBA
#' @return BorderNode
#' @export
gskBorderNodeNew <- function(outline, border_width, border_color) {
  .Call("R_gsk_border_node_new", outline, border_width, border_color)$result
}


#' @rdname gsk
#' @title gskBorderNodeGetColors
#'
#' @param node BorderNode
#' @return Gdk.RGBA
#' @export
gskBorderNodeGetColors <- function(node) {
  .Call("R_gsk_border_node_get_colors", node)$result
}


#' @rdname gsk
#' @title gskBorderNodeGetOutline
#'
#' @param node BorderNode
#' @return RoundedRect
#' @export
gskBorderNodeGetOutline <- function(node) {
  .Call("R_gsk_border_node_get_outline", node)$result
}


#' @rdname gsk
#' @title gskBorderNodeGetWidths
#'
#' @param node BorderNode
#' @return gfloat
#' @export
gskBorderNodeGetWidths <- function(node) {
  .Call("R_gsk_border_node_get_widths", node)$result
}


#' @rdname gsk
#' @title gskCairoNodeNew
#'
#' @param bounds Graphene.Rect
#' @return CairoNode
#' @export
gskCairoNodeNew <- function(bounds) {
  .Call("R_gsk_cairo_node_new", bounds)$result
}


#' @rdname gsk
#' @title gskCairoNodeGetDrawContext
#'
#' @param node CairoNode
#' @return cairo.Context
#' @export
gskCairoNodeGetDrawContext <- function(node) {
  .Call("R_gsk_cairo_node_get_draw_context", node)$result
}


#' @rdname gsk
#' @title gskCairoNodeGetSurface
#'
#' @param node CairoNode
#' @return cairo.Surface
#' @export
gskCairoNodeGetSurface <- function(node) {
  .Call("R_gsk_cairo_node_get_surface", node)$result
}


#' @rdname gsk
#' @title gskCairoRendererNew
#'
#' @return Renderer
#' @export
gskCairoRendererNew <- function() {
  .Call("R_gsk_cairo_renderer_new")$result
}


#' @rdname gsk
#' @title gskClipNodeNew
#'
#' @param child RenderNode
#' @param clip Graphene.Rect
#' @return ClipNode
#' @export
gskClipNodeNew <- function(child, clip) {
  .Call("R_gsk_clip_node_new", child, clip)$result
}


#' @rdname gsk
#' @title gskClipNodeGetChild
#'
#' @param node ClipNode
#' @return RenderNode
#' @export
gskClipNodeGetChild <- function(node) {
  .Call("R_gsk_clip_node_get_child", node)$result
}


#' @rdname gsk
#' @title gskClipNodeGetClip
#'
#' @param node ClipNode
#' @return Graphene.Rect
#' @export
gskClipNodeGetClip <- function(node) {
  .Call("R_gsk_clip_node_get_clip", node)$result
}


#' @rdname gsk
#' @title gskColorMatrixNodeNew
#'
#' @param child RenderNode
#' @param color_matrix Graphene.Matrix
#' @param color_offset Graphene.Vec4
#' @return ColorMatrixNode
#' @export
gskColorMatrixNodeNew <- function(child, color_matrix, color_offset) {
  .Call("R_gsk_color_matrix_node_new", child, color_matrix, color_offset)$result
}


#' @rdname gsk
#' @title gskColorMatrixNodeGetChild
#'
#' @param node ColorMatrixNode
#' @return RenderNode
#' @export
gskColorMatrixNodeGetChild <- function(node) {
  .Call("R_gsk_color_matrix_node_get_child", node)$result
}


#' @rdname gsk
#' @title gskColorMatrixNodeGetColorMatrix
#'
#' @param node ColorMatrixNode
#' @return Graphene.Matrix
#' @export
gskColorMatrixNodeGetColorMatrix <- function(node) {
  .Call("R_gsk_color_matrix_node_get_color_matrix", node)$result
}


#' @rdname gsk
#' @title gskColorMatrixNodeGetColorOffset
#'
#' @param node ColorMatrixNode
#' @return Graphene.Vec4
#' @export
gskColorMatrixNodeGetColorOffset <- function(node) {
  .Call("R_gsk_color_matrix_node_get_color_offset", node)$result
}


#' @rdname gsk
#' @title gskColorNodeNew
#'
#' @param rgba Gdk.RGBA
#' @param bounds Graphene.Rect
#' @return ColorNode
#' @export
gskColorNodeNew <- function(rgba, bounds) {
  .Call("R_gsk_color_node_new", rgba, bounds)$result
}


#' @rdname gsk
#' @title gskColorNodeGetColor
#'
#' @param node ColorNode
#' @return Gdk.RGBA
#' @export
gskColorNodeGetColor <- function(node) {
  .Call("R_gsk_color_node_get_color", node)$result
}


#' @rdname gsk
#' @title gskComponentTransferNewDiscrete
#'
#' @param n guint
#' @param values gfloat
#' @return ComponentTransfer
#' @export
gskComponentTransferNewDiscrete <- function(n, values) {
  .Call("R_gsk_component_transfer_new_discrete", as.integer(n), values)$result
}


#' @rdname gsk
#' @title gskComponentTransferNewGamma
#'
#' @param amp gfloat
#' @param exp gfloat
#' @param ofs gfloat
#' @return ComponentTransfer
#' @export
gskComponentTransferNewGamma <- function(amp, exp, ofs) {
  .Call("R_gsk_component_transfer_new_gamma", amp, exp, ofs)$result
}


#' @rdname gsk
#' @title gskComponentTransferNewIdentity
#'
#' @return ComponentTransfer
#' @export
gskComponentTransferNewIdentity <- function() {
  .Call("R_gsk_component_transfer_new_identity")$result
}


#' @rdname gsk
#' @title gskComponentTransferNewLevels
#'
#' @param n gfloat
#' @return ComponentTransfer
#' @export
gskComponentTransferNewLevels <- function(n) {
  .Call("R_gsk_component_transfer_new_levels", n)$result
}


#' @rdname gsk
#' @title gskComponentTransferNewLinear
#'
#' @param m gfloat
#' @param b gfloat
#' @return ComponentTransfer
#' @export
gskComponentTransferNewLinear <- function(m, b) {
  .Call("R_gsk_component_transfer_new_linear", m, b)$result
}


#' @rdname gsk
#' @title gskComponentTransferNewTable
#'
#' @param n guint
#' @param values gfloat
#' @return ComponentTransfer
#' @export
gskComponentTransferNewTable <- function(n, values) {
  .Call("R_gsk_component_transfer_new_table", as.integer(n), values)$result
}


#' @rdname gsk
#' @title gskComponentTransferCopy
#'
#' @param other ComponentTransfer
#' @return ComponentTransfer
#' @export
gskComponentTransferCopy <- function(other) {
  .Call("R_gsk_component_transfer_copy", other)$result
}


#' @rdname gsk
#' @title gskComponentTransferFree
#'
#' @param self ComponentTransfer
#' @return Return value from C function
#' @export
gskComponentTransferFree <- function(self) {
  invisible(.Call("R_gsk_component_transfer_free", self))
}


#' @rdname gsk
#' @title gskComponentTransferEqual
#'
#' @param self gpointer
#' @param other gpointer
#' @return gboolean
#' @export
gskComponentTransferEqual <- function(self, other) {
  .Call("R_gsk_component_transfer_equal", self, other)$result
}


#' @rdname gsk
#' @title gskComponentTransferNodeNew
#'
#' @param child RenderNode
#' @param r ComponentTransfer
#' @param g ComponentTransfer
#' @param b ComponentTransfer
#' @param a ComponentTransfer
#' @return ComponentTransferNode
#' @export
gskComponentTransferNodeNew <- function(child, r, g, b, a) {
  .Call("R_gsk_component_transfer_node_new", child, r, g, b, a)$result
}


#' @rdname gsk
#' @title gskComponentTransferNodeGetChild
#'
#' @param node ComponentTransferNode
#' @return RenderNode
#' @export
gskComponentTransferNodeGetChild <- function(node) {
  .Call("R_gsk_component_transfer_node_get_child", node)$result
}


#' @rdname gsk
#' @title gskComponentTransferNodeGetTransfer
#'
#' @param node ComponentTransferNode
#' @param component Gdk.ColorChannel
#' @return ComponentTransfer
#' @export
gskComponentTransferNodeGetTransfer <- function(node, component) {
  .Call("R_gsk_component_transfer_node_get_transfer", node, component)$result
}


#' @rdname gsk
#' @title gskCompositeNodeNew
#'
#' @param child RenderNode
#' @param mask RenderNode
#' @param op PorterDuff
#' @return CompositeNode
#' @export
gskCompositeNodeNew <- function(child, mask, op) {
  .Call("R_gsk_composite_node_new", child, mask, op)$result
}


#' @rdname gsk
#' @title gskCompositeNodeGetChild
#'
#' @param node CompositeNode
#' @return RenderNode
#' @export
gskCompositeNodeGetChild <- function(node) {
  .Call("R_gsk_composite_node_get_child", node)$result
}


#' @rdname gsk
#' @title gskCompositeNodeGetMask
#'
#' @param node CompositeNode
#' @return RenderNode
#' @export
gskCompositeNodeGetMask <- function(node) {
  .Call("R_gsk_composite_node_get_mask", node)$result
}


#' @rdname gsk
#' @title gskCompositeNodeGetOperator
#'
#' @param node CompositeNode
#' @return PorterDuff
#' @export
gskCompositeNodeGetOperator <- function(node) {
  .Call("R_gsk_composite_node_get_operator", node)$result
}


#' @rdname gsk
#' @title gskConicGradientNodeNew
#'
#' @param bounds Graphene.Rect
#' @param center Graphene.Point
#' @param rotation gfloat
#' @param color_stops ColorStop
#' @param n_color_stops gsize
#' @return ConicGradientNode
#' @export
gskConicGradientNodeNew <- function(bounds, center, rotation, color_stops, n_color_stops) {
  .Call("R_gsk_conic_gradient_node_new", bounds, center, rotation, color_stops, as.integer(n_color_stops))$result
}


#' @rdname gsk
#' @title gskConicGradientNodeGetAngle
#'
#' @param node ConicGradientNode
#' @return gfloat
#' @export
gskConicGradientNodeGetAngle <- function(node) {
  .Call("R_gsk_conic_gradient_node_get_angle", node)$result
}


#' @rdname gsk
#' @title gskConicGradientNodeGetCenter
#'
#' @param node ConicGradientNode
#' @return Graphene.Point
#' @export
gskConicGradientNodeGetCenter <- function(node) {
  .Call("R_gsk_conic_gradient_node_get_center", node)$result
}


#' @rdname gsk
#' @title gskConicGradientNodeGetColorStops
#'
#' @param node ConicGradientNode
#' @return ColorStop
#' @export
gskConicGradientNodeGetColorStops <- function(node) {
  .Call("R_gsk_conic_gradient_node_get_color_stops", node)
}


#' @rdname gsk
#' @title gskConicGradientNodeGetNColorStops
#'
#' @param node ConicGradientNode
#' @return gsize
#' @export
gskConicGradientNodeGetNColorStops <- function(node) {
  .Call("R_gsk_conic_gradient_node_get_n_color_stops", node)$result
}


#' @rdname gsk
#' @title gskConicGradientNodeGetRotation
#'
#' @param node ConicGradientNode
#' @return gfloat
#' @export
gskConicGradientNodeGetRotation <- function(node) {
  .Call("R_gsk_conic_gradient_node_get_rotation", node)$result
}


#' @rdname gsk
#' @title gskContainerNodeNew
#'
#' @param children RenderNode
#' @param n_children guint
#' @return ContainerNode
#' @export
gskContainerNodeNew <- function(children, n_children) {
  .Call("R_gsk_container_node_new", children, as.integer(n_children))$result
}


#' @rdname gsk
#' @title gskContainerNodeGetChild
#'
#' @param node ContainerNode
#' @param idx guint
#' @return RenderNode
#' @export
gskContainerNodeGetChild <- function(node, idx) {
  .Call("R_gsk_container_node_get_child", node, as.integer(idx))$result
}


#' @rdname gsk
#' @title gskContainerNodeGetNChildren
#'
#' @param node ContainerNode
#' @return guint
#' @export
gskContainerNodeGetNChildren <- function(node) {
  .Call("R_gsk_container_node_get_n_children", node)$result
}


#' @rdname gsk
#' @title gskCopyNodeNew
#'
#' @param child RenderNode
#' @return CopyNode
#' @export
gskCopyNodeNew <- function(child) {
  .Call("R_gsk_copy_node_new", child)$result
}


#' @rdname gsk
#' @title gskCopyNodeGetChild
#'
#' @param node CopyNode
#' @return RenderNode
#' @export
gskCopyNodeGetChild <- function(node) {
  .Call("R_gsk_copy_node_get_child", node)$result
}


#' @rdname gsk
#' @title gskCrossFadeNodeNew
#'
#' @param start RenderNode
#' @param end RenderNode
#' @param progress gfloat
#' @return CrossFadeNode
#' @export
gskCrossFadeNodeNew <- function(start, end, progress) {
  .Call("R_gsk_cross_fade_node_new", start, end, progress)$result
}


#' @rdname gsk
#' @title gskCrossFadeNodeGetEndChild
#'
#' @param node CrossFadeNode
#' @return RenderNode
#' @export
gskCrossFadeNodeGetEndChild <- function(node) {
  .Call("R_gsk_cross_fade_node_get_end_child", node)$result
}


#' @rdname gsk
#' @title gskCrossFadeNodeGetProgress
#'
#' @param node CrossFadeNode
#' @return gfloat
#' @export
gskCrossFadeNodeGetProgress <- function(node) {
  .Call("R_gsk_cross_fade_node_get_progress", node)$result
}


#' @rdname gsk
#' @title gskCrossFadeNodeGetStartChild
#'
#' @param node CrossFadeNode
#' @return RenderNode
#' @export
gskCrossFadeNodeGetStartChild <- function(node) {
  .Call("R_gsk_cross_fade_node_get_start_child", node)$result
}


#' @rdname gsk
#' @title gskDebugNodeNew
#'
#' @param child RenderNode
#' @param message utf8
#' @return DebugNode
#' @export
gskDebugNodeNew <- function(child, message) {
  .Call("R_gsk_debug_node_new", child, message)$result
}


#' @rdname gsk
#' @title gskDebugNodeGetChild
#'
#' @param node DebugNode
#' @return RenderNode
#' @export
gskDebugNodeGetChild <- function(node) {
  .Call("R_gsk_debug_node_get_child", node)$result
}


#' @rdname gsk
#' @title gskDebugNodeGetMessage
#'
#' @param node DebugNode
#' @return utf8
#' @export
gskDebugNodeGetMessage <- function(node) {
  .Call("R_gsk_debug_node_get_message", node)$result
}


#' @rdname gsk
#' @title gskFillNodeNew
#'
#' @param child RenderNode
#' @param path Path
#' @param fill_rule FillRule
#' @return FillNode
#' @export
gskFillNodeNew <- function(child, path, fill_rule) {
  .Call("R_gsk_fill_node_new", child, path, fill_rule)$result
}


#' @rdname gsk
#' @title gskFillNodeGetChild
#'
#' @param node FillNode
#' @return RenderNode
#' @export
gskFillNodeGetChild <- function(node) {
  .Call("R_gsk_fill_node_get_child", node)$result
}


#' @rdname gsk
#' @title gskFillNodeGetFillRule
#'
#' @param node FillNode
#' @return FillRule
#' @export
gskFillNodeGetFillRule <- function(node) {
  .Call("R_gsk_fill_node_get_fill_rule", node)$result
}


#' @rdname gsk
#' @title gskFillNodeGetPath
#'
#' @param node FillNode
#' @return Path
#' @export
gskFillNodeGetPath <- function(node) {
  .Call("R_gsk_fill_node_get_path", node)$result
}


#' @rdname gsk
#' @title gskGlRendererNew
#'
#' @return Renderer
#' @export
gskGlRendererNew <- function() {
  .Call("R_gsk_gl_renderer_new")$result
}


#' @rdname gsk
#' @title gskGlShaderNewFromBytes
#'
#' @param sourcecode GLib.Bytes
#' @return GLShader
#' @export
gskGlShaderNewFromBytes <- function(sourcecode) {
  .Call("R_gsk_gl_shader_new_from_bytes", sourcecode)$result
}


#' @rdname gsk
#' @title gskGlShaderNewFromResource
#'
#' @param resource_path utf8
#' @return GLShader
#' @export
gskGlShaderNewFromResource <- function(resource_path) {
  .Call("R_gsk_gl_shader_new_from_resource", resource_path)$result
}


#' @rdname gsk
#' @title gskGlShaderCompile
#'
#' @param shader GLShader
#' @param renderer Renderer
#' @return gboolean
#' @export
gskGlShaderCompile <- function(shader, renderer) {
  .Call("R_gsk_gl_shader_compile", shader, renderer)$result
}


#' @rdname gsk
#' @title gskGlShaderFindUniformByName
#'
#' @param shader GLShader
#' @param name utf8
#' @return gint
#' @export
gskGlShaderFindUniformByName <- function(shader, name) {
  .Call("R_gsk_gl_shader_find_uniform_by_name", shader, name)$result
}


#' @rdname gsk
#' @title gskGlShaderGetArgBool
#'
#' @param shader GLShader
#' @param args GLib.Bytes
#' @param idx gint
#' @return gboolean
#' @export
gskGlShaderGetArgBool <- function(shader, args, idx) {
  .Call("R_gsk_gl_shader_get_arg_bool", shader, args, as.integer(idx))$result
}


#' @rdname gsk
#' @title gskGlShaderGetArgFloat
#'
#' @param shader GLShader
#' @param args GLib.Bytes
#' @param idx gint
#' @return gfloat
#' @export
gskGlShaderGetArgFloat <- function(shader, args, idx) {
  .Call("R_gsk_gl_shader_get_arg_float", shader, args, as.integer(idx))$result
}


#' @rdname gsk
#' @title gskGlShaderGetArgInt
#'
#' @param shader GLShader
#' @param args GLib.Bytes
#' @param idx gint
#' @return gint32
#' @export
gskGlShaderGetArgInt <- function(shader, args, idx) {
  .Call("R_gsk_gl_shader_get_arg_int", shader, args, as.integer(idx))$result
}


#' @rdname gsk
#' @title gskGlShaderGetArgUint
#'
#' @param shader GLShader
#' @param args GLib.Bytes
#' @param idx gint
#' @return guint32
#' @export
gskGlShaderGetArgUint <- function(shader, args, idx) {
  .Call("R_gsk_gl_shader_get_arg_uint", shader, args, as.integer(idx))$result
}


#' @rdname gsk
#' @title gskGlShaderGetArgVec2
#'
#' @param shader GLShader
#' @param args GLib.Bytes
#' @param idx gint
#' @param out_value Graphene.Vec2
#' @return Return value from C function
#' @export
gskGlShaderGetArgVec2 <- function(shader, args, idx, out_value) {
  invisible(.Call("R_gsk_gl_shader_get_arg_vec2", shader, args, as.integer(idx), out_value))
}


#' @rdname gsk
#' @title gskGlShaderGetArgVec3
#'
#' @param shader GLShader
#' @param args GLib.Bytes
#' @param idx gint
#' @param out_value Graphene.Vec3
#' @return Return value from C function
#' @export
gskGlShaderGetArgVec3 <- function(shader, args, idx, out_value) {
  invisible(.Call("R_gsk_gl_shader_get_arg_vec3", shader, args, as.integer(idx), out_value))
}


#' @rdname gsk
#' @title gskGlShaderGetArgVec4
#'
#' @param shader GLShader
#' @param args GLib.Bytes
#' @param idx gint
#' @param out_value Graphene.Vec4
#' @return Return value from C function
#' @export
gskGlShaderGetArgVec4 <- function(shader, args, idx, out_value) {
  invisible(.Call("R_gsk_gl_shader_get_arg_vec4", shader, args, as.integer(idx), out_value))
}


#' @rdname gsk
#' @title gskGlShaderGetArgsSize
#'
#' @param shader GLShader
#' @return gsize
#' @export
gskGlShaderGetArgsSize <- function(shader) {
  .Call("R_gsk_gl_shader_get_args_size", shader)$result
}


#' @rdname gsk
#' @title gskGlShaderGetNTextures
#'
#' @param shader GLShader
#' @return gint
#' @export
gskGlShaderGetNTextures <- function(shader) {
  .Call("R_gsk_gl_shader_get_n_textures", shader)$result
}


#' @rdname gsk
#' @title gskGlShaderGetNUniforms
#'
#' @param shader GLShader
#' @return gint
#' @export
gskGlShaderGetNUniforms <- function(shader) {
  .Call("R_gsk_gl_shader_get_n_uniforms", shader)$result
}


#' @rdname gsk
#' @title gskGlShaderGetResource
#'
#' @param shader GLShader
#' @return utf8
#' @export
gskGlShaderGetResource <- function(shader) {
  .Call("R_gsk_gl_shader_get_resource", shader)$result
}


#' @rdname gsk
#' @title gskGlShaderGetSource
#'
#' @param shader GLShader
#' @return GLib.Bytes
#' @export
gskGlShaderGetSource <- function(shader) {
  .Call("R_gsk_gl_shader_get_source", shader)$result
}


#' @rdname gsk
#' @title gskGlShaderGetUniformName
#'
#' @param shader GLShader
#' @param idx gint
#' @return utf8
#' @export
gskGlShaderGetUniformName <- function(shader, idx) {
  .Call("R_gsk_gl_shader_get_uniform_name", shader, as.integer(idx))$result
}


#' @rdname gsk
#' @title gskGlShaderGetUniformOffset
#'
#' @param shader GLShader
#' @param idx gint
#' @return gint
#' @export
gskGlShaderGetUniformOffset <- function(shader, idx) {
  .Call("R_gsk_gl_shader_get_uniform_offset", shader, as.integer(idx))$result
}


#' @rdname gsk
#' @title gskGlShaderGetUniformType
#'
#' @param shader GLShader
#' @param idx gint
#' @return GLUniformType
#' @export
gskGlShaderGetUniformType <- function(shader, idx) {
  .Call("R_gsk_gl_shader_get_uniform_type", shader, as.integer(idx))$result
}


#' @rdname gsk
#' @title gskGlShaderNodeNew
#'
#' @param shader GLShader
#' @param bounds Graphene.Rect
#' @param args GLib.Bytes
#' @param children RenderNode
#' @param n_children guint
#' @return GLShaderNode
#' @export
gskGlShaderNodeNew <- function(shader, bounds, args, children, n_children) {
  .Call("R_gsk_gl_shader_node_new", shader, bounds, args, children, as.integer(n_children))$result
}


#' @rdname gsk
#' @title gskGlShaderNodeGetArgs
#'
#' @param node GLShaderNode
#' @return GLib.Bytes
#' @export
gskGlShaderNodeGetArgs <- function(node) {
  .Call("R_gsk_gl_shader_node_get_args", node)$result
}


#' @rdname gsk
#' @title gskGlShaderNodeGetChild
#'
#' @param node GLShaderNode
#' @param idx guint
#' @return RenderNode
#' @export
gskGlShaderNodeGetChild <- function(node, idx) {
  .Call("R_gsk_gl_shader_node_get_child", node, as.integer(idx))$result
}


#' @rdname gsk
#' @title gskGlShaderNodeGetNChildren
#'
#' @param node GLShaderNode
#' @return guint
#' @export
gskGlShaderNodeGetNChildren <- function(node) {
  .Call("R_gsk_gl_shader_node_get_n_children", node)$result
}


#' @rdname gsk
#' @title gskGlShaderNodeGetShader
#'
#' @param node GLShaderNode
#' @return GLShader
#' @export
gskGlShaderNodeGetShader <- function(node) {
  .Call("R_gsk_gl_shader_node_get_shader", node)$result
}


#' @rdname gsk
#' @title gskInsetShadowNodeNew
#'
#' @param outline RoundedRect
#' @param color Gdk.RGBA
#' @param dx gfloat
#' @param dy gfloat
#' @param spread gfloat
#' @param blur_radius gfloat
#' @return InsetShadowNode
#' @export
gskInsetShadowNodeNew <- function(outline, color, dx, dy, spread, blur_radius) {
  .Call("R_gsk_inset_shadow_node_new", outline, color, dx, dy, spread, blur_radius)$result
}


#' @rdname gsk
#' @title gskInsetShadowNodeGetBlurRadius
#'
#' @param node InsetShadowNode
#' @return gfloat
#' @export
gskInsetShadowNodeGetBlurRadius <- function(node) {
  .Call("R_gsk_inset_shadow_node_get_blur_radius", node)$result
}


#' @rdname gsk
#' @title gskInsetShadowNodeGetColor
#'
#' @param node InsetShadowNode
#' @return Gdk.RGBA
#' @export
gskInsetShadowNodeGetColor <- function(node) {
  .Call("R_gsk_inset_shadow_node_get_color", node)$result
}


#' @rdname gsk
#' @title gskInsetShadowNodeGetDx
#'
#' @param node InsetShadowNode
#' @return gfloat
#' @export
gskInsetShadowNodeGetDx <- function(node) {
  .Call("R_gsk_inset_shadow_node_get_dx", node)$result
}


#' @rdname gsk
#' @title gskInsetShadowNodeGetDy
#'
#' @param node InsetShadowNode
#' @return gfloat
#' @export
gskInsetShadowNodeGetDy <- function(node) {
  .Call("R_gsk_inset_shadow_node_get_dy", node)$result
}


#' @rdname gsk
#' @title gskInsetShadowNodeGetOutline
#'
#' @param node InsetShadowNode
#' @return RoundedRect
#' @export
gskInsetShadowNodeGetOutline <- function(node) {
  .Call("R_gsk_inset_shadow_node_get_outline", node)$result
}


#' @rdname gsk
#' @title gskInsetShadowNodeGetSpread
#'
#' @param node InsetShadowNode
#' @return gfloat
#' @export
gskInsetShadowNodeGetSpread <- function(node) {
  .Call("R_gsk_inset_shadow_node_get_spread", node)$result
}


#' @rdname gsk
#' @title gskIsolationNodeNew
#'
#' @param child RenderNode
#' @param isolations Isolation
#' @return IsolationNode
#' @export
gskIsolationNodeNew <- function(child, isolations) {
  .Call("R_gsk_isolation_node_new", child, isolations)$result
}


#' @rdname gsk
#' @title gskIsolationNodeGetChild
#'
#' @param node IsolationNode
#' @return RenderNode
#' @export
gskIsolationNodeGetChild <- function(node) {
  .Call("R_gsk_isolation_node_get_child", node)$result
}


#' @rdname gsk
#' @title gskIsolationNodeGetIsolations
#'
#' @param node IsolationNode
#' @return Isolation
#' @export
gskIsolationNodeGetIsolations <- function(node) {
  .Call("R_gsk_isolation_node_get_isolations", node)$result
}


#' @rdname gsk
#' @title gskLinearGradientNodeNew
#'
#' @param bounds Graphene.Rect
#' @param start Graphene.Point
#' @param end Graphene.Point
#' @param color_stops ColorStop
#' @param n_color_stops gsize
#' @return LinearGradientNode
#' @export
gskLinearGradientNodeNew <- function(bounds, start, end, color_stops, n_color_stops) {
  .Call("R_gsk_linear_gradient_node_new", bounds, start, end, color_stops, as.integer(n_color_stops))$result
}


#' @rdname gsk
#' @title gskLinearGradientNodeGetColorStops
#'
#' @param node LinearGradientNode
#' @return ColorStop
#' @export
gskLinearGradientNodeGetColorStops <- function(node) {
  .Call("R_gsk_linear_gradient_node_get_color_stops", node)
}


#' @rdname gsk
#' @title gskLinearGradientNodeGetEnd
#'
#' @param node LinearGradientNode
#' @return Graphene.Point
#' @export
gskLinearGradientNodeGetEnd <- function(node) {
  .Call("R_gsk_linear_gradient_node_get_end", node)$result
}


#' @rdname gsk
#' @title gskLinearGradientNodeGetNColorStops
#'
#' @param node LinearGradientNode
#' @return gsize
#' @export
gskLinearGradientNodeGetNColorStops <- function(node) {
  .Call("R_gsk_linear_gradient_node_get_n_color_stops", node)$result
}


#' @rdname gsk
#' @title gskLinearGradientNodeGetStart
#'
#' @param node LinearGradientNode
#' @return Graphene.Point
#' @export
gskLinearGradientNodeGetStart <- function(node) {
  .Call("R_gsk_linear_gradient_node_get_start", node)$result
}


#' @rdname gsk
#' @title gskMaskNodeNew
#'
#' @param source RenderNode
#' @param mask RenderNode
#' @param mask_mode MaskMode
#' @return MaskNode
#' @export
gskMaskNodeNew <- function(source, mask, mask_mode) {
  .Call("R_gsk_mask_node_new", source, mask, mask_mode)$result
}


#' @rdname gsk
#' @title gskMaskNodeGetMask
#'
#' @param node MaskNode
#' @return RenderNode
#' @export
gskMaskNodeGetMask <- function(node) {
  .Call("R_gsk_mask_node_get_mask", node)$result
}


#' @rdname gsk
#' @title gskMaskNodeGetMaskMode
#'
#' @param node MaskNode
#' @return MaskMode
#' @export
gskMaskNodeGetMaskMode <- function(node) {
  .Call("R_gsk_mask_node_get_mask_mode", node)$result
}


#' @rdname gsk
#' @title gskMaskNodeGetSource
#'
#' @param node MaskNode
#' @return RenderNode
#' @export
gskMaskNodeGetSource <- function(node) {
  .Call("R_gsk_mask_node_get_source", node)$result
}


#' @rdname gsk
#' @title gskNglRendererNew
#'
#' @return Renderer
#' @export
gskNglRendererNew <- function() {
  .Call("R_gsk_ngl_renderer_new")$result
}


#' @rdname gsk
#' @title gskOpacityNodeNew
#'
#' @param child RenderNode
#' @param opacity gfloat
#' @return OpacityNode
#' @export
gskOpacityNodeNew <- function(child, opacity) {
  .Call("R_gsk_opacity_node_new", child, opacity)$result
}


#' @rdname gsk
#' @title gskOpacityNodeGetChild
#'
#' @param node OpacityNode
#' @return RenderNode
#' @export
gskOpacityNodeGetChild <- function(node) {
  .Call("R_gsk_opacity_node_get_child", node)$result
}


#' @rdname gsk
#' @title gskOpacityNodeGetOpacity
#'
#' @param node OpacityNode
#' @return gfloat
#' @export
gskOpacityNodeGetOpacity <- function(node) {
  .Call("R_gsk_opacity_node_get_opacity", node)$result
}


#' @rdname gsk
#' @title gskOutsetShadowNodeNew
#'
#' @param outline RoundedRect
#' @param color Gdk.RGBA
#' @param dx gfloat
#' @param dy gfloat
#' @param spread gfloat
#' @param blur_radius gfloat
#' @return OutsetShadowNode
#' @export
gskOutsetShadowNodeNew <- function(outline, color, dx, dy, spread, blur_radius) {
  .Call("R_gsk_outset_shadow_node_new", outline, color, dx, dy, spread, blur_radius)$result
}


#' @rdname gsk
#' @title gskOutsetShadowNodeGetBlurRadius
#'
#' @param node OutsetShadowNode
#' @return gfloat
#' @export
gskOutsetShadowNodeGetBlurRadius <- function(node) {
  .Call("R_gsk_outset_shadow_node_get_blur_radius", node)$result
}


#' @rdname gsk
#' @title gskOutsetShadowNodeGetColor
#'
#' @param node OutsetShadowNode
#' @return Gdk.RGBA
#' @export
gskOutsetShadowNodeGetColor <- function(node) {
  .Call("R_gsk_outset_shadow_node_get_color", node)$result
}


#' @rdname gsk
#' @title gskOutsetShadowNodeGetDx
#'
#' @param node OutsetShadowNode
#' @return gfloat
#' @export
gskOutsetShadowNodeGetDx <- function(node) {
  .Call("R_gsk_outset_shadow_node_get_dx", node)$result
}


#' @rdname gsk
#' @title gskOutsetShadowNodeGetDy
#'
#' @param node OutsetShadowNode
#' @return gfloat
#' @export
gskOutsetShadowNodeGetDy <- function(node) {
  .Call("R_gsk_outset_shadow_node_get_dy", node)$result
}


#' @rdname gsk
#' @title gskOutsetShadowNodeGetOutline
#'
#' @param node OutsetShadowNode
#' @return RoundedRect
#' @export
gskOutsetShadowNodeGetOutline <- function(node) {
  .Call("R_gsk_outset_shadow_node_get_outline", node)$result
}


#' @rdname gsk
#' @title gskOutsetShadowNodeGetSpread
#'
#' @param node OutsetShadowNode
#' @return gfloat
#' @export
gskOutsetShadowNodeGetSpread <- function(node) {
  .Call("R_gsk_outset_shadow_node_get_spread", node)$result
}


#' @rdname gsk
#' @title gskPasteNodeNew
#'
#' @param bounds Graphene.Rect
#' @param depth gsize
#' @return PasteNode
#' @export
gskPasteNodeNew <- function(bounds, depth) {
  .Call("R_gsk_paste_node_new", bounds, as.integer(depth))$result
}


#' @rdname gsk
#' @title gskPasteNodeGetDepth
#'
#' @param node PasteNode
#' @return gsize
#' @export
gskPasteNodeGetDepth <- function(node) {
  .Call("R_gsk_paste_node_get_depth", node)$result
}


#' @rdname gsk
#' @title gskPathEqual
#'
#' @param path1 Path
#' @param path2 Path
#' @return gboolean
#' @export
gskPathEqual <- function(path1, path2) {
  .Call("R_gsk_path_equal", path1, path2)$result
}


#' @rdname gsk
#' @title gskPathForeach
#'
#' @param self Path
#' @param flags PathForeachFlags
#' @param func function — PathForeachFunc callback
#' @return gboolean
#' @export
gskPathForeach <- function(self, flags, func) {
  .Call("R_gsk_path_foreach", self, flags, func)$result
}


#' @rdname gsk
#' @title gskPathForeachIntersection
#'
#' @param path1 Path
#' @param path2 Path
#' @param func function — PathIntersectionFunc callback
#' @return gboolean
#' @export
gskPathForeachIntersection <- function(path1, path2, func) {
  .Call("R_gsk_path_foreach_intersection", path1, path2, func)$result
}


#' @rdname gsk
#' @title gskPathGetBounds
#'
#' @param self Path
#' @return gboolean
#' @export
gskPathGetBounds <- function(self) {
  .Call("R_gsk_path_get_bounds", self)
}


#' @rdname gsk
#' @title gskPathGetClosestPoint
#'
#' @param self Path
#' @param point Graphene.Point
#' @param threshold gfloat
#' @return gboolean
#' @export
gskPathGetClosestPoint <- function(self, point, threshold) {
  .Call("R_gsk_path_get_closest_point", self, point, threshold)
}


#' @rdname gsk
#' @title gskPathGetEndPoint
#'
#' @param self Path
#' @return gboolean
#' @export
gskPathGetEndPoint <- function(self) {
  .Call("R_gsk_path_get_end_point", self)
}


#' @rdname gsk
#' @title gskPathGetNext
#'
#' @param self Path
#' @return gboolean
#' @export
gskPathGetNext <- function(self) {
  .Call("R_gsk_path_get_next", self)
}


#' @rdname gsk
#' @title gskPathGetPrevious
#'
#' @param self Path
#' @return gboolean
#' @export
gskPathGetPrevious <- function(self) {
  .Call("R_gsk_path_get_previous", self)
}


#' @rdname gsk
#' @title gskPathGetStartPoint
#'
#' @param self Path
#' @return gboolean
#' @export
gskPathGetStartPoint <- function(self) {
  .Call("R_gsk_path_get_start_point", self)
}


#' @rdname gsk
#' @title gskPathGetStrokeBounds
#'
#' @param self Path
#' @param stroke Stroke
#' @return gboolean
#' @export
gskPathGetStrokeBounds <- function(self, stroke) {
  .Call("R_gsk_path_get_stroke_bounds", self, stroke)
}


#' @rdname gsk
#' @title gskPathGetTightBounds
#'
#' @param self Path
#' @return gboolean
#' @export
gskPathGetTightBounds <- function(self) {
  .Call("R_gsk_path_get_tight_bounds", self)
}


#' @rdname gsk
#' @title gskPathInFill
#'
#' @param self Path
#' @param point Graphene.Point
#' @param fill_rule FillRule
#' @return gboolean
#' @export
gskPathInFill <- function(self, point, fill_rule) {
  .Call("R_gsk_path_in_fill", self, point, fill_rule)$result
}


#' @rdname gsk
#' @title gskPathIsClosed
#'
#' @param self Path
#' @return gboolean
#' @export
gskPathIsClosed <- function(self) {
  .Call("R_gsk_path_is_closed", self)$result
}


#' @rdname gsk
#' @title gskPathIsEmpty
#'
#' @param self Path
#' @return gboolean
#' @export
gskPathIsEmpty <- function(self) {
  .Call("R_gsk_path_is_empty", self)$result
}


#' @rdname gsk
#' @title gskPathPrint
#'
#' @param self Path
#' @param string GLib.String
#' @return Return value from C function
#' @export
gskPathPrint <- function(self, string) {
  invisible(.Call("R_gsk_path_print", self, string))
}


#' @rdname gsk
#' @title gskPathRef
#'
#' @param self Path
#' @return Path
#' @export
gskPathRef <- function(self) {
  .Call("R_gsk_path_ref", self)$result
}


#' @rdname gsk
#' @title gskPathToCairo
#'
#' @param self Path
#' @param cr cairo.Context
#' @return Return value from C function
#' @export
gskPathToCairo <- function(self, cr) {
  invisible(.Call("R_gsk_path_to_cairo", self, cr))
}


#' @rdname gsk
#' @title gskPathToString
#'
#' @param self Path
#' @return utf8
#' @export
gskPathToString <- function(self) {
  .Call("R_gsk_path_to_string", self)$result
}


#' @rdname gsk
#' @title gskPathUnref
#'
#' @param self Path
#' @return Return value from C function
#' @export
gskPathUnref <- function(self) {
  invisible(.Call("R_gsk_path_unref", self))
}


#' @rdname gsk
#' @title gskPathParse
#'
#' @param string utf8
#' @return Path
#' @export
gskPathParse <- function(string) {
  .Call("R_gsk_path_parse", string)$result
}


#' @rdname gsk
#' @title gskPathBuilderNew
#'
#' @return PathBuilder
#' @export
gskPathBuilderNew <- function() {
  .Call("R_gsk_path_builder_new")$result
}


#' @rdname gsk
#' @title gskPathBuilderAddCairoPath
#'
#' @param self PathBuilder
#' @param path cairo.Path
#' @return Return value from C function
#' @export
gskPathBuilderAddCairoPath <- function(self, path) {
  invisible(.Call("R_gsk_path_builder_add_cairo_path", self, path))
}


#' @rdname gsk
#' @title gskPathBuilderAddCircle
#'
#' @param self PathBuilder
#' @param center Graphene.Point
#' @param radius gfloat
#' @return Return value from C function
#' @export
gskPathBuilderAddCircle <- function(self, center, radius) {
  invisible(.Call("R_gsk_path_builder_add_circle", self, center, radius))
}


#' @rdname gsk
#' @title gskPathBuilderAddLayout
#'
#' @param self PathBuilder
#' @param layout Pango.Layout
#' @return Return value from C function
#' @export
gskPathBuilderAddLayout <- function(self, layout) {
  invisible(.Call("R_gsk_path_builder_add_layout", self, layout))
}


#' @rdname gsk
#' @title gskPathBuilderAddPath
#'
#' @param self PathBuilder
#' @param path Path
#' @return Return value from C function
#' @export
gskPathBuilderAddPath <- function(self, path) {
  invisible(.Call("R_gsk_path_builder_add_path", self, path))
}


#' @rdname gsk
#' @title gskPathBuilderAddRect
#'
#' @param self PathBuilder
#' @param rect Graphene.Rect
#' @return Return value from C function
#' @export
gskPathBuilderAddRect <- function(self, rect) {
  invisible(.Call("R_gsk_path_builder_add_rect", self, rect))
}


#' @rdname gsk
#' @title gskPathBuilderAddReversePath
#'
#' @param self PathBuilder
#' @param path Path
#' @return Return value from C function
#' @export
gskPathBuilderAddReversePath <- function(self, path) {
  invisible(.Call("R_gsk_path_builder_add_reverse_path", self, path))
}


#' @rdname gsk
#' @title gskPathBuilderAddRoundedRect
#'
#' @param self PathBuilder
#' @param rect RoundedRect
#' @return Return value from C function
#' @export
gskPathBuilderAddRoundedRect <- function(self, rect) {
  invisible(.Call("R_gsk_path_builder_add_rounded_rect", self, rect))
}


#' @rdname gsk
#' @title gskPathBuilderAddSegment
#'
#' @param self PathBuilder
#' @param path Path
#' @param start PathPoint
#' @param end PathPoint
#' @return Return value from C function
#' @export
gskPathBuilderAddSegment <- function(self, path, start, end) {
  invisible(.Call("R_gsk_path_builder_add_segment", self, path, start, end))
}


#' @rdname gsk
#' @title gskPathBuilderArcTo
#'
#' @param self PathBuilder
#' @param x1 gfloat
#' @param y1 gfloat
#' @param x2 gfloat
#' @param y2 gfloat
#' @return Return value from C function
#' @export
gskPathBuilderArcTo <- function(self, x1, y1, x2, y2) {
  invisible(.Call("R_gsk_path_builder_arc_to", self, x1, y1, x2, y2))
}


#' @rdname gsk
#' @title gskPathBuilderClose
#'
#' @param self PathBuilder
#' @return Return value from C function
#' @export
gskPathBuilderClose <- function(self) {
  invisible(.Call("R_gsk_path_builder_close", self))
}


#' @rdname gsk
#' @title gskPathBuilderConicTo
#'
#' @param self PathBuilder
#' @param x1 gfloat
#' @param y1 gfloat
#' @param x2 gfloat
#' @param y2 gfloat
#' @param weight gfloat
#' @return Return value from C function
#' @export
gskPathBuilderConicTo <- function(self, x1, y1, x2, y2, weight) {
  invisible(.Call("R_gsk_path_builder_conic_to", self, x1, y1, x2, y2, weight))
}


#' @rdname gsk
#' @title gskPathBuilderCubicTo
#'
#' @param self PathBuilder
#' @param x1 gfloat
#' @param y1 gfloat
#' @param x2 gfloat
#' @param y2 gfloat
#' @param x3 gfloat
#' @param y3 gfloat
#' @return Return value from C function
#' @export
gskPathBuilderCubicTo <- function(self, x1, y1, x2, y2, x3, y3) {
  invisible(.Call("R_gsk_path_builder_cubic_to", self, x1, y1, x2, y2, x3, y3))
}


#' @rdname gsk
#' @title gskPathBuilderGetCurrentPoint
#'
#' @param self PathBuilder
#' @return Graphene.Point
#' @export
gskPathBuilderGetCurrentPoint <- function(self) {
  .Call("R_gsk_path_builder_get_current_point", self)$result
}


#' @rdname gsk
#' @title gskPathBuilderHtmlArcTo
#'
#' @param self PathBuilder
#' @param x1 gfloat
#' @param y1 gfloat
#' @param x2 gfloat
#' @param y2 gfloat
#' @param radius gfloat
#' @return Return value from C function
#' @export
gskPathBuilderHtmlArcTo <- function(self, x1, y1, x2, y2, radius) {
  invisible(.Call("R_gsk_path_builder_html_arc_to", self, x1, y1, x2, y2, radius))
}


#' @rdname gsk
#' @title gskPathBuilderLineTo
#'
#' @param self PathBuilder
#' @param x gfloat
#' @param y gfloat
#' @return Return value from C function
#' @export
gskPathBuilderLineTo <- function(self, x, y) {
  invisible(.Call("R_gsk_path_builder_line_to", self, x, y))
}


#' @rdname gsk
#' @title gskPathBuilderMoveTo
#'
#' @param self PathBuilder
#' @param x gfloat
#' @param y gfloat
#' @return Return value from C function
#' @export
gskPathBuilderMoveTo <- function(self, x, y) {
  invisible(.Call("R_gsk_path_builder_move_to", self, x, y))
}


#' @rdname gsk
#' @title gskPathBuilderQuadTo
#'
#' @param self PathBuilder
#' @param x1 gfloat
#' @param y1 gfloat
#' @param x2 gfloat
#' @param y2 gfloat
#' @return Return value from C function
#' @export
gskPathBuilderQuadTo <- function(self, x1, y1, x2, y2) {
  invisible(.Call("R_gsk_path_builder_quad_to", self, x1, y1, x2, y2))
}


#' @rdname gsk
#' @title gskPathBuilderRef
#'
#' @param self PathBuilder
#' @return PathBuilder
#' @export
gskPathBuilderRef <- function(self) {
  .Call("R_gsk_path_builder_ref", self)$result
}


#' @rdname gsk
#' @title gskPathBuilderRelArcTo
#'
#' @param self PathBuilder
#' @param x1 gfloat
#' @param y1 gfloat
#' @param x2 gfloat
#' @param y2 gfloat
#' @return Return value from C function
#' @export
gskPathBuilderRelArcTo <- function(self, x1, y1, x2, y2) {
  invisible(.Call("R_gsk_path_builder_rel_arc_to", self, x1, y1, x2, y2))
}


#' @rdname gsk
#' @title gskPathBuilderRelConicTo
#'
#' @param self PathBuilder
#' @param x1 gfloat
#' @param y1 gfloat
#' @param x2 gfloat
#' @param y2 gfloat
#' @param weight gfloat
#' @return Return value from C function
#' @export
gskPathBuilderRelConicTo <- function(self, x1, y1, x2, y2, weight) {
  invisible(.Call("R_gsk_path_builder_rel_conic_to", self, x1, y1, x2, y2, weight))
}


#' @rdname gsk
#' @title gskPathBuilderRelCubicTo
#'
#' @param self PathBuilder
#' @param x1 gfloat
#' @param y1 gfloat
#' @param x2 gfloat
#' @param y2 gfloat
#' @param x3 gfloat
#' @param y3 gfloat
#' @return Return value from C function
#' @export
gskPathBuilderRelCubicTo <- function(self, x1, y1, x2, y2, x3, y3) {
  invisible(.Call("R_gsk_path_builder_rel_cubic_to", self, x1, y1, x2, y2, x3, y3))
}


#' @rdname gsk
#' @title gskPathBuilderRelHtmlArcTo
#'
#' @param self PathBuilder
#' @param x1 gfloat
#' @param y1 gfloat
#' @param x2 gfloat
#' @param y2 gfloat
#' @param radius gfloat
#' @return Return value from C function
#' @export
gskPathBuilderRelHtmlArcTo <- function(self, x1, y1, x2, y2, radius) {
  invisible(.Call("R_gsk_path_builder_rel_html_arc_to", self, x1, y1, x2, y2, radius))
}


#' @rdname gsk
#' @title gskPathBuilderRelLineTo
#'
#' @param self PathBuilder
#' @param x gfloat
#' @param y gfloat
#' @return Return value from C function
#' @export
gskPathBuilderRelLineTo <- function(self, x, y) {
  invisible(.Call("R_gsk_path_builder_rel_line_to", self, x, y))
}


#' @rdname gsk
#' @title gskPathBuilderRelMoveTo
#'
#' @param self PathBuilder
#' @param x gfloat
#' @param y gfloat
#' @return Return value from C function
#' @export
gskPathBuilderRelMoveTo <- function(self, x, y) {
  invisible(.Call("R_gsk_path_builder_rel_move_to", self, x, y))
}


#' @rdname gsk
#' @title gskPathBuilderRelQuadTo
#'
#' @param self PathBuilder
#' @param x1 gfloat
#' @param y1 gfloat
#' @param x2 gfloat
#' @param y2 gfloat
#' @return Return value from C function
#' @export
gskPathBuilderRelQuadTo <- function(self, x1, y1, x2, y2) {
  invisible(.Call("R_gsk_path_builder_rel_quad_to", self, x1, y1, x2, y2))
}


#' @rdname gsk
#' @title gskPathBuilderRelSvgArcTo
#'
#' @param self PathBuilder
#' @param rx gfloat
#' @param ry gfloat
#' @param x_axis_rotation gfloat
#' @param large_arc gboolean
#' @param positive_sweep gboolean
#' @param x gfloat
#' @param y gfloat
#' @return Return value from C function
#' @export
gskPathBuilderRelSvgArcTo <- function(self, rx, ry, x_axis_rotation, large_arc, positive_sweep, x, y) {
  invisible(.Call("R_gsk_path_builder_rel_svg_arc_to", self, rx, ry, x_axis_rotation, large_arc, positive_sweep, x, y))
}


#' @rdname gsk
#' @title gskPathBuilderSvgArcTo
#'
#' @param self PathBuilder
#' @param rx gfloat
#' @param ry gfloat
#' @param x_axis_rotation gfloat
#' @param large_arc gboolean
#' @param positive_sweep gboolean
#' @param x gfloat
#' @param y gfloat
#' @return Return value from C function
#' @export
gskPathBuilderSvgArcTo <- function(self, rx, ry, x_axis_rotation, large_arc, positive_sweep, x, y) {
  invisible(.Call("R_gsk_path_builder_svg_arc_to", self, rx, ry, x_axis_rotation, large_arc, positive_sweep, x, y))
}


#' @rdname gsk
#' @title gskPathBuilderToPath
#'
#' @param self PathBuilder
#' @return Path
#' @export
gskPathBuilderToPath <- function(self) {
  .Call("R_gsk_path_builder_to_path", self)$result
}


#' @rdname gsk
#' @title gskPathBuilderUnref
#'
#' @param self PathBuilder
#' @return Return value from C function
#' @export
gskPathBuilderUnref <- function(self) {
  invisible(.Call("R_gsk_path_builder_unref", self))
}


#' @rdname gsk
#' @title gskPathMeasureNew
#'
#' @param path Path
#' @return PathMeasure
#' @export
gskPathMeasureNew <- function(path) {
  .Call("R_gsk_path_measure_new", path)$result
}


#' @rdname gsk
#' @title gskPathMeasureNewWithTolerance
#'
#' @param path Path
#' @param tolerance gfloat
#' @return PathMeasure
#' @export
gskPathMeasureNewWithTolerance <- function(path, tolerance) {
  .Call("R_gsk_path_measure_new_with_tolerance", path, tolerance)$result
}


#' @rdname gsk
#' @title gskPathMeasureGetLength
#'
#' @param self PathMeasure
#' @return gfloat
#' @export
gskPathMeasureGetLength <- function(self) {
  .Call("R_gsk_path_measure_get_length", self)$result
}


#' @rdname gsk
#' @title gskPathMeasureGetPath
#'
#' @param self PathMeasure
#' @return Path
#' @export
gskPathMeasureGetPath <- function(self) {
  .Call("R_gsk_path_measure_get_path", self)$result
}


#' @rdname gsk
#' @title gskPathMeasureGetPoint
#'
#' @param self PathMeasure
#' @param distance gfloat
#' @return gboolean
#' @export
gskPathMeasureGetPoint <- function(self, distance) {
  .Call("R_gsk_path_measure_get_point", self, distance)
}


#' @rdname gsk
#' @title gskPathMeasureGetTolerance
#'
#' @param self PathMeasure
#' @return gfloat
#' @export
gskPathMeasureGetTolerance <- function(self) {
  .Call("R_gsk_path_measure_get_tolerance", self)$result
}


#' @rdname gsk
#' @title gskPathMeasureRef
#'
#' @param self PathMeasure
#' @return PathMeasure
#' @export
gskPathMeasureRef <- function(self) {
  .Call("R_gsk_path_measure_ref", self)$result
}


#' @rdname gsk
#' @title gskPathMeasureUnref
#'
#' @param self PathMeasure
#' @return Return value from C function
#' @export
gskPathMeasureUnref <- function(self) {
  invisible(.Call("R_gsk_path_measure_unref", self))
}


#' @rdname gsk
#' @title gskPathPointCompare
#'
#' @param point1 PathPoint
#' @param point2 PathPoint
#' @return gint
#' @export
gskPathPointCompare <- function(point1, point2) {
  .Call("R_gsk_path_point_compare", point1, point2)$result
}


#' @rdname gsk
#' @title gskPathPointCopy
#'
#' @param point PathPoint
#' @return PathPoint
#' @export
gskPathPointCopy <- function(point) {
  .Call("R_gsk_path_point_copy", point)$result
}


#' @rdname gsk
#' @title gskPathPointEqual
#'
#' @param point1 PathPoint
#' @param point2 PathPoint
#' @return gboolean
#' @export
gskPathPointEqual <- function(point1, point2) {
  .Call("R_gsk_path_point_equal", point1, point2)$result
}


#' @rdname gsk
#' @title gskPathPointFree
#'
#' @param point PathPoint
#' @return Return value from C function
#' @export
gskPathPointFree <- function(point) {
  invisible(.Call("R_gsk_path_point_free", point))
}


#' @rdname gsk
#' @title gskPathPointGetCurvature
#'
#' @param point PathPoint
#' @param path Path
#' @param direction PathDirection
#' @return gfloat
#' @export
gskPathPointGetCurvature <- function(point, path, direction) {
  .Call("R_gsk_path_point_get_curvature", point, path, direction)
}


#' @rdname gsk
#' @title gskPathPointGetDistance
#'
#' @param point PathPoint
#' @param measure PathMeasure
#' @return gfloat
#' @export
gskPathPointGetDistance <- function(point, measure) {
  .Call("R_gsk_path_point_get_distance", point, measure)$result
}


#' @rdname gsk
#' @title gskPathPointGetPosition
#'
#' @param point PathPoint
#' @param path Path
#' @return Return value from C function
#' @export
gskPathPointGetPosition <- function(point, path) {
  .Call("R_gsk_path_point_get_position", point, path)$position
}


#' @rdname gsk
#' @title gskPathPointGetRotation
#'
#' @param point PathPoint
#' @param path Path
#' @param direction PathDirection
#' @return gfloat
#' @export
gskPathPointGetRotation <- function(point, path, direction) {
  .Call("R_gsk_path_point_get_rotation", point, path, direction)$result
}


#' @rdname gsk
#' @title gskPathPointGetTangent
#'
#' @param point PathPoint
#' @param path Path
#' @param direction PathDirection
#' @return Return value from C function
#' @export
gskPathPointGetTangent <- function(point, path, direction) {
  .Call("R_gsk_path_point_get_tangent", point, path, direction)$tangent
}


#' @rdname gsk
#' @title gskRadialGradientNodeNew
#'
#' @param bounds Graphene.Rect
#' @param center Graphene.Point
#' @param hradius gfloat
#' @param vradius gfloat
#' @param start gfloat
#' @param end gfloat
#' @param color_stops ColorStop
#' @param n_color_stops gsize
#' @return RadialGradientNode
#' @export
gskRadialGradientNodeNew <- function(bounds, center, hradius, vradius, start, end, color_stops, n_color_stops) {
  .Call("R_gsk_radial_gradient_node_new", bounds, center, hradius, vradius, start, end, color_stops, as.integer(n_color_stops))$result
}


#' @rdname gsk
#' @title gskRadialGradientNodeGetCenter
#'
#' @param node RadialGradientNode
#' @return Graphene.Point
#' @export
gskRadialGradientNodeGetCenter <- function(node) {
  .Call("R_gsk_radial_gradient_node_get_center", node)$result
}


#' @rdname gsk
#' @title gskRadialGradientNodeGetColorStops
#'
#' @param node RadialGradientNode
#' @return ColorStop
#' @export
gskRadialGradientNodeGetColorStops <- function(node) {
  .Call("R_gsk_radial_gradient_node_get_color_stops", node)
}


#' @rdname gsk
#' @title gskRadialGradientNodeGetEnd
#'
#' @param node RadialGradientNode
#' @return gfloat
#' @export
gskRadialGradientNodeGetEnd <- function(node) {
  .Call("R_gsk_radial_gradient_node_get_end", node)$result
}


#' @rdname gsk
#' @title gskRadialGradientNodeGetHradius
#'
#' @param node RadialGradientNode
#' @return gfloat
#' @export
gskRadialGradientNodeGetHradius <- function(node) {
  .Call("R_gsk_radial_gradient_node_get_hradius", node)$result
}


#' @rdname gsk
#' @title gskRadialGradientNodeGetNColorStops
#'
#' @param node RadialGradientNode
#' @return gsize
#' @export
gskRadialGradientNodeGetNColorStops <- function(node) {
  .Call("R_gsk_radial_gradient_node_get_n_color_stops", node)$result
}


#' @rdname gsk
#' @title gskRadialGradientNodeGetStart
#'
#' @param node RadialGradientNode
#' @return gfloat
#' @export
gskRadialGradientNodeGetStart <- function(node) {
  .Call("R_gsk_radial_gradient_node_get_start", node)$result
}


#' @rdname gsk
#' @title gskRadialGradientNodeGetVradius
#'
#' @param node RadialGradientNode
#' @return gfloat
#' @export
gskRadialGradientNodeGetVradius <- function(node) {
  .Call("R_gsk_radial_gradient_node_get_vradius", node)$result
}


#' @rdname gsk
#' @title gskRenderNodeDeserialize
#'
#' @param bytes GLib.Bytes
#' @param error_func function — ParseErrorFunc callback
#' @return RenderNode
#' @export
gskRenderNodeDeserialize <- function(bytes, error_func) {
  .Call("R_gsk_render_node_deserialize", bytes, error_func)$result
}


#' @rdname gsk
#' @title gskRenderNodeDraw
#'
#' @param node RenderNode
#' @param cr cairo.Context
#' @return Return value from C function
#' @export
gskRenderNodeDraw <- function(node, cr) {
  invisible(.Call("R_gsk_render_node_draw", node, cr))
}


#' @rdname gsk
#' @title gskRenderNodeGetBounds
#'
#' @param node RenderNode
#' @return Return value from C function
#' @export
gskRenderNodeGetBounds <- function(node) {
  .Call("R_gsk_render_node_get_bounds", node)$bounds
}


#' @rdname gsk
#' @title gskRenderNodeGetChildren
#'
#' @param self RenderNode
#' @return RenderNode
#' @export
gskRenderNodeGetChildren <- function(self) {
  .Call("R_gsk_render_node_get_children", self)
}


#' @rdname gsk
#' @title gskRenderNodeGetNodeType
#'
#' @param node RenderNode
#' @return RenderNodeType
#' @export
gskRenderNodeGetNodeType <- function(node) {
  .Call("R_gsk_render_node_get_node_type", node)$result
}


#' @rdname gsk
#' @title gskRenderNodeGetOpaqueRect
#'
#' @param self RenderNode
#' @return gboolean
#' @export
gskRenderNodeGetOpaqueRect <- function(self) {
  .Call("R_gsk_render_node_get_opaque_rect", self)
}


#' @rdname gsk
#' @title gskRenderNodeRef
#'
#' @param node RenderNode
#' @return RenderNode
#' @export
gskRenderNodeRef <- function(node) {
  .Call("R_gsk_render_node_ref", node)$result
}


#' @rdname gsk
#' @title gskRenderNodeSerialize
#'
#' @param node RenderNode
#' @return GLib.Bytes
#' @export
gskRenderNodeSerialize <- function(node) {
  .Call("R_gsk_render_node_serialize", node)$result
}


#' @rdname gsk
#' @title gskRenderNodeUnref
#'
#' @param node RenderNode
#' @return Return value from C function
#' @export
gskRenderNodeUnref <- function(node) {
  invisible(.Call("R_gsk_render_node_unref", node))
}


#' @rdname gsk
#' @title gskRenderNodeWriteToFile
#'
#' @param node RenderNode
#' @param filename filename
#' @return gboolean
#' @export
gskRenderNodeWriteToFile <- function(node, filename) {
  .Call("R_gsk_render_node_write_to_file", node, filename)$result
}


#' @rdname gsk
#' @title gskRenderReplayNew
#'
#' @return RenderReplay
#' @export
gskRenderReplayNew <- function() {
  .Call("R_gsk_render_replay_new")$result
}


#' @rdname gsk
#' @title gskRenderReplayDefault
#'
#' @param self RenderReplay
#' @param node RenderNode
#' @return RenderNode
#' @export
gskRenderReplayDefault <- function(self, node) {
  .Call("R_gsk_render_replay_default", self, node)$result
}


#' @rdname gsk
#' @title gskRenderReplayFilterFont
#'
#' @param self RenderReplay
#' @param font Pango.Font
#' @return Pango.Font
#' @export
gskRenderReplayFilterFont <- function(self, font) {
  .Call("R_gsk_render_replay_filter_font", self, font)$result
}


#' @rdname gsk
#' @title gskRenderReplayFilterNode
#'
#' @param self RenderReplay
#' @param node RenderNode
#' @return RenderNode
#' @export
gskRenderReplayFilterNode <- function(self, node) {
  .Call("R_gsk_render_replay_filter_node", self, node)$result
}


#' @rdname gsk
#' @title gskRenderReplayFilterTexture
#'
#' @param self RenderReplay
#' @param texture Gdk.Texture
#' @return Gdk.Texture
#' @export
gskRenderReplayFilterTexture <- function(self, texture) {
  .Call("R_gsk_render_replay_filter_texture", self, texture)$result
}


#' @rdname gsk
#' @title gskRenderReplayFree
#'
#' @param self RenderReplay
#' @return Return value from C function
#' @export
gskRenderReplayFree <- function(self) {
  invisible(.Call("R_gsk_render_replay_free", self))
}


#' @rdname gsk
#' @title gskRenderReplaySetFontFilter
#'
#' @param self RenderReplay
#' @param filter function — RenderReplayFontFilter callback
#' @return Return value from C function
#' @export
gskRenderReplaySetFontFilter <- function(self, filter) {
  invisible(.Call("R_gsk_render_replay_set_font_filter", self, filter))
}


#' @rdname gsk
#' @title gskRenderReplaySetNodeFilter
#'
#' @param self RenderReplay
#' @param filter function — RenderReplayNodeFilter callback
#' @return Return value from C function
#' @export
gskRenderReplaySetNodeFilter <- function(self, filter) {
  invisible(.Call("R_gsk_render_replay_set_node_filter", self, filter))
}


#' @rdname gsk
#' @title gskRenderReplaySetTextureFilter
#'
#' @param self RenderReplay
#' @param filter function — RenderReplayTextureFilter callback
#' @return Return value from C function
#' @export
gskRenderReplaySetTextureFilter <- function(self, filter) {
  invisible(.Call("R_gsk_render_replay_set_texture_filter", self, filter))
}


#' @rdname gsk
#' @title gskRendererNewForSurface
#'
#' @param surface Gdk.Surface
#' @return Renderer
#' @export
gskRendererNewForSurface <- function(surface) {
  .Call("R_gsk_renderer_new_for_surface", surface)$result
}


#' @rdname gsk
#' @title gskRendererGetSurface
#'
#' @param renderer Renderer
#' @return Gdk.Surface
#' @export
gskRendererGetSurface <- function(renderer) {
  .Call("R_gsk_renderer_get_surface", renderer)$result
}


#' @rdname gsk
#' @title gskRendererIsRealized
#'
#' @param renderer Renderer
#' @return gboolean
#' @export
gskRendererIsRealized <- function(renderer) {
  .Call("R_gsk_renderer_is_realized", renderer)$result
}


#' @rdname gsk
#' @title gskRendererRealize
#'
#' @param renderer Renderer
#' @param surface Gdk.Surface
#' @return gboolean
#' @export
gskRendererRealize <- function(renderer, surface) {
  .Call("R_gsk_renderer_realize", renderer, surface)$result
}


#' @rdname gsk
#' @title gskRendererRealizeForDisplay
#'
#' @param renderer Renderer
#' @param display Gdk.Display
#' @return gboolean
#' @export
gskRendererRealizeForDisplay <- function(renderer, display) {
  .Call("R_gsk_renderer_realize_for_display", renderer, display)$result
}


#' @rdname gsk
#' @title gskRendererRender
#'
#' @param renderer Renderer
#' @param root RenderNode
#' @param region cairo.Region
#' @return Return value from C function
#' @export
gskRendererRender <- function(renderer, root, region) {
  invisible(.Call("R_gsk_renderer_render", renderer, root, region))
}


#' @rdname gsk
#' @title gskRendererRenderTexture
#'
#' @param renderer Renderer
#' @param root RenderNode
#' @param viewport Graphene.Rect
#' @return Gdk.Texture
#' @export
gskRendererRenderTexture <- function(renderer, root, viewport) {
  .Call("R_gsk_renderer_render_texture", renderer, root, viewport)$result
}


#' @rdname gsk
#' @title gskRendererUnrealize
#'
#' @param renderer Renderer
#' @return Return value from C function
#' @export
gskRendererUnrealize <- function(renderer) {
  invisible(.Call("R_gsk_renderer_unrealize", renderer))
}


#' @rdname gsk
#' @title gskRepeatNodeNew
#'
#' @param bounds Graphene.Rect
#' @param child RenderNode
#' @param child_bounds Graphene.Rect
#' @return RepeatNode
#' @export
gskRepeatNodeNew <- function(bounds, child, child_bounds) {
  .Call("R_gsk_repeat_node_new", bounds, child, child_bounds)$result
}


#' @rdname gsk
#' @title gskRepeatNodeGetChild
#'
#' @param node RepeatNode
#' @return RenderNode
#' @export
gskRepeatNodeGetChild <- function(node) {
  .Call("R_gsk_repeat_node_get_child", node)$result
}


#' @rdname gsk
#' @title gskRepeatNodeGetChildBounds
#'
#' @param node RepeatNode
#' @return Graphene.Rect
#' @export
gskRepeatNodeGetChildBounds <- function(node) {
  .Call("R_gsk_repeat_node_get_child_bounds", node)$result
}


#' @rdname gsk
#' @title gskRepeatingLinearGradientNodeNew
#'
#' @param bounds Graphene.Rect
#' @param start Graphene.Point
#' @param end Graphene.Point
#' @param color_stops ColorStop
#' @param n_color_stops gsize
#' @return RepeatingLinearGradientNode
#' @export
gskRepeatingLinearGradientNodeNew <- function(bounds, start, end, color_stops, n_color_stops) {
  .Call("R_gsk_repeating_linear_gradient_node_new", bounds, start, end, color_stops, as.integer(n_color_stops))$result
}


#' @rdname gsk
#' @title gskRepeatingRadialGradientNodeNew
#'
#' @param bounds Graphene.Rect
#' @param center Graphene.Point
#' @param hradius gfloat
#' @param vradius gfloat
#' @param start gfloat
#' @param end gfloat
#' @param color_stops ColorStop
#' @param n_color_stops gsize
#' @return RepeatingRadialGradientNode
#' @export
gskRepeatingRadialGradientNodeNew <- function(bounds, center, hradius, vradius, start, end, color_stops, n_color_stops) {
  .Call("R_gsk_repeating_radial_gradient_node_new", bounds, center, hradius, vradius, start, end, color_stops, as.integer(n_color_stops))$result
}


#' @rdname gsk
#' @title gskRoundedClipNodeNew
#'
#' @param child RenderNode
#' @param clip RoundedRect
#' @return RoundedClipNode
#' @export
gskRoundedClipNodeNew <- function(child, clip) {
  .Call("R_gsk_rounded_clip_node_new", child, clip)$result
}


#' @rdname gsk
#' @title gskRoundedClipNodeGetChild
#'
#' @param node RoundedClipNode
#' @return RenderNode
#' @export
gskRoundedClipNodeGetChild <- function(node) {
  .Call("R_gsk_rounded_clip_node_get_child", node)$result
}


#' @rdname gsk
#' @title gskRoundedClipNodeGetClip
#'
#' @param node RoundedClipNode
#' @return RoundedRect
#' @export
gskRoundedClipNodeGetClip <- function(node) {
  .Call("R_gsk_rounded_clip_node_get_clip", node)$result
}


#' @rdname gsk
#' @title gskRoundedRectContainsPoint
#'
#' @param self RoundedRect
#' @param point Graphene.Point
#' @return gboolean
#' @export
gskRoundedRectContainsPoint <- function(self, point) {
  .Call("R_gsk_rounded_rect_contains_point", self, point)$result
}


#' @rdname gsk
#' @title gskRoundedRectContainsRect
#'
#' @param self RoundedRect
#' @param rect Graphene.Rect
#' @return gboolean
#' @export
gskRoundedRectContainsRect <- function(self, rect) {
  .Call("R_gsk_rounded_rect_contains_rect", self, rect)$result
}


#' @rdname gsk
#' @title gskRoundedRectInit
#'
#' @param self RoundedRect
#' @param bounds Graphene.Rect
#' @param top_left Graphene.Size
#' @param top_right Graphene.Size
#' @param bottom_right Graphene.Size
#' @param bottom_left Graphene.Size
#' @return RoundedRect
#' @export
gskRoundedRectInit <- function(self, bounds, top_left, top_right, bottom_right, bottom_left) {
  .Call("R_gsk_rounded_rect_init", self, bounds, top_left, top_right, bottom_right, bottom_left)$result
}


#' @rdname gsk
#' @title gskRoundedRectInitCopy
#'
#' @param self RoundedRect
#' @param src RoundedRect
#' @return RoundedRect
#' @export
gskRoundedRectInitCopy <- function(self, src) {
  .Call("R_gsk_rounded_rect_init_copy", self, src)$result
}


#' @rdname gsk
#' @title gskRoundedRectInitFromRect
#'
#' @param self RoundedRect
#' @param bounds Graphene.Rect
#' @param radius gfloat
#' @return RoundedRect
#' @export
gskRoundedRectInitFromRect <- function(self, bounds, radius) {
  .Call("R_gsk_rounded_rect_init_from_rect", self, bounds, radius)$result
}


#' @rdname gsk
#' @title gskRoundedRectIntersectsRect
#'
#' @param self RoundedRect
#' @param rect Graphene.Rect
#' @return gboolean
#' @export
gskRoundedRectIntersectsRect <- function(self, rect) {
  .Call("R_gsk_rounded_rect_intersects_rect", self, rect)$result
}


#' @rdname gsk
#' @title gskRoundedRectIsRectilinear
#'
#' @param self RoundedRect
#' @return gboolean
#' @export
gskRoundedRectIsRectilinear <- function(self) {
  .Call("R_gsk_rounded_rect_is_rectilinear", self)$result
}


#' @rdname gsk
#' @title gskRoundedRectNormalize
#'
#' @param self RoundedRect
#' @return RoundedRect
#' @export
gskRoundedRectNormalize <- function(self) {
  .Call("R_gsk_rounded_rect_normalize", self)$result
}


#' @rdname gsk
#' @title gskRoundedRectOffset
#'
#' @param self RoundedRect
#' @param dx gfloat
#' @param dy gfloat
#' @return RoundedRect
#' @export
gskRoundedRectOffset <- function(self, dx, dy) {
  .Call("R_gsk_rounded_rect_offset", self, dx, dy)$result
}


#' @rdname gsk
#' @title gskRoundedRectShrink
#'
#' @param self RoundedRect
#' @param top gfloat
#' @param right gfloat
#' @param bottom gfloat
#' @param left gfloat
#' @return RoundedRect
#' @export
gskRoundedRectShrink <- function(self, top, right, bottom, left) {
  .Call("R_gsk_rounded_rect_shrink", self, top, right, bottom, left)$result
}


#' @rdname gsk
#' @title gskSerializationErrorQuark
#'
#' @return GLib.Quark
#' @export
gskSerializationErrorQuark <- function() {
  .Call("R_gsk_serialization_error_quark")$result
}


#' @rdname gsk
#' @title gskShaderArgsBuilderNew
#'
#' @param shader GLShader
#' @param initial_values GLib.Bytes
#' @return ShaderArgsBuilder
#' @export
gskShaderArgsBuilderNew <- function(shader, initial_values) {
  .Call("R_gsk_shader_args_builder_new", shader, initial_values)$result
}


#' @rdname gsk
#' @title gskShaderArgsBuilderRef
#'
#' @param builder ShaderArgsBuilder
#' @return ShaderArgsBuilder
#' @export
gskShaderArgsBuilderRef <- function(builder) {
  .Call("R_gsk_shader_args_builder_ref", builder)$result
}


#' @rdname gsk
#' @title gskShaderArgsBuilderSetBool
#'
#' @param builder ShaderArgsBuilder
#' @param idx gint
#' @param value gboolean
#' @return Return value from C function
#' @export
gskShaderArgsBuilderSetBool <- function(builder, idx, value) {
  invisible(.Call("R_gsk_shader_args_builder_set_bool", builder, as.integer(idx), value))
}


#' @rdname gsk
#' @title gskShaderArgsBuilderSetFloat
#'
#' @param builder ShaderArgsBuilder
#' @param idx gint
#' @param value gfloat
#' @return Return value from C function
#' @export
gskShaderArgsBuilderSetFloat <- function(builder, idx, value) {
  invisible(.Call("R_gsk_shader_args_builder_set_float", builder, as.integer(idx), value))
}


#' @rdname gsk
#' @title gskShaderArgsBuilderSetInt
#'
#' @param builder ShaderArgsBuilder
#' @param idx gint
#' @param value gint32
#' @return Return value from C function
#' @export
gskShaderArgsBuilderSetInt <- function(builder, idx, value) {
  invisible(.Call("R_gsk_shader_args_builder_set_int", builder, as.integer(idx), as.integer(value)))
}


#' @rdname gsk
#' @title gskShaderArgsBuilderSetUint
#'
#' @param builder ShaderArgsBuilder
#' @param idx gint
#' @param value guint32
#' @return Return value from C function
#' @export
gskShaderArgsBuilderSetUint <- function(builder, idx, value) {
  invisible(.Call("R_gsk_shader_args_builder_set_uint", builder, as.integer(idx), value))
}


#' @rdname gsk
#' @title gskShaderArgsBuilderSetVec2
#'
#' @param builder ShaderArgsBuilder
#' @param idx gint
#' @param value Graphene.Vec2
#' @return Return value from C function
#' @export
gskShaderArgsBuilderSetVec2 <- function(builder, idx, value) {
  invisible(.Call("R_gsk_shader_args_builder_set_vec2", builder, as.integer(idx), value))
}


#' @rdname gsk
#' @title gskShaderArgsBuilderSetVec3
#'
#' @param builder ShaderArgsBuilder
#' @param idx gint
#' @param value Graphene.Vec3
#' @return Return value from C function
#' @export
gskShaderArgsBuilderSetVec3 <- function(builder, idx, value) {
  invisible(.Call("R_gsk_shader_args_builder_set_vec3", builder, as.integer(idx), value))
}


#' @rdname gsk
#' @title gskShaderArgsBuilderSetVec4
#'
#' @param builder ShaderArgsBuilder
#' @param idx gint
#' @param value Graphene.Vec4
#' @return Return value from C function
#' @export
gskShaderArgsBuilderSetVec4 <- function(builder, idx, value) {
  invisible(.Call("R_gsk_shader_args_builder_set_vec4", builder, as.integer(idx), value))
}


#' @rdname gsk
#' @title gskShaderArgsBuilderToArgs
#'
#' @param builder ShaderArgsBuilder
#' @return GLib.Bytes
#' @export
gskShaderArgsBuilderToArgs <- function(builder) {
  .Call("R_gsk_shader_args_builder_to_args", builder)$result
}


#' @rdname gsk
#' @title gskShaderArgsBuilderUnref
#'
#' @param builder ShaderArgsBuilder
#' @return Return value from C function
#' @export
gskShaderArgsBuilderUnref <- function(builder) {
  invisible(.Call("R_gsk_shader_args_builder_unref", builder))
}


#' @rdname gsk
#' @title gskShadowNodeNew
#'
#' @param child RenderNode
#' @param shadows Shadow
#' @param n_shadows gsize
#' @return ShadowNode
#' @export
gskShadowNodeNew <- function(child, shadows, n_shadows) {
  .Call("R_gsk_shadow_node_new", child, shadows, as.integer(n_shadows))$result
}


#' @rdname gsk
#' @title gskShadowNodeGetChild
#'
#' @param node ShadowNode
#' @return RenderNode
#' @export
gskShadowNodeGetChild <- function(node) {
  .Call("R_gsk_shadow_node_get_child", node)$result
}


#' @rdname gsk
#' @title gskShadowNodeGetNShadows
#'
#' @param node ShadowNode
#' @return gsize
#' @export
gskShadowNodeGetNShadows <- function(node) {
  .Call("R_gsk_shadow_node_get_n_shadows", node)$result
}


#' @rdname gsk
#' @title gskShadowNodeGetShadow
#'
#' @param node ShadowNode
#' @param i gsize
#' @return Shadow
#' @export
gskShadowNodeGetShadow <- function(node, i) {
  .Call("R_gsk_shadow_node_get_shadow", node, as.integer(i))$result
}


#' @rdname gsk
#' @title gskStrokeNew
#'
#' @param line_width gfloat
#' @return Stroke
#' @export
gskStrokeNew <- function(line_width) {
  .Call("R_gsk_stroke_new", line_width)$result
}


#' @rdname gsk
#' @title gskStrokeCopy
#'
#' @param other Stroke
#' @return Stroke
#' @export
gskStrokeCopy <- function(other) {
  .Call("R_gsk_stroke_copy", other)$result
}


#' @rdname gsk
#' @title gskStrokeFree
#'
#' @param self Stroke
#' @return Return value from C function
#' @export
gskStrokeFree <- function(self) {
  invisible(.Call("R_gsk_stroke_free", self))
}


#' @rdname gsk
#' @title gskStrokeGetDash
#'
#' @param self Stroke
#' @return gfloat
#' @export
gskStrokeGetDash <- function(self) {
  .Call("R_gsk_stroke_get_dash", self)
}


#' @rdname gsk
#' @title gskStrokeGetDashOffset
#'
#' @param self Stroke
#' @return gfloat
#' @export
gskStrokeGetDashOffset <- function(self) {
  .Call("R_gsk_stroke_get_dash_offset", self)$result
}


#' @rdname gsk
#' @title gskStrokeGetLineCap
#'
#' @param self Stroke
#' @return LineCap
#' @export
gskStrokeGetLineCap <- function(self) {
  .Call("R_gsk_stroke_get_line_cap", self)$result
}


#' @rdname gsk
#' @title gskStrokeGetLineJoin
#'
#' @param self Stroke
#' @return LineJoin
#' @export
gskStrokeGetLineJoin <- function(self) {
  .Call("R_gsk_stroke_get_line_join", self)$result
}


#' @rdname gsk
#' @title gskStrokeGetLineWidth
#'
#' @param self Stroke
#' @return gfloat
#' @export
gskStrokeGetLineWidth <- function(self) {
  .Call("R_gsk_stroke_get_line_width", self)$result
}


#' @rdname gsk
#' @title gskStrokeGetMiterLimit
#'
#' @param self Stroke
#' @return gfloat
#' @export
gskStrokeGetMiterLimit <- function(self) {
  .Call("R_gsk_stroke_get_miter_limit", self)$result
}


#' @rdname gsk
#' @title gskStrokeSetDash
#'
#' @param self Stroke
#' @param dash gfloat
#' @param n_dash gsize
#' @return Return value from C function
#' @export
gskStrokeSetDash <- function(self, dash, n_dash) {
  invisible(.Call("R_gsk_stroke_set_dash", self, dash, as.integer(n_dash)))
}


#' @rdname gsk
#' @title gskStrokeSetDashOffset
#'
#' @param self Stroke
#' @param offset gfloat
#' @return Return value from C function
#' @export
gskStrokeSetDashOffset <- function(self, offset) {
  invisible(.Call("R_gsk_stroke_set_dash_offset", self, offset))
}


#' @rdname gsk
#' @title gskStrokeSetLineCap
#'
#' @param self Stroke
#' @param line_cap LineCap
#' @return Return value from C function
#' @export
gskStrokeSetLineCap <- function(self, line_cap) {
  invisible(.Call("R_gsk_stroke_set_line_cap", self, line_cap))
}


#' @rdname gsk
#' @title gskStrokeSetLineJoin
#'
#' @param self Stroke
#' @param line_join LineJoin
#' @return Return value from C function
#' @export
gskStrokeSetLineJoin <- function(self, line_join) {
  invisible(.Call("R_gsk_stroke_set_line_join", self, line_join))
}


#' @rdname gsk
#' @title gskStrokeSetLineWidth
#'
#' @param self Stroke
#' @param line_width gfloat
#' @return Return value from C function
#' @export
gskStrokeSetLineWidth <- function(self, line_width) {
  invisible(.Call("R_gsk_stroke_set_line_width", self, line_width))
}


#' @rdname gsk
#' @title gskStrokeSetMiterLimit
#'
#' @param self Stroke
#' @param limit gfloat
#' @return Return value from C function
#' @export
gskStrokeSetMiterLimit <- function(self, limit) {
  invisible(.Call("R_gsk_stroke_set_miter_limit", self, limit))
}


#' @rdname gsk
#' @title gskStrokeToCairo
#'
#' @param self Stroke
#' @param cr cairo.Context
#' @return Return value from C function
#' @export
gskStrokeToCairo <- function(self, cr) {
  invisible(.Call("R_gsk_stroke_to_cairo", self, cr))
}


#' @rdname gsk
#' @title gskStrokeEqual
#'
#' @param stroke1 gpointer
#' @param stroke2 gpointer
#' @return gboolean
#' @export
gskStrokeEqual <- function(stroke1, stroke2) {
  .Call("R_gsk_stroke_equal", stroke1, stroke2)$result
}


#' @rdname gsk
#' @title gskStrokeNodeNew
#'
#' @param child RenderNode
#' @param path Path
#' @param stroke Stroke
#' @return StrokeNode
#' @export
gskStrokeNodeNew <- function(child, path, stroke) {
  .Call("R_gsk_stroke_node_new", child, path, stroke)$result
}


#' @rdname gsk
#' @title gskStrokeNodeGetChild
#'
#' @param node StrokeNode
#' @return RenderNode
#' @export
gskStrokeNodeGetChild <- function(node) {
  .Call("R_gsk_stroke_node_get_child", node)$result
}


#' @rdname gsk
#' @title gskStrokeNodeGetPath
#'
#' @param node StrokeNode
#' @return Path
#' @export
gskStrokeNodeGetPath <- function(node) {
  .Call("R_gsk_stroke_node_get_path", node)$result
}


#' @rdname gsk
#' @title gskStrokeNodeGetStroke
#'
#' @param node StrokeNode
#' @return Stroke
#' @export
gskStrokeNodeGetStroke <- function(node) {
  .Call("R_gsk_stroke_node_get_stroke", node)$result
}


#' @rdname gsk
#' @title gskSubsurfaceNodeGetChild
#'
#' @param node SubsurfaceNode
#' @return RenderNode
#' @export
gskSubsurfaceNodeGetChild <- function(node) {
  .Call("R_gsk_subsurface_node_get_child", node)$result
}


#' @rdname gsk
#' @title gskTextNodeNew
#'
#' @param font Pango.Font
#' @param glyphs Pango.GlyphString
#' @param color Gdk.RGBA
#' @param offset Graphene.Point
#' @return TextNode
#' @export
gskTextNodeNew <- function(font, glyphs, color, offset) {
  .Call("R_gsk_text_node_new", font, glyphs, color, offset)$result
}


#' @rdname gsk
#' @title gskTextNodeGetColor
#'
#' @param node TextNode
#' @return Gdk.RGBA
#' @export
gskTextNodeGetColor <- function(node) {
  .Call("R_gsk_text_node_get_color", node)$result
}


#' @rdname gsk
#' @title gskTextNodeGetFont
#'
#' @param node TextNode
#' @return Pango.Font
#' @export
gskTextNodeGetFont <- function(node) {
  .Call("R_gsk_text_node_get_font", node)$result
}


#' @rdname gsk
#' @title gskTextNodeGetGlyphs
#'
#' @param node TextNode
#' @return Pango.GlyphInfo
#' @export
gskTextNodeGetGlyphs <- function(node) {
  .Call("R_gsk_text_node_get_glyphs", node)
}


#' @rdname gsk
#' @title gskTextNodeGetNumGlyphs
#'
#' @param node TextNode
#' @return guint
#' @export
gskTextNodeGetNumGlyphs <- function(node) {
  .Call("R_gsk_text_node_get_num_glyphs", node)$result
}


#' @rdname gsk
#' @title gskTextNodeGetOffset
#'
#' @param node TextNode
#' @return Graphene.Point
#' @export
gskTextNodeGetOffset <- function(node) {
  .Call("R_gsk_text_node_get_offset", node)$result
}


#' @rdname gsk
#' @title gskTextNodeHasColorGlyphs
#'
#' @param node TextNode
#' @return gboolean
#' @export
gskTextNodeHasColorGlyphs <- function(node) {
  .Call("R_gsk_text_node_has_color_glyphs", node)$result
}


#' @rdname gsk
#' @title gskTextureNodeNew
#'
#' @param texture Gdk.Texture
#' @param bounds Graphene.Rect
#' @return TextureNode
#' @export
gskTextureNodeNew <- function(texture, bounds) {
  .Call("R_gsk_texture_node_new", texture, bounds)$result
}


#' @rdname gsk
#' @title gskTextureNodeGetTexture
#'
#' @param node TextureNode
#' @return Gdk.Texture
#' @export
gskTextureNodeGetTexture <- function(node) {
  .Call("R_gsk_texture_node_get_texture", node)$result
}


#' @rdname gsk
#' @title gskTextureScaleNodeNew
#'
#' @param texture Gdk.Texture
#' @param bounds Graphene.Rect
#' @param filter ScalingFilter
#' @return TextureScaleNode
#' @export
gskTextureScaleNodeNew <- function(texture, bounds, filter) {
  .Call("R_gsk_texture_scale_node_new", texture, bounds, filter)$result
}


#' @rdname gsk
#' @title gskTextureScaleNodeGetFilter
#'
#' @param node TextureScaleNode
#' @return ScalingFilter
#' @export
gskTextureScaleNodeGetFilter <- function(node) {
  .Call("R_gsk_texture_scale_node_get_filter", node)$result
}


#' @rdname gsk
#' @title gskTextureScaleNodeGetTexture
#'
#' @param node TextureScaleNode
#' @return Gdk.Texture
#' @export
gskTextureScaleNodeGetTexture <- function(node) {
  .Call("R_gsk_texture_scale_node_get_texture", node)$result
}


#' @rdname gsk
#' @title gskTransformNew
#'
#' @return Transform
#' @export
gskTransformNew <- function() {
  .Call("R_gsk_transform_new")$result
}


#' @rdname gsk
#' @title gskTransformEqual
#'
#' @param first Transform
#' @param second Transform
#' @return gboolean
#' @export
gskTransformEqual <- function(first, second) {
  .Call("R_gsk_transform_equal", first, second)$result
}


#' @rdname gsk
#' @title gskTransformGetCategory
#'
#' @param self Transform
#' @return TransformCategory
#' @export
gskTransformGetCategory <- function(self) {
  .Call("R_gsk_transform_get_category", self)$result
}


#' @rdname gsk
#' @title gskTransformInvert
#'
#' @param self Transform
#' @return Transform
#' @export
gskTransformInvert <- function(self) {
  .Call("R_gsk_transform_invert", self)$result
}


#' @rdname gsk
#' @title gskTransformMatrix
#'
#' @param next_ Transform
#' @param matrix Graphene.Matrix
#' @return Transform
#' @export
gskTransformMatrix <- function(next_, matrix) {
  .Call("R_gsk_transform_matrix", next_, matrix)$result
}


#' @rdname gsk
#' @title gskTransformMatrix2d
#'
#' @param next_ Transform
#' @param xx gfloat
#' @param yx gfloat
#' @param xy gfloat
#' @param yy gfloat
#' @param dx gfloat
#' @param dy gfloat
#' @return Transform
#' @export
gskTransformMatrix2d <- function(next_, xx, yx, xy, yy, dx, dy) {
  .Call("R_gsk_transform_matrix_2d", next_, xx, yx, xy, yy, dx, dy)$result
}


#' @rdname gsk
#' @title gskTransformPerspective
#'
#' @param next_ Transform
#' @param depth gfloat
#' @return Transform
#' @export
gskTransformPerspective <- function(next_, depth) {
  .Call("R_gsk_transform_perspective", next_, depth)$result
}


#' @rdname gsk
#' @title gskTransformPrint
#'
#' @param self Transform
#' @param string GLib.String
#' @return Return value from C function
#' @export
gskTransformPrint <- function(self, string) {
  invisible(.Call("R_gsk_transform_print", self, string))
}


#' @rdname gsk
#' @title gskTransformRef
#'
#' @param self Transform
#' @return Transform
#' @export
gskTransformRef <- function(self) {
  .Call("R_gsk_transform_ref", self)$result
}


#' @rdname gsk
#' @title gskTransformRotate
#'
#' @param next_ Transform
#' @param angle gfloat
#' @return Transform
#' @export
gskTransformRotate <- function(next_, angle) {
  .Call("R_gsk_transform_rotate", next_, angle)$result
}


#' @rdname gsk
#' @title gskTransformRotate3d
#'
#' @param next_ Transform
#' @param angle gfloat
#' @param axis Graphene.Vec3
#' @return Transform
#' @export
gskTransformRotate3d <- function(next_, angle, axis) {
  .Call("R_gsk_transform_rotate_3d", next_, angle, axis)$result
}


#' @rdname gsk
#' @title gskTransformScale
#'
#' @param next_ Transform
#' @param factor_x gfloat
#' @param factor_y gfloat
#' @return Transform
#' @export
gskTransformScale <- function(next_, factor_x, factor_y) {
  .Call("R_gsk_transform_scale", next_, factor_x, factor_y)$result
}


#' @rdname gsk
#' @title gskTransformScale3d
#'
#' @param next_ Transform
#' @param factor_x gfloat
#' @param factor_y gfloat
#' @param factor_z gfloat
#' @return Transform
#' @export
gskTransformScale3d <- function(next_, factor_x, factor_y, factor_z) {
  .Call("R_gsk_transform_scale_3d", next_, factor_x, factor_y, factor_z)$result
}


#' @rdname gsk
#' @title gskTransformSkew
#'
#' @param next_ Transform
#' @param skew_x gfloat
#' @param skew_y gfloat
#' @return Transform
#' @export
gskTransformSkew <- function(next_, skew_x, skew_y) {
  .Call("R_gsk_transform_skew", next_, skew_x, skew_y)$result
}


#' @rdname gsk
#' @title gskTransformTo2d
#'
#' @param self Transform
#' @return Return value from C function
#' @export
gskTransformTo2d <- function(self) {
  .Call("R_gsk_transform_to_2d", self)
}


#' @rdname gsk
#' @title gskTransformTo2dComponents
#'
#' @param self Transform
#' @return Return value from C function
#' @export
gskTransformTo2dComponents <- function(self) {
  .Call("R_gsk_transform_to_2d_components", self)
}


#' @rdname gsk
#' @title gskTransformToAffine
#'
#' @param self Transform
#' @return Return value from C function
#' @export
gskTransformToAffine <- function(self) {
  .Call("R_gsk_transform_to_affine", self)
}


#' @rdname gsk
#' @title gskTransformToMatrix
#'
#' @param self Transform
#' @return Return value from C function
#' @export
gskTransformToMatrix <- function(self) {
  .Call("R_gsk_transform_to_matrix", self)$out_matrix
}


#' @rdname gsk
#' @title gskTransformToString
#'
#' @param self Transform
#' @return utf8
#' @export
gskTransformToString <- function(self) {
  .Call("R_gsk_transform_to_string", self)$result
}


#' @rdname gsk
#' @title gskTransformToTranslate
#'
#' @param self Transform
#' @return Return value from C function
#' @export
gskTransformToTranslate <- function(self) {
  .Call("R_gsk_transform_to_translate", self)
}


#' @rdname gsk
#' @title gskTransformTransform
#'
#' @param next_ Transform
#' @param other Transform
#' @return Transform
#' @export
gskTransformTransform <- function(next_, other) {
  .Call("R_gsk_transform_transform", next_, other)$result
}


#' @rdname gsk
#' @title gskTransformTransformBounds
#'
#' @param self Transform
#' @param rect Graphene.Rect
#' @return Return value from C function
#' @export
gskTransformTransformBounds <- function(self, rect) {
  .Call("R_gsk_transform_transform_bounds", self, rect)$out_rect
}


#' @rdname gsk
#' @title gskTransformTransformPoint
#'
#' @param self Transform
#' @param point Graphene.Point
#' @return Return value from C function
#' @export
gskTransformTransformPoint <- function(self, point) {
  .Call("R_gsk_transform_transform_point", self, point)$out_point
}


#' @rdname gsk
#' @title gskTransformTranslate
#'
#' @param next_ Transform
#' @param point Graphene.Point
#' @return Transform
#' @export
gskTransformTranslate <- function(next_, point) {
  .Call("R_gsk_transform_translate", next_, point)$result
}


#' @rdname gsk
#' @title gskTransformTranslate3d
#'
#' @param next_ Transform
#' @param point Graphene.Point3D
#' @return Transform
#' @export
gskTransformTranslate3d <- function(next_, point) {
  .Call("R_gsk_transform_translate_3d", next_, point)$result
}


#' @rdname gsk
#' @title gskTransformUnref
#'
#' @param self Transform
#' @return Return value from C function
#' @export
gskTransformUnref <- function(self) {
  invisible(.Call("R_gsk_transform_unref", self))
}


#' @rdname gsk
#' @title gskTransformParse
#'
#' @param string utf8
#' @return gboolean
#' @export
gskTransformParse <- function(string) {
  .Call("R_gsk_transform_parse", string)
}


#' @rdname gsk
#' @title gskTransformNodeNew
#'
#' @param child RenderNode
#' @param transform Transform
#' @return TransformNode
#' @export
gskTransformNodeNew <- function(child, transform) {
  .Call("R_gsk_transform_node_new", child, transform)$result
}


#' @rdname gsk
#' @title gskTransformNodeGetChild
#'
#' @param node TransformNode
#' @return RenderNode
#' @export
gskTransformNodeGetChild <- function(node) {
  .Call("R_gsk_transform_node_get_child", node)$result
}


#' @rdname gsk
#' @title gskTransformNodeGetTransform
#'
#' @param node TransformNode
#' @return Transform
#' @export
gskTransformNodeGetTransform <- function(node) {
  .Call("R_gsk_transform_node_get_transform", node)$result
}


#' @rdname gsk
#' @title gskVulkanRendererNew
#'
#' @return Renderer
#' @export
gskVulkanRendererNew <- function() {
  .Call("R_gsk_vulkan_renderer_new")$result
}


#' @rdname gsk
#' @title gskValueDupRenderNode
#'
#' @param value GObject.Value
#' @return RenderNode
#' @export
gskValueDupRenderNode <- function(value) {
  .Call("R_gsk_value_dup_render_node", value)$result
}


#' @rdname gsk
#' @title gskValueGetRenderNode
#'
#' @param value GObject.Value
#' @return RenderNode
#' @export
gskValueGetRenderNode <- function(value) {
  .Call("R_gsk_value_get_render_node", value)$result
}


#' @rdname gsk
#' @title gskValueSetRenderNode
#'
#' @param value GObject.Value
#' @param node RenderNode
#' @return Return value from C function
#' @export
gskValueSetRenderNode <- function(value, node) {
  invisible(.Call("R_gsk_value_set_render_node", value, node))
}


#' @rdname gsk
#' @title gskValueTakeRenderNode
#'
#' @param value GObject.Value
#' @param node RenderNode
#' @return Return value from C function
#' @export
gskValueTakeRenderNode <- function(value, node) {
  invisible(.Call("R_gsk_value_take_render_node", value, node))
}


# Enumerations

# BlendMode
DEFAULT <- 0
MULTIPLY <- 1
SCREEN <- 2
OVERLAY <- 3
DARKEN <- 4
LIGHTEN <- 5
COLOR_DODGE <- 6
COLOR_BURN <- 7
HARD_LIGHT <- 8
SOFT_LIGHT <- 9
DIFFERENCE <- 10
EXCLUSION <- 11
COLOR <- 12
HUE <- 13
SATURATION <- 14
LUMINOSITY <- 15

# Corner
TOP_LEFT <- 0
TOP_RIGHT <- 1
BOTTOM_RIGHT <- 2
BOTTOM_LEFT <- 3

# FillRule
WINDING <- 0
EVEN_ODD <- 1

# GLUniformType
NONE <- 0
FLOAT <- 1
INT <- 2
UINT <- 3
BOOL <- 4
VEC2 <- 5
VEC3 <- 6
VEC4 <- 7

# Isolation
NONE <- 0
BACKGROUND <- 1
COPY_PASTE <- 2
ALL <- -1

# LineCap
BUTT <- 0
ROUND <- 1
SQUARE <- 2

# LineJoin
MITER <- 0
ROUND <- 1
BEVEL <- 2

# MaskMode
ALPHA <- 0
INVERTED_ALPHA <- 1
LUMINANCE <- 2
INVERTED_LUMINANCE <- 3

# PathDirection
FROM_START <- 0
TO_START <- 1
TO_END <- 2
FROM_END <- 3

# PathForeachFlags
ONLY_LINES <- 0
QUAD <- 1
CUBIC <- 2
CONIC <- 4

# PathIntersection
NONE <- 0
NORMAL <- 1
START <- 2
END <- 3

# PathOperation
MOVE <- 0
CLOSE <- 1
LINE <- 2
QUAD <- 3
CUBIC <- 4
CONIC <- 5

# PorterDuff
SOURCE <- 0
DEST <- 1
SOURCE_OVER_DEST <- 2
DEST_OVER_SOURCE <- 3
SOURCE_IN_DEST <- 4
DEST_IN_SOURCE <- 5
SOURCE_OUT_DEST <- 6
DEST_OUT_SOURCE <- 7
SOURCE_ATOP_DEST <- 8
DEST_ATOP_SOURCE <- 9
XOR <- 10
CLEAR <- 11

# RenderNodeType
NOT_A_RENDER_NODE <- 0
CONTAINER_NODE <- 1
CAIRO_NODE <- 2
COLOR_NODE <- 3
LINEAR_GRADIENT_NODE <- 4
REPEATING_LINEAR_GRADIENT_NODE <- 5
RADIAL_GRADIENT_NODE <- 6
REPEATING_RADIAL_GRADIENT_NODE <- 7
CONIC_GRADIENT_NODE <- 8
BORDER_NODE <- 9
TEXTURE_NODE <- 10
INSET_SHADOW_NODE <- 11
OUTSET_SHADOW_NODE <- 12
TRANSFORM_NODE <- 13
OPACITY_NODE <- 14
COLOR_MATRIX_NODE <- 15
REPEAT_NODE <- 16
CLIP_NODE <- 17
ROUNDED_CLIP_NODE <- 18
SHADOW_NODE <- 19
BLEND_NODE <- 20
CROSS_FADE_NODE <- 21
TEXT_NODE <- 22
BLUR_NODE <- 23
DEBUG_NODE <- 24
GL_SHADER_NODE <- 25
TEXTURE_SCALE_NODE <- 26
MASK_NODE <- 27
FILL_NODE <- 28
STROKE_NODE <- 29
SUBSURFACE_NODE <- 30
COMPONENT_TRANSFER_NODE <- 31
COPY_NODE <- 32
PASTE_NODE <- 33
COMPOSITE_NODE <- 34
ISOLATION_NODE <- 35
DISPLACEMENT_NODE <- 36
ARITHMETIC_NODE <- 37

# ScalingFilter
LINEAR <- 0
NEAREST <- 1
TRILINEAR <- 2

# SerializationError
UNSUPPORTED_FORMAT <- 0
UNSUPPORTED_VERSION <- 1
INVALID_DATA <- 2

# TransformCategory
UNKNOWN <- 0
ANY <- 1
X3D <- 2
X2D <- 3
X2D_AFFINE <- 4
X2D_TRANSLATE <- 5
IDENTITY <- 6
